plugins { id 'com.android.application' }

android {
    namespace 'com.kareem.lifeos'
    compileSdk 35

    defaultConfig {
        applicationId 'com.kareem.lifeos'
        minSdk 26
        targetSdk 35
        versionCode 14
        versionName '0.8.3-M1.4'
        testInstrumentationRunner 'android.test.InstrumentationTestRunner'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies { testImplementation 'junit:junit:4.13.2' }
