package com.kareem.lifeos;

import android.app.Activity;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import com.kareem.lifeos.actions.PersistentActionQueue;
import com.kareem.lifeos.actions.TeyaApprovalReceiver;
import java.text.DateFormat;
import java.util.Date;
import java.util.List;

/** Approval surface. External/write actions never execute merely because they were proposed. */
public final class ActionCenterActivity extends Activity {
    private static final int BG=Color.rgb(13,17,23),SURFACE=Color.rgb(22,27,34),BORDER=Color.rgb(48,54,61),TEXT=Color.rgb(230,237,243),MUTED=Color.rgb(139,148,158),GREEN=Color.rgb(63,185,80),BLUE=Color.rgb(47,129,247),RED=Color.rgb(248,81,73),YELLOW=Color.rgb(210,153,34);
    private PersistentActionQueue queue; private LinearLayout content; private Button pending,history;
    @Override public void onCreate(Bundle s){super.onCreate(s);queue=new PersistentActionQueue(this);render();showPending();}
    @Override protected void onResume(){super.onResume();if(content!=null)showPending();}

    private void render(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);head.setPadding(dp(14),dp(14),dp(14),dp(12));head.setBackgroundColor(SURFACE);Button back=secondary("‹");back.setOnClickListener(v->finish());head.addView(back,new LinearLayout.LayoutParams(dp(42),dp(40)));TextView title=text("Action Center",21,TEXT);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,-2,1);tp.setMargins(dp(10),0,0,0);head.addView(title,tp);root.addView(head);root.addView(divider());LinearLayout tabs=new LinearLayout(this);tabs.setPadding(dp(8),0,dp(8),0);pending=tab("Pending");history=tab("History");tabs.addView(pending,new LinearLayout.LayoutParams(0,dp(46),1));tabs.addView(history,new LinearLayout.LayoutParams(0,dp(46),1));root.addView(tabs);root.addView(divider());ScrollView scroll=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(16),dp(14),dp(16),dp(24));scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));pending.setOnClickListener(v->showPending());history.setOnClickListener(v->showHistory());setContentView(root);}

    private void showPending(){select(pending);content.removeAllViews();section("Approval required","Teya read-only tools may run immediately. Every write, call, timer, alarm, calendar, memory or other external action stops here first.");List<PersistentActionQueue.Item> xs=queue.pending();if(xs.isEmpty()){empty("No actions waiting for approval.");return;}for(PersistentActionQueue.Item x:xs)card(x,true);}
    private void showHistory(){select(history);content.removeAllViews();section("Action history","Proposal → approval → Teya actuator execution. Results stay visible here.");List<PersistentActionQueue.Item> xs=queue.history();if(xs.isEmpty()){empty("No action history yet.");return;}for(PersistentActionQueue.Item x:xs)card(x,false);}
    private void card(PersistentActionQueue.Item x,boolean controls){LinearLayout r=row();r.addView(badge(x.proposal.risk.name(),x.proposal.risk.name().contains("IRREVERSIBLE")||x.proposal.risk.name().contains("SENSITIVE")?RED:YELLOW));TextView t=text(x.proposal.actionType+(x.proposal.target.isEmpty()?"":" · "+x.proposal.target),15,TEXT);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);t.setPadding(0,dp(7),0,dp(4));r.addView(t);if(!x.proposal.payloadSummary.isEmpty())r.addView(text(x.proposal.payloadSummary,13,TEXT));r.addView(meta("state "+x.state+(x.proposal.situationId.isEmpty()?"":" · situation "+x.proposal.situationId)));if(x.approval!=null)r.addView(meta((x.approval.approved?"approved":"denied")+" · "+DateFormat.getDateTimeInstance(DateFormat.SHORT,DateFormat.SHORT).format(new Date(x.approval.approvedAt))));if(!x.result.isEmpty()){TextView result=text(x.result,12,"failed".equals(x.state)?RED:GREEN);result.setPadding(0,dp(8),0,0);r.addView(result);}if(controls){LinearLayout a=new LinearLayout(this);a.setPadding(0,dp(10),0,0);Button deny=secondary("Deny");deny.setTextColor(RED);deny.setOnClickListener(v->{queue.decide(x.proposal.proposalId,false);showPending();});Button approve=primary("Approve & execute");approve.setOnClickListener(v->{queue.decide(x.proposal.proposalId,true);TeyaApprovalReceiver.executeApproved(this,x);showHistory();});a.addView(deny,new LinearLayout.LayoutParams(0,dp(42),1));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(42),1);p.setMargins(dp(8),0,0,0);a.addView(approve,p);r.addView(a);}content.addView(r);}

    private void section(String t,String s){TextView h=text(t,20,TEXT);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);content.addView(h);TextView m=text(s,12,MUTED);m.setPadding(0,dp(3),0,dp(12));content.addView(m);}private void empty(String s){LinearLayout r=row();r.addView(text(s,14,MUTED));content.addView(r);}private LinearLayout row(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(14),dp(13),dp(14),dp(13));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(8));r.setLayoutParams(p);r.setBackground(round(SURFACE,BORDER,8));return r;}private TextView badge(String s,int c){TextView v=text(s,11,c);v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);v.setPadding(dp(8),dp(4),dp(8),dp(4));v.setBackground(round(Color.TRANSPARENT,c,20));return v;}private TextView meta(String s){TextView v=text(s,11,MUTED);v.setPadding(0,dp(8),0,0);return v;}private Button tab(String s){Button b=new Button(this);b.setText(s);b.setTextColor(MUTED);b.setTextSize(12);b.setAllCaps(false);b.setBackgroundColor(Color.TRANSPARENT);return b;}private void select(Button b){for(Button x:new Button[]{pending,history}){x.setTextColor(x==b?TEXT:MUTED);x.setTypeface(Typeface.DEFAULT,x==b?Typeface.BOLD:Typeface.NORMAL);}}private Button secondary(String s){Button b=new Button(this);b.setText(s);b.setTextColor(TEXT);b.setTextSize(12);b.setAllCaps(false);b.setGravity(Gravity.CENTER);b.setBackground(round(SURFACE,BORDER,7));return b;}private Button primary(String s){Button b=secondary(s);b.setBackground(round(BLUE,BLUE,7));b.setTextColor(Color.WHITE);return b;}private View divider(){View v=new View(this);v.setBackgroundColor(BORDER);v.setLayoutParams(new LinearLayout.LayoutParams(-1,dp(1)));return v;}private GradientDrawable round(int f,int s,int r){GradientDrawable g=new GradientDrawable();g.setColor(f);g.setCornerRadius(dp(r));g.setStroke(dp(1),s);return g;}private TextView text(String s,int n,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(n);v.setTextColor(c);v.setLineSpacing(0,1.08f);return v;}private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
}
