package com.kareem.lifeos;

import android.app.Activity;
import android.content.Intent;
import android.content.SharedPreferences;
import android.graphics.Color;
import android.os.Bundle;
import android.speech.RecognizerIntent;
import android.view.Gravity;
import android.view.View;
import android.view.inputmethod.EditorInfo;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import com.kareem.lifeos.actions.PersistentActionQueue;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;

/** Ask uses the same canonical objects visible in Now, Timeline and Search. */
public final class AskLifeOsActivity extends Activity {
    private static final int VOICE=51;private LinearLayout answers;private EditText input;private volatile boolean running;
    static final class Suggestion {final String q,sub,icon;final int color;Suggestion(String q,String sub,String icon,int color){this.q=q;this.sub=sub;this.icon=icon;this.color=color;}}
    @Override public void onCreate(Bundle s){super.onCreate(s);render();String initial=getIntent().getStringExtra("initial_question");if(initial!=null&&!initial.trim().isEmpty()){input.setText(initial.trim());input.setSelection(input.length());}}

    private void render(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(LifeOsUi.BG);LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);head.setPadding(LifeOsUi.dp(this,16),LifeOsUi.dp(this,8),LifeOsUi.dp(this,8),LifeOsUi.dp(this,5));TextView title=LifeOsUi.text(this,"Ask LifeOS",21.2f,LifeOsUi.TEXT);LifeOsUi.weight(title,700);head.addView(title,new LinearLayout.LayoutParams(0,-2,1));View history=LifeOsUi.iconTouch(this,LifeOsIconView.HISTORY,LifeOsUi.TEXT,22,42);history.setContentDescription("Recent questions");history.setOnClickListener(v->showHistory());head.addView(history,new LinearLayout.LayoutParams(LifeOsUi.dp(this,42),LifeOsUi.dp(this,42)));View more=LifeOsUi.iconTouch(this,LifeOsIconView.MORE,LifeOsUi.TEXT,21,42);more.setContentDescription("More");more.setOnClickListener(v->startActivity(new Intent(this,MainActivity.class)));head.addView(more,new LinearLayout.LayoutParams(LifeOsUi.dp(this,42),LifeOsUi.dp(this,42)));root.addView(head);
        ScrollView sc=new ScrollView(this);sc.setFillViewport(true);sc.setVerticalScrollBarEnabled(false);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(LifeOsUi.dp(this,16),0,LifeOsUi.dp(this,16),LifeOsUi.dp(this,8));View orb=LifeOsUi.orb(this);body.addView(orb,new LinearLayout.LayoutParams(-1,LifeOsUi.dp(this,154)));TextView hello=LifeOsUi.text(this,"How can I help you?",22f,LifeOsUi.TEXT);LifeOsUi.weight(hello,700);hello.setGravity(Gravity.CENTER);body.addView(hello);TextView sub=LifeOsUi.text(this,"Ask. Plan. Decide. Do. · Connected context only",11.7f,LifeOsUi.MUTED);LifeOsUi.weight(sub,500);sub.setGravity(Gravity.CENTER);sub.setPadding(0,LifeOsUi.dp(this,4),0,LifeOsUi.dp(this,14));body.addView(sub);for(Suggestion s:dynamicSuggestions())body.addView(promptRow(s));answers=new LinearLayout(this);answers.setOrientation(LinearLayout.VERTICAL);answers.setPadding(0,LifeOsUi.dp(this,6),0,0);body.addView(answers);sc.addView(body);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));
        LinearLayout composerWrap=new LinearLayout(this);composerWrap.setGravity(Gravity.CENTER_VERTICAL);composerWrap.setPadding(LifeOsUi.dp(this,14),LifeOsUi.dp(this,4),LifeOsUi.dp(this,14),LifeOsUi.dp(this,4));LinearLayout pill=new LinearLayout(this);pill.setGravity(Gravity.CENTER_VERTICAL);pill.setPadding(LifeOsUi.dp(this,15),0,LifeOsUi.dp(this,4),0);pill.setBackground(LifeOsUi.round(this,LifeOsUi.SURFACE_2,LifeOsUi.BORDER,25));input=new EditText(this);input.setHint("Ask anything…");input.setHintTextColor(LifeOsUi.MUTED);input.setTextColor(LifeOsUi.TEXT);input.setTextSize(LifeOsUi.refSp(12.2f));LifeOsUi.weight(input,500);input.setSingleLine(true);input.setGravity(Gravity.CENTER_VERTICAL);input.setImeOptions(EditorInfo.IME_ACTION_SEND);input.setBackgroundColor(Color.TRANSPARENT);input.setPadding(0,0,0,0);pill.addView(input,new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,48),1));View mic=LifeOsUi.iconTouch(this,LifeOsIconView.MIC,LifeOsUi.MUTED,20,40);mic.setContentDescription("Voice question");mic.setOnClickListener(v->startVoice());pill.addView(mic,new LinearLayout.LayoutParams(LifeOsUi.dp(this,40),LifeOsUi.dp(this,40)));composerWrap.addView(pill,new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,50),1));FrameLayout send=new FrameLayout(this);send.setBackground(LifeOsUi.round(this,LifeOsUi.BLUE,LifeOsUi.BLUE,100));send.setElevation(LifeOsUi.dp(this,3));LifeOsIconView plane=new LifeOsIconView(this,LifeOsIconView.SEND,Color.WHITE);send.addView(plane,new FrameLayout.LayoutParams(LifeOsUi.dp(this,22),LifeOsUi.dp(this,22),Gravity.CENTER));send.setOnClickListener(v->ask(input.getText().toString()));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(LifeOsUi.dp(this,48),LifeOsUi.dp(this,48));sp.setMargins(LifeOsUi.dp(this,7),0,0,0);composerWrap.addView(send,sp);input.setOnEditorActionListener((v,id,e)->{if(id==EditorInfo.IME_ACTION_SEND){ask(input.getText().toString());return true;}return false;});root.addView(composerWrap);root.addView(LifeOsUi.bottomNav(this,AskLifeOsActivity.class));setContentView(root);}

    private List<Suggestion> dynamicSuggestions(){ArrayList<Suggestion> out=new ArrayList<>();Set<String> seen=new HashSet<>();List<ObligationRepository.ObligationObject> obligations=ObligationRepository.open(this,20);if(!obligations.isEmpty())add(out,seen,new Suggestion("What needs my attention before tonight?",obligations.size()+" canonical open commitment"+(obligations.size()==1?"":"s")+" · prioritize only grounded next actions.",LifeOsIconView.ALERT,LifeOsUi.RED));List<ConversationRepository.ConversationObject> conversations=ConversationRepository.list(this,10);if(!conversations.isEmpty()){ConversationRepository.ConversationObject c=conversations.get(0);add(out,seen,new Suggestion("Catch me up on "+c.label+".",c.capturedCount+" persisted conversation items · use grounded evidence only.",LifeOsIconView.PEOPLE,LifeOsUi.PURPLE));}if(CalendarEventRepository.availability(this)==CalendarEventRepository.Availability.OPERATIONAL){List<CalendarEventRepository.CalendarEventObject> events=CalendarEventRepository.upcoming(this,10,7L*86400000L);if(!events.isEmpty()){CalendarEventRepository.CalendarEventObject e=events.get(0);add(out,seen,new Suggestion("What should I know about my upcoming event: "+(e.title.isEmpty()?"calendar event":e.title)+"?",new SimpleDateFormat("EEE, d MMM · HH:mm",Locale.getDefault()).format(new Date(e.begin))+(!e.location.isEmpty()?" · "+e.location:""),LifeOsIconView.EVENT,LifeOsUi.PURPLE));}}
        List<PersistentActionQueue.Item> actions=new PersistentActionQueue(this).pending();if(!actions.isEmpty()){PersistentActionQueue.Item a=actions.get(0);String target=a.proposal.target==null?"":a.proposal.target.trim();add(out,seen,new Suggestion(target.isEmpty()?"What action is ready for my approval?":"What action is ready for "+target+"?","This comes from a real pending action proposal in LifeOS.",LifeOsIconView.ACTION,LifeOsUi.GREEN));}
        List<CanonicalTimelineRepository.TimelineObject> recent=CanonicalTimelineRepository.recent(this,5);if(!recent.isEmpty())add(out,seen,new Suggestion("What happened recently?","Summarize the canonical timeline, not raw notification noise.",LifeOsIconView.TIMELINE,LifeOsUi.BLUE));if(out.isEmpty())add(out,seen,new Suggestion("What can LifeOS actually access right now?","Use only connected providers and clearly state what is unavailable.",LifeOsIconView.SEARCH,LifeOsUi.BLUE));return out.subList(0,Math.min(5,out.size()));}
    private static void add(List<Suggestion> out,Set<String> seen,Suggestion s){String k=s.q.toLowerCase(Locale.ROOT);if(seen.add(k))out.add(s);}
    private View promptRow(Suggestion s){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(LifeOsUi.dp(this,10),LifeOsUi.dp(this,7),LifeOsUi.dp(this,11),LifeOsUi.dp(this,7));row.setMinimumHeight(LifeOsUi.dp(this,56));row.setBackground(LifeOsUi.round(this,LifeOsUi.SURFACE,LifeOsUi.BORDER,14));row.addView(LifeOsUi.iconTile(this,s.icon,s.color,34),new LinearLayout.LayoutParams(LifeOsUi.dp(this,34),LifeOsUi.dp(this,34)));LinearLayout copy=new LinearLayout(this);copy.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(0,-2,1);cp.setMargins(LifeOsUi.dp(this,10),0,LifeOsUi.dp(this,7),0);row.addView(copy,cp);TextView q=LifeOsUi.text(this,s.q,11.5f,LifeOsUi.TEXT);LifeOsUi.weight(q,600);q.setMaxLines(2);copy.addView(q);TextView sub=LifeOsUi.text(this,s.sub,9.4f,LifeOsUi.MUTED);LifeOsUi.weight(sub,500);sub.setPadding(0,LifeOsUi.dp(this,2),0,0);sub.setMaxLines(2);copy.addView(sub);row.addView(LifeOsUi.icon(this,LifeOsIconView.CHEVRON,LifeOsUi.TERTIARY,12),new LinearLayout.LayoutParams(LifeOsUi.dp(this,12),LifeOsUi.dp(this,22)));row.setOnClickListener(v->{input.setText(s.q);ask(s.q);});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,LifeOsUi.dp(this,6));row.setLayoutParams(p);return row;}

    private void ask(String q){q=q==null?"":q.trim();if(q.isEmpty()||running)return;saveHistory(q);running=true;answers.removeAllViews();LinearLayout loading=LifeOsUi.card(this);TextView thinking=LifeOsUi.text(this,"Thinking with canonical connected LifeOS context…",10.5f,LifeOsUi.MUTED);LifeOsUi.weight(thinking,500);loading.addView(thinking);answers.addView(loading);final String question=q;new Thread(()->{String answer;try{String context=GroundedQueryEngine.context(this,question);if(BackgroundModelManager.isReadyFast(this)){File model=BackgroundModelManager.modelFile(this);String prompt="You are LifeOS, Kareem's private personal intelligence. Answer the QUESTION using ONLY the CANONICAL CONTEXT below. Never infer a file, place, project, decision, obligation, person relationship or action that is not explicitly represented there. Address Kareem as 'you'. If the requested capability is not connected, say so plainly. Prefer object-grounded next actions. Maximum 8 short sentences.\nQUESTION:\n"+question+"\n\n"+context;answer=BackgroundSemanticRuntime.generateFreeform(this,model.getAbsolutePath(),prompt);}else answer=GroundedQueryEngine.fallbackAnswer(this,question);}catch(Throwable e){answer=GroundedQueryEngine.fallbackAnswer(this,question);}final String out=UserFacingText.humanize(answer);runOnUiThread(()->{running=false;answers.removeAllViews();LinearLayout card=LifeOsUi.card(this);TextView k=LifeOsUi.text(this,"CANONICAL LIFE INTELLIGENCE",9f,LifeOsUi.BLUE);LifeOsUi.weight(k,700);card.addView(k);TextView a=LifeOsUi.text(this,out,11.5f,LifeOsUi.TEXT);LifeOsUi.weight(a,500);a.setPadding(0,LifeOsUi.dp(this,6),0,0);card.addView(a);answers.addView(card);});},"lifeos-ask").start();}
    private void showHistory(){answers.removeAllViews();List<String> xs=history();if(xs.isEmpty()){TextView none=LifeOsUi.text(this,"No recent questions yet.",11f,LifeOsUi.MUTED);LifeOsUi.weight(none,500);answers.addView(none);return;}TextView h=LifeOsUi.text(this,"Recent questions",12.5f,LifeOsUi.TEXT);LifeOsUi.weight(h,700);h.setPadding(0,0,0,LifeOsUi.dp(this,6));answers.addView(h);for(String q:xs){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(LifeOsUi.dp(this,10),0,LifeOsUi.dp(this,9),0);r.setBackground(LifeOsUi.round(this,LifeOsUi.SURFACE,LifeOsUi.BORDER,12));TextView t=LifeOsUi.text(this,q,11.5f,LifeOsUi.TEXT);LifeOsUi.weight(t,500);r.addView(t,new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,44),1));r.addView(LifeOsUi.icon(this,LifeOsIconView.CHEVRON,LifeOsUi.TERTIARY,11),new LinearLayout.LayoutParams(LifeOsUi.dp(this,11),LifeOsUi.dp(this,18)));r.setOnClickListener(v->{input.setText(q);ask(q);});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,LifeOsUi.dp(this,44));p.setMargins(0,0,0,LifeOsUi.dp(this,6));answers.addView(r,p);}}
    private void saveHistory(String value){String s=value==null?"":value.trim();if(s.isEmpty())return;ArrayList<String> h=new ArrayList<>(history());h.remove(s);h.add(0,s);while(h.size()>6)h.remove(h.size()-1);prefs().edit().putString("history",android.text.TextUtils.join("\u001f",h)).apply();}
    private List<String> history(){String raw=prefs().getString("history","");if(raw==null||raw.isEmpty())return new ArrayList<>();return new ArrayList<>(Arrays.asList(raw.split("\u001f")));}
    private SharedPreferences prefs(){return getSharedPreferences("lifeos_ask",MODE_PRIVATE);}
    private void startVoice(){try{Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);startActivityForResult(i,VOICE);}catch(Throwable ignored){}}
    @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){super.onActivityResult(requestCode,resultCode,data);if(requestCode==VOICE&&resultCode==RESULT_OK&&data!=null){ArrayList<String> xs=data.getStringArrayListExtra(RecognizerIntent.EXTRA_RESULTS);if(xs!=null&&!xs.isEmpty()){input.setText(xs.get(0));ask(xs.get(0));}}}
}
