package com.kareem.lifeos;

import android.app.Activity;
import android.graphics.Typeface;
import android.os.Bundle;
import android.view.Gravity;
import android.view.inputmethod.EditorInfo;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import java.io.File;

public final class AskLifeOsActivity extends Activity {
    private LinearLayout answers;private EditText input;private volatile boolean running;
    @Override public void onCreate(Bundle s){super.onCreate(s);render();}
    private void render(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(LifeOsUi.BG);root.addView(LifeOsUi.topBar(this,"Ask LifeOS",true));ScrollView sc=new ScrollView(this);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(LifeOsUi.dp(this,16),LifeOsUi.dp(this,10),LifeOsUi.dp(this,16),LifeOsUi.dp(this,16));TextView orb=LifeOsUi.text(this,"◯",72,LifeOsUi.BLUE);orb.setGravity(Gravity.CENTER);body.addView(orb,new LinearLayout.LayoutParams(-1,LifeOsUi.dp(this,104)));TextView hello=LifeOsUi.text(this,"How can I help you?",23,LifeOsUi.TEXT);hello.setTypeface(Typeface.DEFAULT,Typeface.BOLD);hello.setGravity(Gravity.CENTER);body.addView(hello);TextView sub=LifeOsUi.text(this,"Ask. Plan. Decide. Do.",13,LifeOsUi.MUTED);sub.setGravity(Gravity.CENTER);sub.setPadding(0,LifeOsUi.dp(this,4),0,LifeOsUi.dp(this,18));body.addView(sub);for(String q:new String[]{"What needs my attention today?","Summarize my conversations with Ahmed this week.","What did I miss in Gmail?","What did I decide about the car?","Draft a reply to GLIO with my car details."}){Button b=LifeOsUi.button(this,q+"  ›");b.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);b.setPadding(LifeOsUi.dp(this,14),0,LifeOsUi.dp(this,14),0);b.setOnClickListener(v->{input.setText(q);ask(q);});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,LifeOsUi.dp(this,54));p.setMargins(0,0,0,LifeOsUi.dp(this,8));body.addView(b,p);}answers=new LinearLayout(this);answers.setOrientation(LinearLayout.VERTICAL);answers.setPadding(0,LifeOsUi.dp(this,8),0,0);body.addView(answers);sc.addView(body);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));LinearLayout composer=new LinearLayout(this);composer.setPadding(LifeOsUi.dp(this,14),LifeOsUi.dp(this,7),LifeOsUi.dp(this,14),LifeOsUi.dp(this,7));input=new EditText(this);input.setHint("Ask anything…");input.setHintTextColor(LifeOsUi.MUTED);input.setTextColor(LifeOsUi.TEXT);input.setSingleLine(true);input.setImeOptions(EditorInfo.IME_ACTION_SEND);input.setBackground(LifeOsUi.round(this,LifeOsUi.SURFACE_2,LifeOsUi.BORDER,24));input.setPadding(LifeOsUi.dp(this,15),0,LifeOsUi.dp(this,15),0);Button send=LifeOsUi.primary(this,"↑");send.setTextSize(20);send.setOnClickListener(v->ask(input.getText().toString()));input.setOnEditorActionListener((v,id,e)->{if(id==EditorInfo.IME_ACTION_SEND){ask(input.getText().toString());return true;}return false;});composer.addView(input,new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,48),1));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(LifeOsUi.dp(this,48),LifeOsUi.dp(this,48));sp.setMargins(LifeOsUi.dp(this,8),0,0,0);composer.addView(send,sp);root.addView(composer);root.addView(LifeOsUi.bottomNav(this,AskLifeOsActivity.class));setContentView(root);}
    private void ask(String q){q=q==null?"":q.trim();if(q.isEmpty()||running)return;running=true;answers.removeAllViews();LinearLayout loading=LifeOsUi.card(this);loading.addView(LifeOsUi.text(this,"Thinking with your LifeOS memory…",13,LifeOsUi.MUTED));answers.addView(loading);final String question=q;new Thread(()->{String answer;try{String context=LifeIntelligenceEngine.context(this,question);if(BackgroundModelManager.isReadyFast(this)){File model=BackgroundModelManager.modelFile(this);String prompt="You are LifeOS, Karim's private personal intelligence. Answer the QUESTION using ONLY the grounded CONTEXT below. Address Karim directly as 'you'; never say 'the user'. Be concise, useful and explicit about uncertainty. Do not invent missing facts. Maximum 8 short sentences.\nQUESTION:\n"+question+"\n\n"+context;answer=BackgroundSemanticRuntime.generateFreeform(this,model.getAbsolutePath(),prompt);}else answer=LifeIntelligenceEngine.fallbackAnswer(this,question);}catch(Throwable e){answer=LifeIntelligenceEngine.fallbackAnswer(this,question);}final String out=UserFacingText.humanize(answer);runOnUiThread(()->{running=false;answers.removeAllViews();LinearLayout card=LifeOsUi.card(this);TextView k=LifeOsUi.text(this,"LIFE INTELLIGENCE",10,LifeOsUi.BLUE);k.setTypeface(Typeface.DEFAULT,Typeface.BOLD);card.addView(k);TextView a=LifeOsUi.text(this,out,14,LifeOsUi.TEXT);a.setPadding(0,LifeOsUi.dp(this,8),0,0);card.addView(a);answers.addView(card);});},"lifeos-ask").start();}
}
