package com.kareem.lifeos;

import android.Manifest;
import android.app.Activity;
import android.app.AlertDialog;
import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;
import java.util.List;

/** Deep browser backed only by registered functional providers. */
public final class CapabilityActivity extends Activity {
    private static final int PERMISSION=91,FILE_PICK=92,LOCATION_PERMISSION=93;private String capabilityId;
    @Override public void onCreate(Bundle state){super.onCreate(state);capabilityId=getIntent().getStringExtra("capability");if(capabilityId==null)capabilityId="conversations";render();}
    @Override protected void onResume(){super.onResume();if(capabilityId!=null)render();}

    private void render(){FunctionalCapabilityRegistry.Capability cap=FunctionalCapabilityRegistry.find(this,capabilityId);String title=cap==null?"LifeOS":cap.label;LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(LifeOsUi.BG);root.addView(LifeOsUi.detailTopBar(this,title));ScrollView sc=new ScrollView(this);sc.setVerticalScrollBarEnabled(false);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(LifeOsUi.dp(this,16),LifeOsUi.dp(this,6),LifeOsUi.dp(this,16),LifeOsUi.dp(this,24));sc.addView(body);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));if(cap==null){empty(body,"This capability is not registered as operational.");setContentView(root);return;}
        LinearLayout hero=LifeOsUi.card(this);LinearLayout hr=new LinearLayout(this);hr.setGravity(Gravity.CENTER_VERTICAL);hr.addView(LifeOsUi.iconTile(this,cap.icon,cap.color,42),new LinearLayout.LayoutParams(LifeOsUi.dp(this,42),LifeOsUi.dp(this,42)));LinearLayout copy=new LinearLayout(this);copy.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(0,-2,1);cp.setMargins(LifeOsUi.dp(this,11),0,0,0);hr.addView(copy,cp);TextView count=LifeOsUi.text(this,cap.countLine(),15f,LifeOsUi.TEXT);LifeOsUi.weight(count,700);copy.addView(count);TextView desc=LifeOsUi.text(this,cap.description,10.6f,LifeOsUi.MUTED);LifeOsUi.weight(desc,500);desc.setPadding(0,LifeOsUi.dp(this,2),0,0);copy.addView(desc);TextView sec=LifeOsUi.text(this,cap.status,9.8f,cap.availability==FunctionalCapabilityRegistry.Availability.OPERATIONAL?cap.color:LifeOsUi.AMBER);LifeOsUi.weight(sec,500);sec.setPadding(0,LifeOsUi.dp(this,3),0,0);copy.addView(sec);hero.addView(hr);body.addView(hero);
        if(cap.availability==FunctionalCapabilityRegistry.Availability.SETUP_REQUIRED){body.addView(LifeOsUi.section(this,"Set up"));LinearLayout setup=LifeOsUi.card(this);TextView info=LifeOsUi.text(this,setupText(),11f,LifeOsUi.TEXT);LifeOsUi.weight(info,500);setup.addView(info);Button enable=LifeOsUi.primary(this,"Allow access");enable.setOnClickListener(v->requestSetupPermission());LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,LifeOsUi.dp(this,44));bp.topMargin=LifeOsUi.dp(this,9);setup.addView(enable,bp);body.addView(setup);setContentView(root);return;}
        addProviderAction(body);body.addView(LifeOsUi.section(this,"Browse"));List<FunctionalCapabilityRegistry.ObjectItem> xs=FunctionalCapabilityRegistry.list(this,capabilityId,120);if(xs.isEmpty())empty(body,emptyText());else for(FunctionalCapabilityRegistry.ObjectItem r:xs)body.addView(resultRow(r,cap));setContentView(root);
    }

    private void addProviderAction(LinearLayout body){String label=null;if("files".equals(capabilityId))label="Connect a file";else if("projects".equals(capabilityId))label="Create project";else if("places".equals(capabilityId))label=PlaceRepository.availability(this)==PlaceRepository.Availability.OPERATIONAL?"Save current place":"Allow location to add places";else if("decisions".equals(capabilityId))label="Open Decision Memory";if(label==null)return;body.addView(LifeOsUi.section(this,"Add / manage"));Button action=LifeOsUi.primary(this,label);action.setOnClickListener(v->{if("files".equals(capabilityId))pickFile();else if("projects".equals(capabilityId))createProject();else if("places".equals(capabilityId)){if(PlaceRepository.availability(this)!=PlaceRepository.Availability.OPERATIONAL)requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},LOCATION_PERMISSION);else savePlace();}else if("decisions".equals(capabilityId))startActivity(new Intent(this,LifeSignalsActivity.class));});body.addView(action,new LinearLayout.LayoutParams(-1,LifeOsUi.dp(this,44)));}
    private View resultRow(FunctionalCapabilityRegistry.ObjectItem r,FunctionalCapabilityRegistry.Capability cap){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(0,LifeOsUi.dp(this,7),0,LifeOsUi.dp(this,7));row.addView(LifeOsUi.iconTile(this,cap.icon,cap.color,36),new LinearLayout.LayoutParams(LifeOsUi.dp(this,36),LifeOsUi.dp(this,36)));LinearLayout txt=new LinearLayout(this);txt.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,-2,1);tp.setMargins(LifeOsUi.dp(this,10),0,LifeOsUi.dp(this,8),0);row.addView(txt,tp);TextView t=LifeOsUi.text(this,r.title,12.4f,LifeOsUi.TEXT);LifeOsUi.weight(t,600);t.setMaxLines(1);txt.addView(t);if(!r.summary.isEmpty()){TextView s=LifeOsUi.text(this,r.summary,10.3f,LifeOsUi.MUTED);LifeOsUi.weight(s,500);s.setPadding(0,LifeOsUi.dp(this,2),0,0);s.setMaxLines(2);txt.addView(s);}if(!r.meta.isEmpty()){TextView m=LifeOsUi.text(this,r.meta,9.2f,cap.color);LifeOsUi.weight(m,500);m.setPadding(0,LifeOsUi.dp(this,2),0,0);m.setMaxLines(1);txt.addView(m);}row.addView(LifeOsUi.icon(this,LifeOsIconView.CHEVRON,LifeOsUi.TERTIARY,12),new LinearLayout.LayoutParams(LifeOsUi.dp(this,12),LifeOsUi.dp(this,22)));row.setOnClickListener(v->open(r));return row;}
    private void open(FunctionalCapabilityRegistry.ObjectItem r){if("conversations".equals(r.capabilityId)){startActivity(new Intent(this,ConversationDetailActivity.class).putExtra("conversation_id",r.objectId));return;}startActivity(new Intent(this,FunctionalObjectDetailActivity.class).putExtra("capability_id",r.capabilityId).putExtra("object_id",r.objectId));}

    private void pickFile(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,FILE_PICK);}
    private void createProject(){LinearLayout form=new LinearLayout(this);form.setOrientation(LinearLayout.VERTICAL);int p=LifeOsUi.dp(this,18);form.setPadding(p,0,p,0);EditText name=new EditText(this);name.setHint("Project name");name.setSingleLine(true);EditText desc=new EditText(this);desc.setHint("Description (optional)");desc.setMinLines(2);form.addView(name);form.addView(desc);new AlertDialog.Builder(this).setTitle("Create project").setView(form).setNegativeButton("Cancel",null).setPositiveButton("Create",(d,w)->{ProjectRepository.ProjectObject x=ProjectRepository.create(this,name.getText().toString(),desc.getText().toString());if(x==null)Toast.makeText(this,"Project name is required.",Toast.LENGTH_SHORT).show();else{Toast.makeText(this,"Project created",Toast.LENGTH_SHORT).show();render();}}).show();}
    private void savePlace(){EditText name=new EditText(this);name.setHint("Place name, e.g. Office");name.setSingleLine(true);int p=LifeOsUi.dp(this,18);name.setPadding(p,0,p,0);new AlertDialog.Builder(this).setTitle("Save current place").setMessage("LifeOS will save the current Android location evidence with the label you choose.").setView(name).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{Toast.makeText(this,"Getting current location…",Toast.LENGTH_SHORT).show();PlaceRepository.captureCurrent(this,name.getText().toString(),(place,error)->runOnUiThread(()->{if(place==null)Toast.makeText(this,error==null?"Could not save current place":error,Toast.LENGTH_LONG).show();else{Toast.makeText(this,"Place saved",Toast.LENGTH_SHORT).show();render();}}));}).show();}

    private String setupText(){if("people".equals(capabilityId))return "People is backed by Android Contacts. LifeOS will show only contacts Android allows it to read.";if("events".equals(capabilityId))return "Events is backed by Android Calendar. LifeOS will read real calendar events instead of guessing from notification text.";if("places".equals(capabilityId))return "Places uses Android location only when you explicitly choose to save your current place.";return "This source needs Android permission before LifeOS can expose it.";}
    private String emptyText(){if("files".equals(capabilityId))return "No files are connected yet. Use Connect a file to choose a real document through Android.";if("projects".equals(capabilityId))return "No projects exist yet. Create one to make it a real LifeOS object.";if("places".equals(capabilityId))return "No places are saved yet. Save your current location when you want LifeOS to remember a place.";if("decisions".equals(capabilityId))return "No decisions have been explicitly recorded in Decision Memory yet.";return "No real objects are available from this source yet.";}
    private void requestSetupPermission(){if("people".equals(capabilityId))requestPermissions(new String[]{Manifest.permission.READ_CONTACTS},PERMISSION);else if("events".equals(capabilityId))requestPermissions(new String[]{Manifest.permission.READ_CALENDAR},PERMISSION);else if("places".equals(capabilityId))requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},LOCATION_PERMISSION);}
    @Override public void onRequestPermissionsResult(int requestCode,String[] permissions,int[] grantResults){super.onRequestPermissionsResult(requestCode,permissions,grantResults);if(requestCode==PERMISSION)render();else if(requestCode==LOCATION_PERMISSION){render();if(PlaceRepository.availability(this)==PlaceRepository.Availability.OPERATIONAL)savePlace();}}
    @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){super.onActivityResult(requestCode,resultCode,data);if(requestCode==FILE_PICK&&resultCode==RESULT_OK&&data!=null&&data.getData()!=null){Uri uri=data.getData();try{int flags=data.getFlags()&(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION);getContentResolver().takePersistableUriPermission(uri,flags&Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}FileRepository.FileObject f=FileRepository.importUri(this,uri);Toast.makeText(this,f==null?"Could not connect this file":"File connected",f==null?Toast.LENGTH_LONG:Toast.LENGTH_SHORT).show();render();}}
    private void empty(LinearLayout body,String text){TextView none=LifeOsUi.text(this,text,11.5f,LifeOsUi.MUTED);LifeOsUi.weight(none,500);none.setPadding(0,LifeOsUi.dp(this,8),0,0);body.addView(none);}
}
