package com.kareem.lifeos;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.HorizontalScrollView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import java.util.ArrayList;
import java.util.List;

/** Consistent detail architecture: Summary -> What matters -> Related -> Evidence -> Actions. */
public final class EntityDetailActivity extends Activity {
    private String kind,title,summary;private long eventId;
    static Intent intent(Context c,String kind,String title,String summary,long eventId){return new Intent(c,EntityDetailActivity.class).putExtra("kind",kind).putExtra("title",title).putExtra("summary",summary).putExtra("event_id",eventId);}
    @Override public void onCreate(Bundle state){super.onCreate(state);Intent i=getIntent();kind=s(i.getStringExtra("kind"));title=s(i.getStringExtra("title"));summary=s(i.getStringExtra("summary"));eventId=i.getLongExtra("event_id",0);if(title.isEmpty())title=kind.isEmpty()?"LifeOS item":kind;render();}

    private void render(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(LifeOsUi.BG);root.addView(LifeOsUi.detailTopBar(this,title));ScrollView sc=new ScrollView(this);sc.setVerticalScrollBarEnabled(false);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(LifeOsUi.dp(this,16),LifeOsUi.dp(this,7),LifeOsUi.dp(this,16),LifeOsUi.dp(this,24));sc.addView(body);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));
        TextView eyebrow=LifeOsUi.text(this,kind.isEmpty()?"CONNECTED CONTEXT":kind.toUpperCase(),9.5f,accent());LifeOsUi.weight(eyebrow,700);body.addView(eyebrow);TextView h=LifeOsUi.text(this,title,19.5f,LifeOsUi.TEXT);LifeOsUi.weight(h,700);h.setPadding(0,LifeOsUi.dp(this,5),0,0);body.addView(h);
        body.addView(LifeOsUi.section(this,"Summary"));LinearLayout summaryCard=LifeOsUi.card(this);TextView sv=LifeOsUi.text(this,summary.isEmpty()?"LifeOS has grounded this item, but there is no concise summary yet.":summary,11.6f,LifeOsUi.TEXT);LifeOsUi.weight(sv,500);summaryCard.addView(sv);body.addView(summaryCard);
        List<LifeIntelligenceEngine.Result> related=related();body.addView(LifeOsUi.section(this,"What matters"));if(related.isEmpty()){TextView none=LifeOsUi.text(this,"No additional grounded context is connected yet.",10.6f,LifeOsUi.MUTED);LifeOsUi.weight(none,500);body.addView(none);}else{int shown=0;for(LifeIntelligenceEngine.Result r:related){if(shown++>=4)break;body.addView(relatedRow(r));}}
        body.addView(LifeOsUi.section(this,"Related"));body.addView(relatedChips());
        body.addView(LifeOsUi.section(this,"Evidence"));if(eventId>0){LinearLayout evidence=LifeOsUi.card(this);LinearLayout er=new LinearLayout(this);er.setGravity(Gravity.CENTER_VERTICAL);er.addView(LifeOsUi.iconTile(this,LifeOsIconView.FILE,LifeOsUi.BLUE,34),new LinearLayout.LayoutParams(LifeOsUi.dp(this,34),LifeOsUi.dp(this,34)));LinearLayout copy=new LinearLayout(this);copy.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams ep=new LinearLayout.LayoutParams(0,-2,1);ep.setMargins(LifeOsUi.dp(this,10),0,0,0);er.addView(copy,ep);TextView et=LifeOsUi.text(this,"Open source evidence",11.8f,LifeOsUi.TEXT);LifeOsUi.weight(et,600);copy.addView(et);TextView es=LifeOsUi.text(this,"See the captured event and provenance behind this item.",9.8f,LifeOsUi.MUTED);LifeOsUi.weight(es,500);copy.addView(es);er.addView(LifeOsUi.icon(this,LifeOsIconView.CHEVRON,LifeOsUi.TERTIARY,12),new LinearLayout.LayoutParams(LifeOsUi.dp(this,12),LifeOsUi.dp(this,20)));evidence.addView(er);evidence.setOnClickListener(v->startActivity(new Intent(this,EvidenceDetailActivity.class).putExtra("event_id",eventId).putExtra("mode","entity")));body.addView(evidence);}else{TextView no=LifeOsUi.text(this,"This item is grounded in LifeOS memory rather than one single source event.",10.5f,LifeOsUi.MUTED);LifeOsUi.weight(no,500);body.addView(no);}
        body.addView(LifeOsUi.section(this,"Actions"));LinearLayout actions=new LinearLayout(this);Button ask=LifeOsUi.primary(this,"Ask about this");ask.setOnClickListener(v->startActivity(new Intent(this,AskLifeOsActivity.class).putExtra("initial_question","Tell me what matters about "+title+" and what I should do next.")));actions.addView(ask,new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,44),1));Button search=LifeOsUi.button(this,"Search related");search.setOnClickListener(v->startActivity(new Intent(this,SearchActivity.class).putExtra("initial_query",title)));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,44),1);sp.setMargins(LifeOsUi.dp(this,8),0,0,0);actions.addView(search,sp);body.addView(actions);setContentView(root);
    }

    private List<LifeIntelligenceEngine.Result> related(){ArrayList<LifeIntelligenceEngine.Result> out=new ArrayList<>();for(LifeIntelligenceEngine.Result r:LifeIntelligenceEngine.search(this,title,14)){if(r.title.equalsIgnoreCase(title)&&r.summary.equalsIgnoreCase(summary))continue;out.add(r);}return out;}
    private View relatedRow(LifeIntelligenceEngine.Result r){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(0,LifeOsUi.dp(this,5),0,LifeOsUi.dp(this,5));row.addView(LifeOsUi.iconTile(this,iconFor(r.kind),colorFor(r.kind),32),new LinearLayout.LayoutParams(LifeOsUi.dp(this,32),LifeOsUi.dp(this,32)));LinearLayout txt=new LinearLayout(this);txt.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);p.setMargins(LifeOsUi.dp(this,9),0,LifeOsUi.dp(this,8),0);row.addView(txt,p);TextView t=LifeOsUi.text(this,r.title,11.6f,LifeOsUi.TEXT);LifeOsUi.weight(t,600);t.setMaxLines(1);txt.addView(t);TextView s=LifeOsUi.text(this,r.summary,9.8f,LifeOsUi.MUTED);LifeOsUi.weight(s,500);s.setMaxLines(1);txt.addView(s);row.addView(LifeOsUi.icon(this,LifeOsIconView.CHEVRON,LifeOsUi.TERTIARY,11),new LinearLayout.LayoutParams(LifeOsUi.dp(this,11),LifeOsUi.dp(this,18)));row.setOnClickListener(v->openRelated(r));return row;}
    private View relatedChips(){HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);LinearLayout row=new LinearLayout(this);for(LifeOsCapabilityRegistry.Capability c:LifeOsCapabilityRegistry.all(this)){if(c.count<=0)continue;Button b=LifeOsUi.chip(this,c.label,false);b.setOnClickListener(v->startActivity(new Intent(this,CapabilityActivity.class).putExtra("capability",c.id)));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,LifeOsUi.dp(this,34));p.setMargins(0,0,LifeOsUi.dp(this,7),0);row.addView(b,p);}hs.addView(row);return hs;}
    private void openRelated(LifeIntelligenceEngine.Result r){if("People".equalsIgnoreCase(r.kind)&&r.eventId>0){startActivity(new Intent(this,PersonDetailActivity.class).putExtra("event_id",r.eventId));return;}if("Conversation".equalsIgnoreCase(r.kind)&&r.eventId>0){startActivity(new Intent(this,ConversationDetailActivity.class).putExtra("event_id",r.eventId));return;}startActivity(intent(this,r.kind,r.title,r.summary,r.eventId));}
    private int accent(){return colorFor(kind);}private static int colorFor(String k){String x=s(k).toLowerCase();if(x.contains("people")||x.contains("person"))return LifeOsUi.PURPLE;if(x.contains("decision"))return LifeOsUi.PINK;if(x.contains("commit")||x.contains("attention"))return LifeOsUi.GREEN;if(x.contains("event")||x.contains("reminder"))return LifeOsUi.PURPLE;if(x.contains("file"))return LifeOsUi.AMBER;return LifeOsUi.BLUE;}private static String iconFor(String k){String x=s(k).toLowerCase();if(x.contains("people")||x.contains("person"))return LifeOsIconView.PEOPLE;if(x.contains("decision"))return LifeOsIconView.DECISION;if(x.contains("commit")||x.contains("attention"))return LifeOsIconView.COMMITMENT;if(x.contains("event")||x.contains("reminder"))return LifeOsIconView.EVENT;if(x.contains("place"))return LifeOsIconView.PLACE;return LifeOsIconView.FILE;}private static String s(String x){return x==null?"":x;}
}
