package com.kareem.lifeos;

import android.app.Activity;
import android.os.Bundle;
import android.text.TextUtils;
import android.view.View;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;
import java.text.DateFormat;
import java.util.Date;
import java.util.Locale;

/** Evidence is the provenance layer under every semantic surface. */
public final class EvidenceDetailActivity extends Activity {
    private LifeDb db;private long eventId,loopId;private LifeDb.Event event;private LifeDb.Loop loop;private AttentionStore.Item attention;
    @Override public void onCreate(Bundle s){super.onCreate(s);db=new LifeDb(this);eventId=getIntent().getLongExtra("event_id",0);loopId=getIntent().getLongExtra("loop_id",0);event=db.eventById(eventId);loop=loopId>0?db.loopById(loopId):null;attention=AttentionStore.get(this).forEvent(eventId);render();}
    @Override protected void onDestroy(){db.close();super.onDestroy();}
    private void render(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(LifeOsUi.BG);root.addView(LifeOsUi.detailTopBar(this,"Evidence"));ScrollView sc=new ScrollView(this);sc.setVerticalScrollBarEnabled(false);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(LifeOsUi.dp(this,16),LifeOsUi.dp(this,7),LifeOsUi.dp(this,16),LifeOsUi.dp(this,24));sc.addView(body);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));if(event==null){TextView none=LifeOsUi.text(this,"Original evidence is no longer available.",11.5f,LifeOsUi.MUTED);LifeOsUi.weight(none,500);body.addView(none);setContentView(root);return;}
        TextView source=LifeOsUi.text(this,LifeDb.friendlyApp(event.app).toUpperCase(),9.5f,LifeOsUi.BLUE);LifeOsUi.weight(source,700);body.addView(source);TextView h=LifeOsUi.text(this,heading(),19.5f,LifeOsUi.TEXT);LifeOsUi.weight(h,700);h.setPadding(0,LifeOsUi.dp(this,4),0,0);body.addView(h);TextView time=LifeOsUi.text(this,DateFormat.getDateTimeInstance(DateFormat.MEDIUM,DateFormat.SHORT).format(new Date(event.at)),10f,LifeOsUi.MUTED);LifeOsUi.weight(time,500);time.setPadding(0,LifeOsUi.dp(this,3),0,0);body.addView(time);
        body.addView(LifeOsUi.section(this,"Why it matters"));LinearLayout why=LifeOsUi.card(this);String reason=attention!=null&&!attention.reason.isEmpty()?attention.reason:loop!=null?reason(loop.kind):"This is grounded source evidence connected to something LifeOS surfaced.";TextView wr=LifeOsUi.text(this,UserFacingText.humanize(reason),11.2f,LifeOsUi.TEXT);LifeOsUi.weight(wr,500);why.addView(wr);if(attention!=null&&!attention.summary.isEmpty()){TextView ws=LifeOsUi.text(this,UserFacingText.humanize(attention.summary),9.8f,LifeOsUi.MUTED);LifeOsUi.weight(ws,500);ws.setPadding(0,LifeOsUi.dp(this,5),0,0);why.addView(ws);}body.addView(why);
        body.addView(LifeOsUi.section(this,"Original evidence"));LinearLayout original=LifeOsUi.card(this);TextView raw=LifeOsUi.text(this,event.body==null?"":event.body,11.4f,LifeOsUi.TEXT);LifeOsUi.weight(raw,500);raw.setMaxLines(7);raw.setEllipsize(TextUtils.TruncateAt.END);raw.setTextDirection(View.TEXT_DIRECTION_FIRST_STRONG);original.addView(raw);if(event.body!=null&&event.body.length()>320){Button more=LifeOsUi.button(this,"Show full evidence");more.setOnClickListener(v->{boolean full=raw.getMaxLines()>50;raw.setMaxLines(full?7:Integer.MAX_VALUE);raw.setEllipsize(full?TextUtils.TruncateAt.END:null);more.setText(full?"Show full evidence":"Collapse evidence");});LinearLayout.LayoutParams mp=new LinearLayout.LayoutParams(-1,LifeOsUi.dp(this,40));mp.setMargins(0,LifeOsUi.dp(this,8),0,0);original.addView(more,mp);}body.addView(original);
        body.addView(LifeOsUi.section(this,"Actions"));Button open=LifeOsUi.primary(this,SourceOpener.buttonLabel(this,eventId,event));open.setOnClickListener(v->{SourceOpener.Result r=SourceOpener.open(this,eventId,event);if(!r.opened||r.precision<SourceOpener.EXACT)Toast.makeText(this,r.message,Toast.LENGTH_LONG).show();});body.addView(open,new LinearLayout.LayoutParams(-1,LifeOsUi.dp(this,44)));boolean unresolved=(attention!=null&&attention.isOpen())||(loop!=null&&"open".equals(loop.status));if(unresolved){Button done=LifeOsUi.button(this,"Mark handled");LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,LifeOsUi.dp(this,44));p.setMargins(0,LifeOsUi.dp(this,7),0,0);done.setOnClickListener(v->{AttentionStore.get(this).markHandled(eventId);db.getWritableDatabase().execSQL("UPDATE open_loops SET status='done' WHERE evidence_id=? AND status='open'",new Object[]{eventId});finish();});body.addView(done,p);}setContentView(root);}
    private String heading(){String t=event.title==null?"":event.title.trim(),low=t.toLowerCase(Locale.ROOT);boolean generic=t.isEmpty()||low.equals("info")||low.equals("notification")||low.equals("message")||low.equals("visible conversation");if(generic&&attention!=null&&!attention.summary.isEmpty())return UserFacingText.humanize(attention.summary);if(generic&&loop!=null&&!loop.title.isEmpty())return UserFacingText.humanize(loop.title);return t.isEmpty()?LifeDb.friendlyApp(event.app):t;}
    private static String reason(String kind){if("security".equals(kind)||"brain_security".equals(kind))return "An account-access change may need verification.";if("financial_alert".equals(kind)||"brain_financial".equals(kind))return "A financial exception may need review.";if("deadline".equals(kind))return "A dated obligation may still need action.";if("appointment".equals(kind)||"brain_calendar".equals(kind))return "A scheduled plan may need preparation.";if("commitment".equals(kind))return "A concrete commitment is still open.";return "A direct request appears to need action from you.";}
}
