package com.kareem.lifeos;

import android.app.Activity;
import android.content.Intent;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;
import java.text.DateFormat;
import java.util.Date;

public final class EvidenceDetailActivity extends Activity {
    private static final int BG=Color.rgb(13,17,23),SURFACE=Color.rgb(22,27,34),BORDER=Color.rgb(48,54,61),TEXT=Color.rgb(230,237,243),MUTED=Color.rgb(139,148,158),GREEN=Color.rgb(63,185,80),BLUE=Color.rgb(47,129,247);
    private LifeDb db;private long eventId,loopId;private LifeDb.Event event;private LifeDb.Loop loop;private AttentionStore.Item attention;
    @Override public void onCreate(Bundle s){super.onCreate(s);db=new LifeDb(this);eventId=getIntent().getLongExtra("event_id",0);loopId=getIntent().getLongExtra("loop_id",0);event=db.eventById(eventId);loop=loopId>0?db.loopById(loopId):null;attention=AttentionStore.get(this).forEvent(eventId);render();}
    @Override protected void onDestroy(){db.close();super.onDestroy();}
    private void render(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.setPadding(dp(12),dp(10),dp(16),dp(8));top.setBackgroundColor(SURFACE);Button back=plain("‹");back.setContentDescription("Back");back.setOnClickListener(v->finish());top.addView(back,new LinearLayout.LayoutParams(dp(48),dp(48)));TextView title=text("Evidence",22,TEXT);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);top.addView(title);root.addView(top);root.addView(divider());ScrollView sc=new ScrollView(this);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(16),dp(18),dp(16),dp(28));sc.addView(body);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));if(event==null){body.addView(text("Original evidence is no longer available.",14,MUTED));setContentView(root);return;}TextView app=text(app(event.app),12,GREEN);app.setTypeface(Typeface.DEFAULT,Typeface.BOLD);body.addView(app);String heading=event.title==null||event.title.isEmpty()||"Visible conversation".equals(event.title)?LifeDb.personLabel(event):event.title;TextView h=text(heading,21,TEXT);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);h.setPadding(0,dp(8),0,dp(4));body.addView(h);body.addView(text(time(event.at),12,MUTED));
        if(attention!=null&&attention.isOpen()){LinearLayout reason=row();TextView rt=text(attention.provisional?"WHY THIS IS RESERVED":"WHY THIS SURFACED",11,GREEN);rt.setTypeface(Typeface.DEFAULT,Typeface.BOLD);reason.addView(rt);String why=attention.reason.isEmpty()?(attention.provisional?"Potentially actionable evidence is waiting for deep analysis.":"LifeOS identified an unresolved action for you."):attention.reason;TextView rb=text(why,14,TEXT);rb.setPadding(0,dp(7),0,0);reason.addView(rb);reason.addView(text(attention.summary,13,MUTED));body.addView(reason);}else if(loop!=null){LinearLayout reason=row();TextView rt=text("WHY THIS SURFACED",11,GREEN);rt.setTypeface(Typeface.DEFAULT,Typeface.BOLD);reason.addView(rt);TextView rb=text(reason(loop.kind),14,TEXT);rb.setPadding(0,dp(7),0,0);reason.addView(rb);reason.addView(text(loop.title,13,MUTED));body.addView(reason);}
        LinearLayout evidence=row();TextView et=text("Original evidence",13,MUTED);et.setTypeface(Typeface.DEFAULT,Typeface.BOLD);evidence.addView(et);TextView eb=text(event.body==null?"":event.body,15,TEXT);eb.setPadding(0,dp(8),0,0);evidence.addView(eb);body.addView(evidence);Button open=primary("Open source app");open.setOnClickListener(v->openSource());body.addView(open,new LinearLayout.LayoutParams(-1,dp(48)));
        boolean durableOpen=attention!=null&&attention.isOpen();boolean legacyOpen=loop!=null&&"open".equals(loop.status);
        if(durableOpen||legacyOpen){Button done=secondary("Mark handled");LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(48));p.setMargins(0,dp(9),0,0);done.setOnClickListener(v->{AttentionStore.get(this).markHandled(eventId);db.getWritableDatabase().execSQL("UPDATE open_loops SET status='done' WHERE evidence_id=? AND status='open'",new Object[]{eventId});finish();});body.addView(done,p);}
        TextView note=text("Opening or reading the source never marks this handled. Only Mark handled closes the attention item; captured evidence remains traceable to its source.",12,MUTED);note.setPadding(0,dp(16),0,0);body.addView(note);setContentView(root);}
    private void openSource(){try{String label=LifeDb.personLabel(event),digits=label.replaceAll("[^0-9+]","");if(event.app!=null&&event.app.toLowerCase().contains("whatsapp")&&digits.matches("\\+?[0-9]{8,}")){startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://wa.me/"+digits.replace("+",""))));return;}Intent launch=getPackageManager().getLaunchIntentForPackage(event.app);if(launch==null)throw new IllegalStateException();launch.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);startActivity(launch);}catch(Exception e){Toast.makeText(this,"Android cannot open a more precise destination. The captured original remains available here.",Toast.LENGTH_LONG).show();}}
    private LinearLayout row(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(14),dp(14),dp(14),dp(14));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(14),0,dp(12));c.setLayoutParams(p);c.setBackground(round(SURFACE,BORDER,9));return c;}private Button primary(String s){Button b=secondary(s);b.setBackground(round(BLUE,BLUE,8));b.setTextColor(Color.WHITE);return b;}private Button secondary(String s){Button b=new Button(this);b.setText(s);b.setTextColor(TEXT);b.setTextSize(13);b.setAllCaps(false);b.setBackground(round(SURFACE,BORDER,8));return b;}private Button plain(String s){Button b=secondary(s);b.setTextSize(18);b.setBackgroundColor(Color.TRANSPARENT);return b;}private View divider(){View v=new View(this);v.setBackgroundColor(BORDER);v.setLayoutParams(new LinearLayout.LayoutParams(-1,dp(1)));return v;}private GradientDrawable round(int fill,int stroke,int radius){GradientDrawable g=new GradientDrawable();g.setColor(fill);g.setCornerRadius(dp(radius));g.setStroke(dp(1),stroke);return g;}private TextView text(String s,int size,int color){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(color);v.setLineSpacing(0,1.08f);return v;}private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}private static String app(String p){return LifeDb.friendlyApp(p);}private static String reason(String kind){if("security".equals(kind))return "Account access or sign-in changed and should be verified.";if("financial_alert".equals(kind))return "A card, payment, or balance exception was detected.";if("deadline".equals(kind))return "The source contains an explicit date and an obligation.";if("appointment".equals(kind))return "The source contains scheduling intent and a time.";if("commitment".equals(kind))return "A concrete commitment remains open.";return "A direct request with an actionable verb was detected.";}private static String time(long at){return DateFormat.getDateTimeInstance(DateFormat.MEDIUM,DateFormat.SHORT).format(new Date(at));}
}
