package com.kareem.lifeos;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.Gravity;
import android.view.View;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.swiperefreshlayout.widget.SwipeRefreshLayout;
import com.kareem.lifeos.actions.PersistentActionQueue;
import com.kareem.lifeos.actions.TeyaApprovalReceiver;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;

/** Golden-reference Now: calm semantic triage, no raw capture or donor plumbing. */
public final class FeedActivity extends Activity {
    private LifeDb db;private LinearLayout content;private SwipeRefreshLayout swipe;private TextView status;private final Handler ui=new Handler(Looper.getMainLooper());
    @Override public void onCreate(Bundle s){super.onCreate(s);db=new LifeDb(this);render();}
    @Override protected void onResume(){super.onResume();refresh();}
    @Override protected void onDestroy(){db.close();super.onDestroy();}

    private void render(){
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(LifeOsUi.BG);
        LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.setPadding(LifeOsUi.dp(this,16),LifeOsUi.dp(this,7),LifeOsUi.dp(this,12),LifeOsUi.dp(this,1));
        LinearLayout brand=new LinearLayout(this);brand.setGravity(Gravity.CENTER_VERTICAL);brand.addView(LifeOsUi.icon(this,LifeOsIconView.LIFE,LifeOsUi.BLUE,18),new LinearLayout.LayoutParams(LifeOsUi.dp(this,18),LifeOsUi.dp(this,18)));TextView bt=LifeOsUi.text(this,"LifeOS",20.5f,LifeOsUi.TEXT);LifeOsUi.weight(bt,700);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-2,-2);bp.leftMargin=LifeOsUi.dp(this,8);brand.addView(bt,bp);top.addView(brand,new LinearLayout.LayoutParams(0,-2,1));
        TextView avatar=LifeOsUi.avatar(this,"K");avatar.setContentDescription("Settings and diagnostics");avatar.setOnClickListener(v->startActivity(new Intent(this,MainActivity.class)));top.addView(avatar,new LinearLayout.LayoutParams(LifeOsUi.dp(this,36),LifeOsUi.dp(this,36)));root.addView(top);
        status=LifeOsUi.text(this,"",10f,LifeOsUi.MUTED);status.setPadding(LifeOsUi.dp(this,16),0,LifeOsUi.dp(this,16),LifeOsUi.dp(this,3));status.setVisibility(View.GONE);root.addView(status);
        ScrollView sc=new ScrollView(this);sc.setFillViewport(true);sc.setVerticalScrollBarEnabled(false);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(LifeOsUi.dp(this,16),LifeOsUi.dp(this,2),LifeOsUi.dp(this,16),LifeOsUi.dp(this,14));sc.addView(content);
        swipe=new SwipeRefreshLayout(this);swipe.setColorSchemeColors(LifeOsUi.BLUE);swipe.setProgressBackgroundColorSchemeColor(LifeOsUi.SURFACE);swipe.addView(sc);swipe.setOnRefreshListener(this::manualRefresh);root.addView(swipe,new LinearLayout.LayoutParams(-1,0,1));root.addView(LifeOsUi.bottomNav(this,FeedActivity.class));setContentView(root);
    }
    private void manualRefresh(){refresh();try{BackgroundBrain.poke(this);}catch(Throwable ignored){}if(!BackgroundModelManager.isReadyFast(this))NotificationBrain.analyzeForeground(this,r->{if(!isFinishing())refresh();});ui.postDelayed(()->{if(swipe!=null)swipe.setRefreshing(false);refresh();},1000);}

    private void refresh(){
        if(content==null)return;content.removeAllViews();IntelligenceStatus.Snapshot is=IntelligenceStatus.snapshot(this);
        if(is.pending>0||is.provisional>0){status.setVisibility(View.VISIBLE);status.setText(is.pending+" processing"+(is.provisional>0?"  ·  "+is.provisional+" analyzing":""));status.setTextColor(LifeOsUi.MUTED);}else status.setVisibility(View.GONE);
        List<LifeDb.Loop> raw=db.openLoops(60);List<AttentionStore.Item> durable=dedupeDurable(AttentionStore.get(this).openItems(50));List<LifeDb.Loop> fallback=legacyNotCovered(raw,durable);PersistentActionQueue queue=new PersistentActionQueue(this);List<PersistentActionQueue.Item> actions=queue.pending();List<SituationEngine.Situation> allSituations=SituationEngine.build(db,raw,actions,System.currentTimeMillis());Set<Long> covered=coveredEvidence(durable,fallback);List<SituationEngine.Situation> situations=new ArrayList<>();for(SituationEngine.Situation s:allSituations)if(addsContext(s,covered))situations.add(s);
        int attention=durable.size()+fallback.size();int upcoming=countUpcoming(raw);
        TextView date=LifeOsUi.text(this,new SimpleDateFormat("EEE, d MMM yyyy",Locale.getDefault()).format(new Date()),10.8f,LifeOsUi.MUTED);content.addView(date);
        TextView greet=LifeOsUi.text(this,greeting()+", Kareem.",21.5f,LifeOsUi.TEXT);LifeOsUi.weight(greet,700);greet.setPadding(0,LifeOsUi.dp(this,3),0,0);content.addView(greet);
        TextView sub=LifeOsUi.text(this,"Here's what matters today.",11.7f,LifeOsUi.MUTED);sub.setPadding(0,LifeOsUi.dp(this,3),0,LifeOsUi.dp(this,10));content.addView(sub);
        stats(attention,actions.size(),upcoming);
        sectionRow("Needs Attention",attention>0?"See all":"",()->openSection("attention"));if(attention==0)quiet("Nothing needs your attention right now.");else{int shown=0;for(LifeDb.Loop x:fallback){if(x.dueAt<=0)continue;if(shown++>=3)break;loopCard(x);}for(AttentionStore.Item x:durable){if(shown++>=3)break;attentionCard(x);}for(LifeDb.Loop x:fallback){if(x.dueAt>0)continue;if(shown++>=3)break;loopCard(x);}}
        if(!actions.isEmpty()){sectionRow("Ready for your approval","See all",()->openSection("actions"));for(int i=0;i<Math.min(2,actions.size());i++)approvalCard(queue,actions.get(i));}
        if(!situations.isEmpty()){sectionRow("Situations",situations.size()>3?"See all":"",()->openSection("situations"));for(int i=0;i<Math.min(3,situations.size());i++)situationCard(situations.get(i));}
    }

    private void stats(int a,int actions,int upcoming){LinearLayout row=new LinearLayout(this);row.setPadding(0,0,0,LifeOsUi.dp(this,2));stat(row,String.valueOf(a),"Need attention",LifeOsIconView.ALERT,a>0?LifeOsUi.RED:LifeOsUi.TERTIARY);stat(row,String.valueOf(actions),"Ready actions",LifeOsIconView.ACTION,LifeOsUi.BLUE);stat(row,String.valueOf(upcoming),"Upcoming",LifeOsIconView.UPCOMING,LifeOsUi.TERTIARY);content.addView(row);}
    private void stat(LinearLayout row,String value,String label,String iconName,int color){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(LifeOsUi.dp(this,8),LifeOsUi.dp(this,7),LifeOsUi.dp(this,6),LifeOsUi.dp(this,6));c.setBackground(LifeOsUi.round(this,LifeOsUi.SURFACE,LifeOsUi.BORDER,13));LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.addView(LifeOsUi.icon(this,iconName,color,12),new LinearLayout.LayoutParams(LifeOsUi.dp(this,12),LifeOsUi.dp(this,12)));TextView n=LifeOsUi.text(this,value,16.5f,color);LifeOsUi.weight(n,700);LinearLayout.LayoutParams np=new LinearLayout.LayoutParams(-2,-2);np.leftMargin=LifeOsUi.dp(this,5);top.addView(n,np);c.addView(top);TextView l=LifeOsUi.text(this,label,9.1f,LifeOsUi.MUTED);l.setPadding(0,LifeOsUi.dp(this,3),0,0);c.addView(l);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,56),1);p.setMargins(0,0,LifeOsUi.dp(this,6),0);row.addView(c,p);}
    private void sectionRow(String title,String action,Runnable click){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(LifeOsUi.dp(this,1),LifeOsUi.dp(this,15),0,LifeOsUi.dp(this,7));TextView t=LifeOsUi.text(this,title,15.5f,LifeOsUi.TEXT);LifeOsUi.weight(t,700);r.addView(t,new LinearLayout.LayoutParams(0,-2,1));if(action!=null&&!action.isEmpty()){TextView a=LifeOsUi.text(this,action,10.5f,LifeOsUi.BLUE);LifeOsUi.weight(a,500);r.addView(a);r.setOnClickListener(v->click.run());}content.addView(r);}

    private void attentionCard(AttentionStore.Item x){LifeDb.Event e=db.eventById(x.eventId);LinearLayout c=LifeOsUi.card(this);LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);View icon=e!=null&&PresentationSemantics.preferSemanticIcon(this,e)?LifeOsUi.iconTile(this,PresentationSemantics.iconName(this,e),PresentationSemantics.iconAccent(this,e),38):e==null?LifeOsUi.iconTile(this,LifeOsIconView.ALERT,LifeOsUi.RED,38):LifeOsUi.appIcon(this,e.app,38);row.addView(icon,new LinearLayout.LayoutParams(LifeOsUi.dp(this,38),LifeOsUi.dp(this,38)));LinearLayout txt=new LinearLayout(this);txt.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,-2,1);tp.setMargins(LifeOsUi.dp(this,10),0,LifeOsUi.dp(this,5),0);row.addView(txt,tp);String title=e==null?UserFacingText.humanize(x.summary):PresentationSemantics.title(this,e);TextView t=LifeOsUi.text(this,title,12.8f,LifeOsUi.TEXT);LifeOsUi.weight(t,700);t.setMaxLines(2);txt.addView(t);String state=e==null?"":PresentationSemantics.status(this,e);if(state.isEmpty())state=x.provisional?"Analyzing":actionStatus(x.action,x.urgency);if(!state.isEmpty()){int sc=x.provisional?LifeOsUi.AMBER:PresentationSemantics.statusColor(this,e,state);TextView st=LifeOsUi.text(this,state,10.4f,sc);LifeOsUi.weight(st,500);st.setPadding(0,LifeOsUi.dp(this,2),0,0);txt.addView(st);}String summary=e==null?UserFacingText.humanize(x.summary):PresentationSemantics.summary(this,e);if(summary.isEmpty())summary=UserFacingText.humanize(x.summary);TextView s=LifeOsUi.text(this,summary,10.7f,LifeOsUi.MUTED);s.setPadding(0,LifeOsUi.dp(this,3),0,0);s.setMaxLines(2);txt.addView(s);row.addView(LifeOsUi.icon(this,LifeOsIconView.CHEVRON,LifeOsUi.MUTED,12),new LinearLayout.LayoutParams(LifeOsUi.dp(this,12),LifeOsUi.dp(this,18)));c.addView(row);c.setOnClickListener(v->startActivity(new Intent(this,EvidenceDetailActivity.class).putExtra("event_id",x.eventId)));content.addView(c);}
    private void loopCard(LifeDb.Loop x){LifeDb.Event e=db.eventById(x.evidenceId);LinearLayout c=LifeOsUi.card(this);LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);View icon=e!=null&&PresentationSemantics.preferSemanticIcon(this,e)?LifeOsUi.iconTile(this,PresentationSemantics.iconName(this,e),PresentationSemantics.iconAccent(this,e),38):e==null?LifeOsUi.iconTile(this,LifeOsIconView.ALERT,LifeOsUi.RED,38):LifeOsUi.appIcon(this,e.app,38);row.addView(icon,new LinearLayout.LayoutParams(LifeOsUi.dp(this,38),LifeOsUi.dp(this,38)));LinearLayout txt=new LinearLayout(this);txt.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,-2,1);tp.setMargins(LifeOsUi.dp(this,10),0,LifeOsUi.dp(this,5),0);row.addView(txt,tp);String title=e==null?UserFacingText.humanize(x.title):PresentationSemantics.title(this,e);TextView t=LifeOsUi.text(this,title,12.8f,LifeOsUi.TEXT);LifeOsUi.weight(t,700);t.setMaxLines(2);txt.addView(t);String state=x.dueAt>0?due(x.dueAt):humanKind(x.kind);TextView st=LifeOsUi.text(this,state,10.4f,PresentationSemantics.statusColor(this,e,state));LifeOsUi.weight(st,500);st.setPadding(0,LifeOsUi.dp(this,2),0,0);txt.addView(st);String summary=e==null?UserFacingText.humanize(x.title):PresentationSemantics.summary(this,e);TextView s=LifeOsUi.text(this,summary,10.7f,LifeOsUi.MUTED);s.setPadding(0,LifeOsUi.dp(this,3),0,0);s.setMaxLines(2);txt.addView(s);row.addView(LifeOsUi.icon(this,LifeOsIconView.CHEVRON,LifeOsUi.MUTED,12),new LinearLayout.LayoutParams(LifeOsUi.dp(this,12),LifeOsUi.dp(this,18)));c.addView(row);c.setOnClickListener(v->startActivity(new Intent(this,EvidenceDetailActivity.class).putExtra("event_id",x.evidenceId).putExtra("loop_id",x.id)));content.addView(c);}
    private void approvalCard(PersistentActionQueue queue,PersistentActionQueue.Item x){LinearLayout c=LifeOsUi.card(this);LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);head.addView(LifeOsUi.iconTile(this,LifeOsIconView.ACTION,LifeOsUi.GREEN,38),new LinearLayout.LayoutParams(LifeOsUi.dp(this,38),LifeOsUi.dp(this,38)));LinearLayout txt=new LinearLayout(this);txt.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,-2,1);tp.setMargins(LifeOsUi.dp(this,10),0,0,0);head.addView(txt,tp);String label=UserFacingText.humanize(x.proposal.payloadSummary.isEmpty()?x.proposal.actionType:x.proposal.payloadSummary);TextView t=LifeOsUi.text(this,label,12.8f,LifeOsUi.TEXT);LifeOsUi.weight(t,700);txt.addView(t);TextView meta=LifeOsUi.text(this,"Draft reply ready",10f,LifeOsUi.MUTED);meta.setPadding(0,LifeOsUi.dp(this,2),0,0);txt.addView(meta);if(!x.proposal.target.isEmpty()){TextView target=LifeOsUi.text(this,UserFacingText.humanize(x.proposal.target),10.7f,LifeOsUi.MUTED);target.setPadding(0,LifeOsUi.dp(this,3),0,0);txt.addView(target);}c.addView(head);LinearLayout a=new LinearLayout(this);a.setPadding(0,LifeOsUi.dp(this,8),0,0);android.widget.Button edit=LifeOsUi.button(this,"Edit");edit.setOnClickListener(v->{queue.decide(x.proposal.proposalId,false);refresh();});android.widget.Button approve=LifeOsUi.primary(this,"Approve");approve.setOnClickListener(v->{queue.decide(x.proposal.proposalId,true);TeyaApprovalReceiver.executeApproved(this,x);refresh();});a.addView(edit,new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,40),1));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,40),1);p.setMargins(LifeOsUi.dp(this,7),0,0,0);a.addView(approve,p);c.addView(a);content.addView(c);}
    private void situationCard(SituationEngine.Situation x){LinearLayout c=LifeOsUi.card(this);LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);LinearLayout txt=new LinearLayout(this);txt.setOrientation(LinearLayout.VERTICAL);TextView t=LifeOsUi.text(this,UserFacingText.humanize(x.title),12.8f,LifeOsUi.TEXT);LifeOsUi.weight(t,700);txt.addView(t);TextView s=LifeOsUi.text(this,UserFacingText.humanize(x.summary),10.7f,LifeOsUi.MUTED);s.setPadding(0,LifeOsUi.dp(this,3),0,0);s.setMaxLines(2);txt.addView(s);r.addView(txt,new LinearLayout.LayoutParams(0,-2,1));r.addView(LifeOsUi.icon(this,LifeOsIconView.CHEVRON,LifeOsUi.MUTED,12),new LinearLayout.LayoutParams(LifeOsUi.dp(this,12),LifeOsUi.dp(this,18)));c.addView(r);c.setOnClickListener(v->startActivity(new Intent(this,SituationDetailActivity.class).putExtra("situation_id",x.id)));content.addView(c);}
    private void quiet(String x){TextView t=LifeOsUi.text(this,x,10.7f,LifeOsUi.MUTED);t.setPadding(LifeOsUi.dp(this,2),LifeOsUi.dp(this,3),0,LifeOsUi.dp(this,5));content.addView(t);}
    private void openSection(String mode){startActivity(new Intent(this,FeedSectionActivity.class).putExtra("mode",mode));}

    private List<AttentionStore.Item> dedupeDurable(List<AttentionStore.Item> items){ArrayList<AttentionStore.Item> out=new ArrayList<>();Set<String> seen=new HashSet<>();for(AttentionStore.Item x:items){LifeDb.Event e=db.eventById(x.eventId);String key=e==null?"event:"+x.eventId:PresentationSemantics.attentionFingerprint(this,e);if(key.isEmpty())key="event:"+x.eventId;if(seen.add(key))out.add(x);}return out;}
    private List<LifeDb.Loop> legacyNotCovered(List<LifeDb.Loop> loops,List<AttentionStore.Item> items){Set<Long> ids=new HashSet<>();Set<String> semantic=new HashSet<>();for(AttentionStore.Item x:items){ids.add(x.eventId);LifeDb.Event e=db.eventById(x.eventId);if(e!=null)semantic.add(PresentationSemantics.attentionFingerprint(this,e));}ArrayList<LifeDb.Loop> out=new ArrayList<>();for(LifeDb.Loop x:loops){if(ids.contains(x.evidenceId))continue;LifeDb.Event e=db.eventById(x.evidenceId);String key=e==null?"loop:"+x.id:PresentationSemantics.attentionFingerprint(this,e);if(!key.isEmpty()&&semantic.contains(key))continue;if(!key.isEmpty())semantic.add(key);out.add(x);}return out;}
    private static Set<Long> coveredEvidence(List<AttentionStore.Item> durable,List<LifeDb.Loop> fallback){Set<Long> out=new HashSet<>();for(AttentionStore.Item x:durable)out.add(x.eventId);for(LifeDb.Loop x:fallback)out.add(x.evidenceId);return out;}
    private static boolean addsContext(SituationEngine.Situation s,Set<Long> covered){if(s==null)return false;if(s.evidenceIds==null||s.evidenceIds.isEmpty())return s.actionCount>0;boolean uncovered=false;for(Long id:s.evidenceIds)if(id!=null&&!covered.contains(id)){uncovered=true;break;}return uncovered||(s.evidenceIds.size()>1&&s.actionCount>0);}
    private static int countUpcoming(List<LifeDb.Loop> raw){int n=0;long now=System.currentTimeMillis();for(LifeDb.Loop x:raw){if(x.dueAt>now&&("appointment".equalsIgnoreCase(x.kind)||"event".equalsIgnoreCase(x.kind)||"reminder".equalsIgnoreCase(x.kind)))n++;}return n;}
    private static String greeting(){int h=java.util.Calendar.getInstance().get(java.util.Calendar.HOUR_OF_DAY);return h<12?"Good morning":h<18?"Good afternoon":"Good evening";}
    private String due(long at){long delta=at-System.currentTimeMillis();String date=new SimpleDateFormat("d MMM",Locale.getDefault()).format(new Date(at));if(delta>=0&&delta<36*60*60*1000L)return "Tomorrow · "+date;if(delta<0){long days=Math.max(1,Math.abs(delta)/(24*60*60*1000L));return "Overdue · "+days+" day"+(days==1?"":"s");}return "Due · "+date;}
    private static String humanKind(String x){String v=x==null?"":x.replace('_',' ').trim();if("deadline".equalsIgnoreCase(v))return "Due soon";if("appointment".equalsIgnoreCase(v))return "Scheduled";if("commitment".equalsIgnoreCase(v))return "Commitment";return v.isEmpty()?"Needs attention":Character.toUpperCase(v.charAt(0))+v.substring(1);}
    private static String actionStatus(String action,String urgency){String a=action==null?"":action;if("PAY".equals(a))return "Payment due";if("REPLY".equals(a))return "Waiting on you";if("CALL_BACK".equals(a))return "Call back";if("DO_TASK".equals(a))return "Action needed";return "HIGH".equals(urgency)?"Important":"";}
}
