package com.kareem.lifeos;

import android.app.Activity;
import android.content.Intent;
import android.graphics.Typeface;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.swiperefreshlayout.widget.SwipeRefreshLayout;
import com.kareem.lifeos.actions.PersistentActionQueue;
import com.kareem.lifeos.actions.TeyaApprovalReceiver;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;

/** Approved LifeOS reference UI: calm triage, contextual approvals, no donor plumbing. */
public final class FeedActivity extends Activity {
    private LifeDb db;private LinearLayout content;private SwipeRefreshLayout swipe;private TextView status;private final Handler ui=new Handler(Looper.getMainLooper());
    @Override public void onCreate(Bundle s){super.onCreate(s);db=new LifeDb(this);render();}
    @Override protected void onResume(){super.onResume();refresh();}
    @Override protected void onDestroy(){db.close();super.onDestroy();}

    private void render(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(LifeOsUi.BG);LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.setPadding(LifeOsUi.dp(this,16),LifeOsUi.dp(this,8),LifeOsUi.dp(this,12),0);TextView brand=LifeOsUi.text(this,"○ LifeOS",21,LifeOsUi.TEXT);brand.setTypeface(Typeface.DEFAULT,Typeface.BOLD);top.addView(brand,new LinearLayout.LayoutParams(0,-2,1));TextView avatar=LifeOsUi.avatar(this,"K");avatar.setContentDescription("Settings and diagnostics");avatar.setOnClickListener(v->startActivity(new Intent(this,MainActivity.class)));top.addView(avatar,new LinearLayout.LayoutParams(LifeOsUi.dp(this,38),LifeOsUi.dp(this,38)));root.addView(top);status=LifeOsUi.text(this,"",10,LifeOsUi.MUTED);status.setPadding(LifeOsUi.dp(this,17),0,LifeOsUi.dp(this,17),LifeOsUi.dp(this,5));root.addView(status);ScrollView sc=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(LifeOsUi.dp(this,16),0,LifeOsUi.dp(this,16),LifeOsUi.dp(this,16));sc.addView(content);swipe=new SwipeRefreshLayout(this);swipe.setColorSchemeColors(LifeOsUi.BLUE);swipe.setProgressBackgroundColorSchemeColor(LifeOsUi.SURFACE);swipe.addView(sc);swipe.setOnRefreshListener(this::manualRefresh);root.addView(swipe,new LinearLayout.LayoutParams(-1,0,1));root.addView(LifeOsUi.bottomNav(this,FeedActivity.class));setContentView(root);}
    private void manualRefresh(){refresh();try{BackgroundBrain.poke(this);}catch(Throwable ignored){}if(!BackgroundModelManager.isReadyFast(this))NotificationBrain.analyzeForeground(this,r->{if(!isFinishing())refresh();});ui.postDelayed(()->{if(swipe!=null)swipe.setRefreshing(false);refresh();},1000);}

    private void refresh(){if(content==null)return;content.removeAllViews();IntelligenceStatus.Snapshot is=IntelligenceStatus.snapshot(this);status.setText(is.ready+" ready  ·  "+is.pending+" processing"+(is.provisional>0?"  ·  "+is.provisional+" provisional":""));status.setTextColor(is.pending==0?LifeOsUi.GREEN:LifeOsUi.MUTED);List<LifeDb.Loop> raw=db.openLoops(60);List<AttentionStore.Item> durable=AttentionStore.get(this).openItems(50);List<LifeDb.Loop> fallback=legacyNotCovered(raw,durable);PersistentActionQueue queue=new PersistentActionQueue(this);List<PersistentActionQueue.Item> actions=queue.pending();List<SituationEngine.Situation> situations=SituationEngine.build(db,raw,actions,System.currentTimeMillis());int attention=durable.size()+fallback.size();TextView date=LifeOsUi.text(this,new SimpleDateFormat("EEE, d MMM yyyy",Locale.getDefault()).format(new Date()),11,LifeOsUi.MUTED);content.addView(date);TextView greet=LifeOsUi.text(this,greeting()+", Karim.",21,LifeOsUi.TEXT);greet.setTypeface(Typeface.DEFAULT,Typeface.BOLD);greet.setPadding(0,LifeOsUi.dp(this,1),0,0);content.addView(greet);TextView sub=LifeOsUi.text(this,"Here's what matters today.",12,LifeOsUi.MUTED);sub.setPadding(0,LifeOsUi.dp(this,2),0,LifeOsUi.dp(this,10));content.addView(sub);stats(attention,actions.size(),situations.size());sectionRow("Needs Attention",attention>3?"See all":"",()->openSection("attention"));if(attention==0)quiet("Nothing needs your attention right now.");else{int shown=0;for(AttentionStore.Item x:durable){if(shown++>=3)break;attentionCard(x);}for(LifeDb.Loop x:fallback){if(shown++>=3)break;loopCard(x);}}if(!actions.isEmpty()){sectionRow("Ready for your approval",actions.size()>2?"See all":"",()->openSection("actions"));for(int i=0;i<Math.min(2,actions.size());i++)approvalCard(queue,actions.get(i));}if(!situations.isEmpty()){sectionRow("Situations",situations.size()>3?"See all":"",()->openSection("situations"));for(int i=0;i<Math.min(3,situations.size());i++)situationCard(situations.get(i));}}
    private void stats(int a,int actions,int situations){LinearLayout row=new LinearLayout(this);row.setPadding(0,0,0,LifeOsUi.dp(this,4));stat(row,String.valueOf(a),"Need attention",a>0?LifeOsUi.RED:LifeOsUi.GREEN);stat(row,String.valueOf(actions),"Ready actions",LifeOsUi.BLUE);stat(row,String.valueOf(situations),"Upcoming",LifeOsUi.MUTED);content.addView(row);}
    private void stat(LinearLayout row,String value,String label,int color){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(LifeOsUi.dp(this,10),LifeOsUi.dp(this,8),LifeOsUi.dp(this,8),LifeOsUi.dp(this,7));c.setBackground(LifeOsUi.round(this,LifeOsUi.SURFACE,LifeOsUi.BORDER,9));TextView n=LifeOsUi.text(this,value,16,color);n.setTypeface(Typeface.DEFAULT,Typeface.BOLD);c.addView(n);c.addView(LifeOsUi.text(this,label,9,LifeOsUi.MUTED));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,59),1);p.setMargins(0,0,LifeOsUi.dp(this,6),0);row.addView(c,p);}
    private void sectionRow(String title,String action,Runnable click){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(LifeOsUi.dp(this,1),LifeOsUi.dp(this,12),0,LifeOsUi.dp(this,7));TextView t=LifeOsUi.text(this,title,16,LifeOsUi.TEXT);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);r.addView(t,new LinearLayout.LayoutParams(0,-2,1));if(action!=null&&!action.isEmpty()){TextView a=LifeOsUi.text(this,action,10,LifeOsUi.BLUE);r.addView(a);r.setOnClickListener(v->click.run());}content.addView(r);}

    private void attentionCard(AttentionStore.Item x){LifeDb.Event e=db.eventById(x.eventId);LinearLayout c=LifeOsUi.card(this);LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);View icon=e==null?LifeOsUi.categoryIcon(this,"!",LifeOsUi.RED,36):LifeOsUi.appIcon(this,e.app,36);row.addView(icon);LinearLayout txt=new LinearLayout(this);txt.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,-2,1);tp.setMargins(LifeOsUi.dp(this,10),0,0,0);row.addView(txt,tp);String title=e==null?UserFacingText.humanize(x.summary):PresentationSemantics.title(this,e);TextView t=LifeOsUi.text(this,title+"  ›",14,LifeOsUi.TEXT);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);txt.addView(t);String state=e==null?"":PresentationSemantics.status(this,e);if(state.isEmpty())state=x.provisional?"Analyzing":actionStatus(x.action,x.urgency);if(!state.isEmpty())txt.addView(LifeOsUi.text(this,state,10,x.provisional?LifeOsUi.AMBER:LifeOsUi.BLUE));String summary=e==null?UserFacingText.humanize(x.summary):PresentationSemantics.summary(this,e);if(summary.isEmpty())summary=UserFacingText.humanize(x.summary);TextView s=LifeOsUi.text(this,summary,11,LifeOsUi.MUTED);s.setPadding(0,LifeOsUi.dp(this,3),0,0);s.setMaxLines(2);txt.addView(s);c.addView(row);c.setOnClickListener(v->startActivity(new Intent(this,EvidenceDetailActivity.class).putExtra("event_id",x.eventId)));content.addView(c);}
    private void loopCard(LifeDb.Loop x){LifeDb.Event e=db.eventById(x.evidenceId);LinearLayout c=LifeOsUi.card(this);LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.addView(e==null?LifeOsUi.categoryIcon(this,"!",LifeOsUi.RED,36):LifeOsUi.appIcon(this,e.app,36));LinearLayout txt=new LinearLayout(this);txt.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,-2,1);tp.setMargins(LifeOsUi.dp(this,10),0,0,0);row.addView(txt,tp);TextView t=LifeOsUi.text(this,e==null?UserFacingText.humanize(x.title):PresentationSemantics.title(this,e)+"  ›",14,LifeOsUi.TEXT);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);txt.addView(t);String state=x.dueAt>0?due(x.dueAt):humanKind(x.kind);txt.addView(LifeOsUi.text(this,state,10,LifeOsUi.RED));String summary=e==null?UserFacingText.humanize(x.title):PresentationSemantics.summary(this,e);TextView s=LifeOsUi.text(this,summary,11,LifeOsUi.MUTED);s.setPadding(0,LifeOsUi.dp(this,3),0,0);s.setMaxLines(2);txt.addView(s);c.addView(row);c.setOnClickListener(v->startActivity(new Intent(this,EvidenceDetailActivity.class).putExtra("event_id",x.evidenceId).putExtra("loop_id",x.id)));content.addView(c);}
    private void approvalCard(PersistentActionQueue queue,PersistentActionQueue.Item x){LinearLayout c=LifeOsUi.card(this);LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);head.addView(LifeOsUi.categoryIcon(this,"✓",LifeOsUi.GREEN,36));LinearLayout txt=new LinearLayout(this);txt.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,-2,1);tp.setMargins(LifeOsUi.dp(this,10),0,0,0);head.addView(txt,tp);TextView t=LifeOsUi.text(this,UserFacingText.humanize(x.proposal.payloadSummary.isEmpty()?x.proposal.actionType:x.proposal.payloadSummary),14,LifeOsUi.TEXT);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);txt.addView(t);if(!x.proposal.target.isEmpty())txt.addView(LifeOsUi.text(this,x.proposal.target,10,LifeOsUi.MUTED));c.addView(head);LinearLayout a=new LinearLayout(this);a.setPadding(0,LifeOsUi.dp(this,8),0,0);Button edit=LifeOsUi.button(this,"Cancel");edit.setOnClickListener(v->{queue.decide(x.proposal.proposalId,false);refresh();});Button approve=LifeOsUi.primary(this,"Approve");approve.setOnClickListener(v->{queue.decide(x.proposal.proposalId,true);TeyaApprovalReceiver.executeApproved(this,x);refresh();});a.addView(edit,new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,38),1));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,38),1);p.setMargins(LifeOsUi.dp(this,7),0,0,0);a.addView(approve,p);c.addView(a);content.addView(c);}
    private void situationCard(SituationEngine.Situation x){LinearLayout c=LifeOsUi.card(this);TextView t=LifeOsUi.text(this,x.title+"  ›",14,LifeOsUi.TEXT);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);c.addView(t);TextView s=LifeOsUi.text(this,UserFacingText.humanize(x.summary),11,LifeOsUi.MUTED);s.setPadding(0,LifeOsUi.dp(this,3),0,0);s.setMaxLines(2);c.addView(s);c.setOnClickListener(v->startActivity(new Intent(this,SituationDetailActivity.class).putExtra("situation_id",x.id)));content.addView(c);}
    private void quiet(String x){TextView t=LifeOsUi.text(this,x,11,LifeOsUi.MUTED);t.setPadding(LifeOsUi.dp(this,2),LifeOsUi.dp(this,3),0,LifeOsUi.dp(this,6));content.addView(t);}
    private void openSection(String mode){startActivity(new Intent(this,FeedSectionActivity.class).putExtra("mode",mode));}
    private List<LifeDb.Loop> legacyNotCovered(List<LifeDb.Loop> loops,List<AttentionStore.Item> items){Set<Long> ids=new HashSet<>();for(AttentionStore.Item x:items)ids.add(x.eventId);ArrayList<LifeDb.Loop> out=new ArrayList<>();for(LifeDb.Loop x:loops)if(!ids.contains(x.evidenceId))out.add(x);return out;}
    private static String greeting(){int h=java.util.Calendar.getInstance().get(java.util.Calendar.HOUR_OF_DAY);return h<12?"Good morning":h<18?"Good afternoon":"Good evening";}
    private String due(long at){return "Due · "+new SimpleDateFormat("d MMM",Locale.getDefault()).format(new Date(at));}
    private static String humanKind(String x){String v=x==null?"":x.replace('_',' ').trim();return v.isEmpty()?"Needs attention":Character.toUpperCase(v.charAt(0))+v.substring(1);}
    private static String actionStatus(String action,String urgency){String a=action==null?"":action;if("PAY".equals(a))return "Payment due";if("REPLY".equals(a))return "Reply needed";if("CALL_BACK".equals(a))return "Call back";if("DO_TASK".equals(a))return "Action needed";return "HIGH".equals(urgency)?"Important":"";}
}
