package com.kareem.lifeos;

import android.app.Activity;
import android.content.Intent;
import android.graphics.Typeface;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.Gravity;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.swiperefreshlayout.widget.SwipeRefreshLayout;
import com.kareem.lifeos.actions.PersistentActionQueue;
import com.kareem.lifeos.actions.TeyaApprovalReceiver;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;

/** Approved LifeOS reference UI: calm triage, contextual approvals, no donor plumbing. */
public final class FeedActivity extends Activity {
    private LifeDb db;private LinearLayout content;private SwipeRefreshLayout swipe;private TextView status;private final Handler ui=new Handler(Looper.getMainLooper());
    @Override public void onCreate(Bundle s){super.onCreate(s);db=new LifeDb(this);render();}
    @Override protected void onResume(){super.onResume();refresh();}
    @Override protected void onDestroy(){db.close();super.onDestroy();}
    private void render(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(LifeOsUi.BG);LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.setPadding(LifeOsUi.dp(this,16),LifeOsUi.dp(this,10),LifeOsUi.dp(this,10),0);TextView brand=LifeOsUi.text(this,"◯  LifeOS",22,LifeOsUi.TEXT);brand.setTypeface(Typeface.DEFAULT,Typeface.BOLD);top.addView(brand,new LinearLayout.LayoutParams(0,-2,1));Button settings=LifeOsUi.button(this,"K");settings.setTextSize(13);settings.setContentDescription("Settings and diagnostics");settings.setOnClickListener(v->startActivity(new Intent(this,MainActivity.class)));top.addView(settings,new LinearLayout.LayoutParams(LifeOsUi.dp(this,44),LifeOsUi.dp(this,44)));root.addView(top);status=LifeOsUi.text(this,"",11,LifeOsUi.MUTED);status.setPadding(LifeOsUi.dp(this,18),0,LifeOsUi.dp(this,18),LifeOsUi.dp(this,7));root.addView(status);ScrollView sc=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(LifeOsUi.dp(this,16),0,LifeOsUi.dp(this,16),LifeOsUi.dp(this,20));sc.addView(content);swipe=new SwipeRefreshLayout(this);swipe.setColorSchemeColors(LifeOsUi.BLUE);swipe.setProgressBackgroundColorSchemeColor(LifeOsUi.SURFACE);swipe.addView(sc);swipe.setOnRefreshListener(this::manualRefresh);root.addView(swipe,new LinearLayout.LayoutParams(-1,0,1));root.addView(LifeOsUi.bottomNav(this,FeedActivity.class));setContentView(root);}
    private void manualRefresh(){refresh();try{BackgroundBrain.poke(this);}catch(Throwable ignored){}if(!BackgroundModelManager.isReadyFast(this))NotificationBrain.analyzeForeground(this,r->{if(!isFinishing())refresh();});ui.postDelayed(()->{if(swipe!=null)swipe.setRefreshing(false);refresh();},1100);}
    private void refresh(){if(content==null)return;content.removeAllViews();IntelligenceStatus.Snapshot is=IntelligenceStatus.snapshot(this);status.setText(is.ready+" ready  ·  "+is.pending+" processing"+(is.provisional>0?"  ·  "+is.provisional+" provisional":""));status.setTextColor(is.pending==0?LifeOsUi.GREEN:LifeOsUi.MUTED);List<LifeDb.Loop> raw=db.openLoops(60);List<AttentionStore.Item> durable=AttentionStore.get(this).openItems(50);List<LifeDb.Loop> fallback=legacyNotCovered(raw,durable);PersistentActionQueue queue=new PersistentActionQueue(this);List<PersistentActionQueue.Item> actions=queue.pending();List<SituationEngine.Situation> situations=SituationEngine.build(db,raw,actions,System.currentTimeMillis());int attention=durable.size()+fallback.size();TextView date=LifeOsUi.text(this,new SimpleDateFormat("EEE, d MMM yyyy",Locale.getDefault()).format(new Date()),12,LifeOsUi.MUTED);content.addView(date);TextView greet=LifeOsUi.text(this,greeting()+", Karim.",22,LifeOsUi.TEXT);greet.setTypeface(Typeface.DEFAULT,Typeface.BOLD);greet.setPadding(0,LifeOsUi.dp(this,2),0,0);content.addView(greet);TextView sub=LifeOsUi.text(this,"Here's what matters today.",13,LifeOsUi.MUTED);sub.setPadding(0,LifeOsUi.dp(this,3),0,LifeOsUi.dp(this,12));content.addView(sub);stats(attention,actions.size(),situations.size());content.addView(LifeOsUi.section(this,"Needs Attention"));if(attention==0)empty("Nothing needs your attention right now.");else{int shown=0;for(AttentionStore.Item x:durable){if(shown++>=3)break;attentionCard(x);}for(LifeDb.Loop x:fallback){if(shown++>=3)break;loopCard(x);}}content.addView(LifeOsUi.section(this,"Ready for your approval"));if(actions.isEmpty())empty("No external action is waiting for approval.");else for(int i=0;i<Math.min(2,actions.size());i++)approvalCard(queue,actions.get(i));content.addView(LifeOsUi.section(this,"Situations"));if(situations.isEmpty())empty("No unresolved situation needs you right now.");else for(int i=0;i<Math.min(3,situations.size());i++)situationCard(situations.get(i));}
    private void stats(int a,int actions,int situations){LinearLayout row=new LinearLayout(this);row.setPadding(0,0,0,LifeOsUi.dp(this,5));stat(row,String.valueOf(a),"Need attention",a>0?LifeOsUi.RED:LifeOsUi.GREEN);stat(row,String.valueOf(actions),"Ready actions",LifeOsUi.BLUE);stat(row,String.valueOf(situations),"Upcoming",LifeOsUi.MUTED);content.addView(row);}
    private void stat(LinearLayout row,String value,String label,int color){LinearLayout c=LifeOsUi.card(this);TextView n=LifeOsUi.text(this,value,18,color);n.setTypeface(Typeface.DEFAULT,Typeface.BOLD);c.addView(n);c.addView(LifeOsUi.text(this,label,10,LifeOsUi.MUTED));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,70),1);p.setMargins(0,0,LifeOsUi.dp(this,6),0);row.addView(c,p);}
    private void attentionCard(AttentionStore.Item x){LifeDb.Event e=db.eventById(x.eventId);LinearLayout c=LifeOsUi.card(this);String signal=x.provisional?"Analyzing":(!"NONE".equals(x.intent)?x.intent:x.type);c.addView(LifeOsUi.badge(this,signal,x.provisional?LifeOsUi.AMBER:LifeOsUi.RED));String who=e==null?"":LifeDb.personLabel(e);TextView t=LifeOsUi.text(this,UserFacingText.humanize(who.isEmpty()?x.summary:who),15,LifeOsUi.TEXT);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);t.setPadding(0,LifeOsUi.dp(this,7),0,0);c.addView(t);TextView s=LifeOsUi.text(this,UserFacingText.humanize(x.summary),12,LifeOsUi.MUTED);s.setPadding(0,LifeOsUi.dp(this,4),0,0);s.setMaxLines(2);c.addView(s);if(!x.reason.isEmpty())c.addView(LifeOsUi.text(this,UserFacingText.humanize(x.reason),11,LifeOsUi.BLUE));c.setOnClickListener(v->startActivity(new Intent(this,EvidenceDetailActivity.class).putExtra("event_id",x.eventId)));content.addView(c);}
    private void loopCard(LifeDb.Loop x){LifeDb.Event e=db.eventById(x.evidenceId);LinearLayout c=LifeOsUi.card(this);c.addView(LifeOsUi.badge(this,x.kind,LifeOsUi.RED));TextView t=LifeOsUi.text(this,e==null?UserFacingText.humanize(x.title):LifeDb.personLabel(e),15,LifeOsUi.TEXT);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);t.setPadding(0,LifeOsUi.dp(this,7),0,0);c.addView(t);c.addView(LifeOsUi.text(this,UserFacingText.humanize(x.title),12,LifeOsUi.MUTED));c.setOnClickListener(v->startActivity(new Intent(this,EvidenceDetailActivity.class).putExtra("event_id",x.evidenceId).putExtra("loop_id",x.id)));content.addView(c);}
    private void approvalCard(PersistentActionQueue queue,PersistentActionQueue.Item x){LinearLayout c=LifeOsUi.card(this);c.addView(LifeOsUi.badge(this,"Approval",LifeOsUi.BLUE));TextView t=LifeOsUi.text(this,UserFacingText.humanize(x.proposal.payloadSummary.isEmpty()?x.proposal.actionType:x.proposal.payloadSummary),15,LifeOsUi.TEXT);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);t.setPadding(0,LifeOsUi.dp(this,7),0,0);c.addView(t);if(!x.proposal.target.isEmpty())c.addView(LifeOsUi.text(this,x.proposal.target,11,LifeOsUi.MUTED));LinearLayout a=new LinearLayout(this);a.setPadding(0,LifeOsUi.dp(this,10),0,0);Button cancel=LifeOsUi.button(this,"Cancel");cancel.setOnClickListener(v->{queue.decide(x.proposal.proposalId,false);refresh();});Button approve=LifeOsUi.primary(this,"Approve");approve.setOnClickListener(v->{queue.decide(x.proposal.proposalId,true);TeyaApprovalReceiver.executeApproved(this,x);refresh();});a.addView(cancel,new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,44),1));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,44),1);p.setMargins(LifeOsUi.dp(this,8),0,0,0);a.addView(approve,p);c.addView(a);content.addView(c);}
    private void situationCard(SituationEngine.Situation x){LinearLayout c=LifeOsUi.card(this);c.addView(LifeOsUi.badge(this,x.status,LifeOsUi.BLUE));TextView t=LifeOsUi.text(this,x.title+"  ›",15,LifeOsUi.TEXT);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);t.setPadding(0,LifeOsUi.dp(this,7),0,0);c.addView(t);TextView s=LifeOsUi.text(this,UserFacingText.humanize(x.summary),12,LifeOsUi.MUTED);s.setMaxLines(2);c.addView(s);c.setOnClickListener(v->startActivity(new Intent(this,SituationDetailActivity.class).putExtra("situation_id",x.id)));content.addView(c);}
    private void empty(String x){LinearLayout c=LifeOsUi.card(this);c.addView(LifeOsUi.text(this,x,13,LifeOsUi.MUTED));content.addView(c);}
    private List<LifeDb.Loop> legacyNotCovered(List<LifeDb.Loop> loops,List<AttentionStore.Item> items){Set<Long> ids=new HashSet<>();for(AttentionStore.Item x:items)ids.add(x.eventId);ArrayList<LifeDb.Loop> out=new ArrayList<>();for(LifeDb.Loop x:loops)if(!ids.contains(x.evidenceId))out.add(x);return out;}
    private static String greeting(){int h=java.util.Calendar.getInstance().get(java.util.Calendar.HOUR_OF_DAY);return h<12?"Good morning":h<18?"Good afternoon":"Good evening";}
}
