package com.kareem.lifeos;

import android.app.Activity;
import android.content.ContentUris;
import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.provider.CalendarContract;
import android.view.Gravity;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

/** Detail screen that always reloads a real typed object by capability + stable object ID. */
public final class FunctionalObjectDetailActivity extends Activity {
    private String capabilityId,objectId;
    @Override public void onCreate(Bundle state){super.onCreate(state);capabilityId=s(getIntent().getStringExtra("capability_id"));objectId=s(getIntent().getStringExtra("object_id"));render();}

    private void render(){FunctionalCapabilityRegistry.ObjectItem item=FunctionalCapabilityRegistry.load(this,capabilityId,objectId);String title=item==null?"LifeOS item":item.title;LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(LifeOsUi.BG);root.addView(LifeOsUi.detailTopBar(this,title));ScrollView sc=new ScrollView(this);sc.setVerticalScrollBarEnabled(false);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(LifeOsUi.dp(this,16),LifeOsUi.dp(this,7),LifeOsUi.dp(this,16),LifeOsUi.dp(this,24));sc.addView(body);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));if(item==null){TextView none=LifeOsUi.text(this,"This object is no longer available from its backing source.",11.5f,LifeOsUi.MUTED);LifeOsUi.weight(none,500);body.addView(none);setContentView(root);return;}
        TextView eyebrow=LifeOsUi.text(this,capabilityId.toUpperCase(Locale.ROOT),9.5f,accent());LifeOsUi.weight(eyebrow,700);body.addView(eyebrow);TextView h=LifeOsUi.text(this,item.title,19.5f,LifeOsUi.TEXT);LifeOsUi.weight(h,700);h.setPadding(0,LifeOsUi.dp(this,5),0,0);body.addView(h);if(!item.meta.isEmpty()){TextView meta=LifeOsUi.text(this,item.meta,10f,LifeOsUi.MUTED);LifeOsUi.weight(meta,500);meta.setPadding(0,LifeOsUi.dp(this,3),0,0);body.addView(meta);}
        body.addView(LifeOsUi.section(this,"Summary"));LinearLayout summary=LifeOsUi.card(this);TextView sv=LifeOsUi.text(this,item.summary.isEmpty()?"No additional details are available from the backing source.":item.summary,11.5f,LifeOsUi.TEXT);LifeOsUi.weight(sv,500);summary.addView(sv);body.addView(summary);
        if("people".equals(capabilityId))renderPerson(body);else if("events".equals(capabilityId))renderEvent(body);else if("decisions".equals(capabilityId))renderDecision(body,item);else if("commitments".equals(capabilityId))renderObligation(body,item);else renderConversation(body,item);
        setContentView(root);
    }

    private void renderPerson(LinearLayout body){ContactPersonRepository.PersonObject p=ContactPersonRepository.load(this,objectId);if(p==null)return;body.addView(LifeOsUi.section(this,"Source"));sourceCard(body,"Android Contacts","Stable contact: "+p.lookupKey);if(!p.phones.isEmpty()||!p.emails.isEmpty()){body.addView(LifeOsUi.section(this,"Contact details"));LinearLayout c=LifeOsUi.card(this);for(String phone:p.phones){TextView t=LifeOsUi.text(this,phone,11.2f,LifeOsUi.TEXT);LifeOsUi.weight(t,500);c.addView(t);}for(String email:p.emails){TextView t=LifeOsUi.text(this,email,11.2f,LifeOsUi.TEXT);LifeOsUi.weight(t,500);t.setPadding(0,LifeOsUi.dp(this,4),0,0);c.addView(t);}body.addView(c);}body.addView(LifeOsUi.section(this,"Actions"));LinearLayout row=new LinearLayout(this);if(!p.phones.isEmpty()){Button dial=LifeOsUi.button(this,"Call");dial.setOnClickListener(v->startActivity(new Intent(Intent.ACTION_DIAL,Uri.parse("tel:"+Uri.encode(p.phones.get(0))))));row.addView(dial,new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,44),1));Button sms=LifeOsUi.primary(this,"Message");sms.setOnClickListener(v->startActivity(new Intent(Intent.ACTION_SENDTO,Uri.parse("smsto:"+Uri.encode(p.phones.get(0))))));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,44),1);sp.setMargins(LifeOsUi.dp(this,8),0,0,0);row.addView(sms,sp);}else{Button search=LifeOsUi.button(this,"Search LifeOS");search.setOnClickListener(v->startActivity(new Intent(this,SearchActivity.class).putExtra("initial_query",p.name)));row.addView(search,new LinearLayout.LayoutParams(-1,LifeOsUi.dp(this,44)));}body.addView(row);}

    private void renderEvent(LinearLayout body){CalendarEventRepository.CalendarEventObject e=CalendarEventRepository.load(this,objectId);if(e==null)return;body.addView(LifeOsUi.section(this,"When"));LinearLayout when=LifeOsUi.card(this);String format=e.allDay?"EEE, d MMM yyyy":"EEE, d MMM yyyy · HH:mm";TextView w=LifeOsUi.text(this,new SimpleDateFormat(format,Locale.getDefault()).format(new Date(e.begin))+(e.end>e.begin&&!e.allDay?" – "+new SimpleDateFormat("HH:mm",Locale.getDefault()).format(new Date(e.end)):""),11.5f,LifeOsUi.TEXT);LifeOsUi.weight(w,600);when.addView(w);if(!e.location.isEmpty()){TextView loc=LifeOsUi.text(this,e.location,10.5f,LifeOsUi.MUTED);LifeOsUi.weight(loc,500);loc.setPadding(0,LifeOsUi.dp(this,4),0,0);when.addView(loc);}body.addView(when);body.addView(LifeOsUi.section(this,"Source"));sourceCard(body,"Android Calendar",e.calendarName.isEmpty()?"Calendar provider":e.calendarName);body.addView(LifeOsUi.section(this,"Actions"));Button open=LifeOsUi.primary(this,"Open in Calendar");open.setOnClickListener(v->{try{Uri uri=ContentUris.withAppendedId(CalendarContract.Events.CONTENT_URI,e.eventId);startActivity(new Intent(Intent.ACTION_VIEW,uri));}catch(Exception ex){Toast.makeText(this,"No calendar app can open this event.",Toast.LENGTH_LONG).show();}});body.addView(open,new LinearLayout.LayoutParams(-1,LifeOsUi.dp(this,44)));}

    private void renderDecision(LinearLayout body,FunctionalCapabilityRegistry.ObjectItem item){DecisionRepository.DecisionObject d=DecisionRepository.load(this,objectId);if(d==null)return;if(!d.context.isEmpty()){body.addView(LifeOsUi.section(this,"Context"));textCard(body,d.context);}if(!d.options.isEmpty()){body.addView(LifeOsUi.section(this,"Options considered"));textCard(body,d.options);}if(!d.choice.isEmpty()){body.addView(LifeOsUi.section(this,"Choice"));textCard(body,d.choice);}if(!d.consequences.isEmpty()){body.addView(LifeOsUi.section(this,"Expected consequences"));textCard(body,d.consequences);}body.addView(LifeOsUi.section(this,"Source"));sourceCard(body,"LifeOS Decision Memory","Explicitly recorded by you · "+new SimpleDateFormat("d MMM yyyy · HH:mm",Locale.getDefault()).format(new Date(d.createdAt))+" · status "+(d.status.isEmpty()?"active":d.status));body.addView(LifeOsUi.section(this,"Actions"));LinearLayout actions=new LinearLayout(this);Button memory=LifeOsUi.button(this,"Open Decision Memory");memory.setOnClickListener(v->startActivity(new Intent(this,LifeSignalsActivity.class)));actions.addView(memory,new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,44),1));Button ask=LifeOsUi.primary(this,"Ask about this");ask.setOnClickListener(v->startActivity(new Intent(this,AskLifeOsActivity.class).putExtra("initial_question","What did I decide about "+item.title+" and what does that decision mean now?")));LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,44),1);ap.setMargins(LifeOsUi.dp(this,8),0,0,0);actions.addView(ask,ap);body.addView(actions);}

    private void renderObligation(LinearLayout body,FunctionalCapabilityRegistry.ObjectItem item){ObligationRepository.ObligationObject o=ObligationRepository.load(this,objectId);if(o==null)return;body.addView(LifeOsUi.section(this,"Why this is open"));LinearLayout why=LifeOsUi.card(this);TextView r=LifeOsUi.text(this,o.reason.isEmpty()?"A grounded semantic analysis says a future response or action is still required.":o.reason,10.8f,LifeOsUi.TEXT);LifeOsUi.weight(r,500);why.addView(r);body.addView(why);body.addView(LifeOsUi.section(this,"Evidence"));try(LifeDb db=new LifeDb(this)){for(Long id:o.evidenceEventIds){LifeDb.Event e=id==null?null:db.eventById(id);if(e==null)continue;LinearLayout ev=LifeOsUi.card(this);TextView t=LifeOsUi.text(this,PresentationSemantics.title(this,e),11.4f,LifeOsUi.TEXT);LifeOsUi.weight(t,600);ev.addView(t);TextView s=LifeOsUi.text(this,PresentationSemantics.summary(this,e),10f,LifeOsUi.MUTED);LifeOsUi.weight(s,500);s.setPadding(0,LifeOsUi.dp(this,3),0,0);ev.addView(s);ev.setOnClickListener(v->startActivity(new Intent(this,EvidenceDetailActivity.class).putExtra("event_id",e.id).putExtra("mode","obligation")));body.addView(ev);}}
        body.addView(LifeOsUi.section(this,"Actions"));LinearLayout actions=new LinearLayout(this);Button handled=LifeOsUi.button(this,"Mark handled");handled.setOnClickListener(v->{ObligationRepository.markHandled(this,objectId);finish();});actions.addView(handled,new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,44),1));Button ask=LifeOsUi.primary(this,"Ask about this");ask.setOnClickListener(v->startActivity(new Intent(this,AskLifeOsActivity.class).putExtra("initial_question","What should I do about "+item.title+"?")));LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,44),1);ap.setMargins(LifeOsUi.dp(this,8),0,0,0);actions.addView(ask,ap);body.addView(actions);}

    private void renderConversation(LinearLayout body,FunctionalCapabilityRegistry.ObjectItem item){body.addView(LifeOsUi.section(this,"Source"));sourceCard(body,"LifeOS conversation store",item.meta);body.addView(LifeOsUi.section(this,"Actions"));Button open=LifeOsUi.primary(this,"Open conversation detail");open.setOnClickListener(v->startActivity(new Intent(this,ConversationDetailActivity.class).putExtra("conversation_id",objectId)));body.addView(open,new LinearLayout.LayoutParams(-1,LifeOsUi.dp(this,44)));}
    private void textCard(LinearLayout body,String value){LinearLayout c=LifeOsUi.card(this);TextView t=LifeOsUi.text(this,value,11.2f,LifeOsUi.TEXT);LifeOsUi.weight(t,500);c.addView(t);body.addView(c);}
    private void sourceCard(LinearLayout body,String title,String sub){LinearLayout c=LifeOsUi.card(this);TextView t=LifeOsUi.text(this,title,11.5f,LifeOsUi.TEXT);LifeOsUi.weight(t,600);c.addView(t);if(sub!=null&&!sub.trim().isEmpty()){TextView s=LifeOsUi.text(this,sub,9.8f,LifeOsUi.MUTED);LifeOsUi.weight(s,500);s.setPadding(0,LifeOsUi.dp(this,3),0,0);c.addView(s);}body.addView(c);}
    private int accent(){if("people".equals(capabilityId))return LifeOsUi.PURPLE;if("events".equals(capabilityId))return LifeOsUi.PURPLE;if("decisions".equals(capabilityId))return LifeOsUi.PINK;if("commitments".equals(capabilityId))return LifeOsUi.GREEN;return LifeOsUi.BLUE;}
    private static String s(String x){return x==null?"":x.trim();}
}
