package com.kareem.lifeos;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.ClipData;
import android.content.ClipboardManager;
import android.content.Intent;
import android.graphics.Color;
import android.net.Uri;
import android.os.Bundle;
import android.view.Gravity;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;
import java.util.Locale;

/** OCR inspection + ground-truth correction screen used to validate the pipeline before promotion. */
public final class ImageOcrDetailActivity extends Activity {
    private String imageId;private LinearLayout body;
    @Override public void onCreate(Bundle s){super.onCreate(s);imageId=getIntent().getStringExtra("image_id");render();}
    @Override protected void onResume(){super.onResume();refresh();}
    private void render(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(LifeOsUi.BG);root.addView(LifeOsUi.detailTopBar(this,"OCR image"));ScrollView sc=new ScrollView(this);sc.setVerticalScrollBarEnabled(false);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(LifeOsUi.dp(this,16),LifeOsUi.dp(this,7),LifeOsUi.dp(this,16),LifeOsUi.dp(this,24));sc.addView(body);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
    private void refresh(){body.removeAllViews();ImageRepository.ImageObject image=ImageRepository.load(this,imageId);if(image==null){TextView t=LifeOsUi.text(this,"Image is no longer available.",11.5f,LifeOsUi.MUTED);body.addView(t);return;}ImageView preview=new ImageView(this);preview.setScaleType(ImageView.ScaleType.CENTER_CROP);preview.setAdjustViewBounds(true);preview.setImageURI(Uri.parse(image.uri));LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(-1,LifeOsUi.dp(this,190));ip.bottomMargin=LifeOsUi.dp(this,10);body.addView(preview,ip);TextView h=LifeOsUi.text(this,image.displayName,18f,LifeOsUi.TEXT);LifeOsUi.weight(h,700);body.addView(h);TextView meta=LifeOsUi.text(this,image.width+"×"+image.height+" · "+image.source,9.8f,LifeOsUi.MUTED);LifeOsUi.weight(meta,500);meta.setPadding(0,LifeOsUi.dp(this,3),0,0);body.addView(meta);OcrResult r=image.latest(this);body.addView(LifeOsUi.section(this,"OCR status"));LinearLayout status=LifeOsUi.card(this);TextView st=LifeOsUi.text(this,r==null?human(image.ocrStatus):r.status+" · "+Math.round(r.confidence*100)+"% confidence",11.5f,r!=null&&r.success()?LifeOsUi.GREEN:"processing".equals(image.ocrStatus)?LifeOsUi.AMBER:LifeOsUi.RED);LifeOsUi.weight(st,700);status.addView(st);if(r!=null){TextView sm=LifeOsUi.text(this,r.engineSummary+" · "+r.languages+" · "+r.durationMs+" ms",9.6f,LifeOsUi.MUTED);LifeOsUi.weight(sm,500);sm.setPadding(0,LifeOsUi.dp(this,4),0,0);status.addView(sm);}body.addView(status);
        if(r!=null&&r.success()){body.addView(LifeOsUi.section(this,"Extracted text"));LinearLayout textCard=LifeOsUi.card(this);TextView txt=LifeOsUi.text(this,r.rawText,11f,LifeOsUi.TEXT);LifeOsUi.weight(txt,500);txt.setTextIsSelectable(true);textCard.addView(txt);body.addView(textCard);if(!r.criticalTokens.isEmpty()){body.addView(LifeOsUi.section(this,"Critical tokens"));LinearLayout ct=LifeOsUi.card(this);TextView x=LifeOsUi.text(this,android.text.TextUtils.join("\n",r.criticalTokens),10.5f,LifeOsUi.TEXT);LifeOsUi.weight(x,500);ct.addView(x);body.addView(ct);}String truth=ImageOcrStore.get(this).groundTruth(imageId);body.addView(LifeOsUi.section(this,"Benchmark truth"));LinearLayout truthCard=LifeOsUi.card(this);TextView tv=LifeOsUi.text(this,truth.isEmpty()?"Not scored yet. Add the exact ground-truth text to measure CER/WER.":"Ground truth saved · CER "+pct(OcrBenchmark.cer(truth,r.rawText))+" · WER "+pct(OcrBenchmark.wer(truth,r.rawText)),10.3f,truth.isEmpty()?LifeOsUi.MUTED:LifeOsUi.BLUE);LifeOsUi.weight(tv,500);truthCard.addView(tv);body.addView(truthCard);}
        body.addView(LifeOsUi.section(this,"Actions"));LinearLayout row=new LinearLayout(this);Button rescan=LifeOsUi.button(this,r==null?"Run OCR":"Re-scan");rescan.setOnClickListener(v->reanalyze(image));row.addView(rescan,new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,44),1));Button open=LifeOsUi.primary(this,"Open image");open.setOnClickListener(v->open(image));LinearLayout.LayoutParams op=new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,44),1);op.setMargins(LifeOsUi.dp(this,8),0,0,0);row.addView(open,op);body.addView(row);if(r!=null&&r.success()){LinearLayout row2=new LinearLayout(this);row2.setPadding(0,LifeOsUi.dp(this,8),0,0);Button copy=LifeOsUi.button(this,"Copy text");copy.setOnClickListener(v->copy(r.rawText));row2.addView(copy,new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,44),1));Button truth=LifeOsUi.button(this,"Set ground truth");truth.setOnClickListener(v->groundTruth(r));LinearLayout.LayoutParams gp=new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,44),1);gp.setMargins(LifeOsUi.dp(this,8),0,0,0);row2.addView(truth,gp);body.addView(row2);body.addView(LifeOsUi.section(this,"Engine candidates"));LinearLayout raw=LifeOsUi.card(this);TextView rv=LifeOsUi.text(this,android.text.TextUtils.join("\n\n",r.candidateSummaries),9f,LifeOsUi.MUTED);LifeOsUi.weight(rv,500);rv.setTextIsSelectable(true);raw.addView(rv);body.addView(raw);}}
    private void reanalyze(ImageRepository.ImageObject image){ImageOcrStore.get(this).setImageStatus(image.id,"processing");refresh();ImageRepository.analyze(this,image.id,new ImageOcrEngine.Callback(){public void ok(OcrResult result){refresh();}public void fail(Exception error){refresh();Toast.makeText(ImageOcrDetailActivity.this,"OCR failed: "+error.getMessage(),Toast.LENGTH_LONG).show();}});}
    private void open(ImageRepository.ImageObject image){try{Intent i=new Intent(Intent.ACTION_VIEW,Uri.parse(image.uri));i.setDataAndType(Uri.parse(image.uri),image.mimeType.isEmpty()?"image/*":image.mimeType);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(i);}catch(Exception e){Toast.makeText(this,"No app can open this image.",Toast.LENGTH_LONG).show();}}
    private void copy(String text){ClipboardManager cm=(ClipboardManager)getSystemService(CLIPBOARD_SERVICE);cm.setPrimaryClip(ClipData.newPlainText("LifeOS OCR",text));Toast.makeText(this,"OCR text copied",Toast.LENGTH_SHORT).show();}
    private void groundTruth(OcrResult r){EditText e=new EditText(this);e.setText(ImageOcrStore.get(this).groundTruth(imageId).isEmpty()?r.rawText:ImageOcrStore.get(this).groundTruth(imageId));e.setMinLines(8);e.setGravity(Gravity.TOP);e.setTextColor(Color.BLACK);new AlertDialog.Builder(this).setTitle("Ground-truth transcript").setMessage("Correct this to the exact visible text. This does not overwrite raw OCR; it becomes a benchmark sample.").setView(e).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{String corrected=e.getText().toString();ImageOcrStore.get(this).recordCorrection(imageId,r.runId,r.rawText,corrected);ImageOcrStore.get(this).setGroundTruth(imageId,corrected);refresh();}).show();}
    private static String human(String x){String v=x==null?"not run":x.replace('_',' ');return v.isEmpty()?"not run":v;}private static String pct(double v){return String.format(Locale.US,"%.1f%%",v*100);}
}
