package com.kareem.lifeos;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.Intent;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.text.InputType;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;
import com.kareem.lifeos.graphiti.GraphitiGateway;
import java.util.List;

/** Local-first people/decision intelligence; Graphiti is an optional Advanced enhancement. */
public final class LifeSignalsActivity extends Activity {
    private static final int BG=Color.rgb(13,17,23),SURFACE=Color.rgb(22,27,34),BORDER=Color.rgb(48,54,61),TEXT=Color.rgb(230,237,243),MUTED=Color.rgb(139,148,158),GREEN=Color.rgb(63,185,80),BLUE=Color.rgb(47,129,247);
    private GraphitiGateway api; private LifeDb db; private LinearLayout content; private TextView connection; private Button social,decisions;private volatile boolean remoteAvailable;private boolean advanced;
    @Override public void onCreate(Bundle state){super.onCreate(state);advanced=getIntent().getBooleanExtra("advanced",false);api=new GraphitiGateway(this);db=new LifeDb(this);render();checkHealth();}
    @Override protected void onDestroy(){db.close();super.onDestroy();}
    private void render(){
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);
        LinearLayout header=new LinearLayout(this);header.setOrientation(LinearLayout.VERTICAL);header.setPadding(dp(16),dp(16),dp(16),dp(12));header.setBackgroundColor(SURFACE);
        LinearLayout titleRow=new LinearLayout(this);titleRow.setGravity(Gravity.CENTER_VERTICAL);Button back=secondary("‹");back.setContentDescription("Back");back.setOnClickListener(v->finish());titleRow.addView(back,new LinearLayout.LayoutParams(dp(48),dp(48)));TextView title=text("People & Decisions",21,TEXT);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,-2,1);tp.setMargins(dp(10),0,0,0);titleRow.addView(title,tp);if(advanced){Button server=secondary("Server");server.setOnClickListener(v->configure());titleRow.addView(server,new LinearLayout.LayoutParams(dp(84),dp(48)));}header.addView(titleRow);
        connection=text("Local intelligence active",12,GREEN);connection.setPadding(0,dp(8),0,0);header.addView(connection);
        Button addDecision=primary("Record decision");addDecision.setOnClickListener(v->recordDecision());LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,dp(48));ap.setMargins(0,dp(10),0,0);header.addView(addDecision,ap);
        root.addView(header);root.addView(divider());
        LinearLayout tabs=new LinearLayout(this);tabs.setPadding(dp(8),0,dp(8),0);social=tab("Social Radar");decisions=tab("Decision Memory");tabs.addView(social,new LinearLayout.LayoutParams(0,dp(48),1));tabs.addView(decisions,new LinearLayout.LayoutParams(0,dp(48),1));root.addView(tabs);root.addView(divider());
        ScrollView scroll=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(16),dp(14),dp(16),dp(24));scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        social.setOnClickListener(v->loadSocial());decisions.setOnClickListener(v->loadDecisions());setContentView(root);loadSocial();
    }
    private void configure(){EditText input=new EditText(this);input.setText(api.baseUrl());input.setTextColor(TEXT);input.setHintTextColor(MUTED);input.setSingleLine(true);input.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_URI);new AlertDialog.Builder(this).setTitle("Graphiti server").setMessage("Pinned upstream Graphiti FastAPI service.").setView(input).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{api.setBaseUrl(input.getText().toString());checkHealth();}).show();}
    private void checkHealth(){new Thread(()->{try{remoteAvailable=api.health();}catch(Exception ignored){remoteAvailable=false;}runOnUiThread(()->{connection.setText(advanced?(remoteAvailable?"Enhanced history connected · "+api.baseUrl():"Local mode · enhanced history offline"):remoteAvailable?"Local intelligence · enhanced history connected":"Local intelligence active");connection.setTextColor(GREEN);});},"graphiti-health").start();}
    private void syncInteractions(){Toast.makeText(this,"Syncing recent LifeOS interactions…",Toast.LENGTH_SHORT).show();new Thread(()->{try{int n=LifeSignalsSync.syncRecentInteractions(this,80);runOnUiThread(()->{Toast.makeText(this,"Queued "+n+" interaction episodes",Toast.LENGTH_SHORT).show();loadSocial();});}catch(Exception e){runOnUiThread(()->error(e));}},"life-signals-sync").start();}
    private void recordDecision(){LinearLayout form=new LinearLayout(this);form.setOrientation(LinearLayout.VERTICAL);form.setPadding(dp(18),0,dp(18),0);EditText title=field("Decision title",false),ctx=field("Context / problem",true),options=field("Options considered",true),outcome=field("Choice and why",true),consequences=field("Expected consequences",true);form.addView(title);form.addView(ctx);form.addView(options);form.addView(outcome);form.addView(consequences);new AlertDialog.Builder(this).setTitle("Record decision").setMessage("Saved privately on this device. Add the context and reasoning you may want to compare with the outcome later.").setView(form).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{String name=title.getText().toString().trim();if(name.isEmpty())name="Untitled decision";db.addDecision(name,ctx.getText().toString(),options.getText().toString(),outcome.getText().toString(),consequences.getText().toString());Toast.makeText(this,"Decision saved",Toast.LENGTH_SHORT).show();loadDecisions();if(remoteAvailable)syncDecision(name,ctx.getText().toString(),options.getText().toString(),outcome.getText().toString(),consequences.getText().toString());}).show();}
    private EditText field(String hint,boolean multi){EditText e=new EditText(this);e.setHint(hint);e.setTextColor(TEXT);e.setHintTextColor(MUTED);e.setSingleLine(!multi);e.setInputType(InputType.TYPE_CLASS_TEXT|(multi?InputType.TYPE_TEXT_FLAG_MULTI_LINE:0));e.setMinLines(multi?2:1);return e;}
    private void loadSocial(){select(social);content.removeAllViews();section("Social Radar","Current relationship context, grounded follow-ups and recent changes");List<LifeDb.Conversation> xs=db.recentConversations(40);if(xs.isEmpty()){empty("No person-level conversation history is available yet. Keep notification or screen context access enabled while you use messaging apps.");return;}List<LifeDb.Loop> loops=db.openLoops(100);NotificationMeaningStore meanings=NotificationMeaningStore.get(this);for(LifeDb.Conversation x:xs){ProactiveSummaryEngine.Result fallback=ProactiveSummaryEngine.summarizeConversation(x.label,db.eventsForThread(x.app,x.threadKey,x.label,80));NotificationMeaning brain=meanings.forStream(x.threadKey);int waiting=waitingFor(x,loops);boolean brainWaiting=brain!=null&&brain.needsAttention()&&"PERSON_CONVERSATION".equals(brain.type);LinearLayout r=row();TextView name=text(x.label+"  ›",15,TEXT);name.setTypeface(Typeface.DEFAULT,Typeface.BOLD);r.addView(name);if(brainWaiting||waiting>0)r.addView(badge("WAITING ON YOU"));if(brain!=null&&brain.canSummarize()){String signal=!"NONE".equals(brain.intent)?brain.intent:brain.state;if(!"NONE".equals(signal)&&!"UNKNOWN".equals(signal))r.addView(badge(signal.replace('_',' ')));TextView summary=text(brain.summary,13,TEXT);summary.setPadding(0,dp(6),0,0);summary.setMaxLines(2);r.addView(summary);if(!brain.reason.isEmpty())r.addView(meta(brain.reason));}else{TextView summary=text(fallback.summary,13,TEXT);summary.setPadding(0,dp(6),0,0);summary.setMaxLines(2);r.addView(summary);}r.addView(meta("Updated from "+LifeDb.friendlyApp(x.app)));r.setOnClickListener(v->startActivity(new Intent(this,PersonDetailActivity.class).putExtra("event_id",x.latestEventId)));content.addView(r);}}
    private void loadDecisions(){select(decisions);content.removeAllViews();section("Decision Memory","What you chose, the context you had, and what you expected");List<LifeDb.Decision> xs=db.recentDecisions(60);if(xs.isEmpty()){empty("No decisions recorded yet. Record important choices here so LifeOS can compare the original reasoning with later outcomes.");return;}for(LifeDb.Decision x:xs){LinearLayout r=row();TextView title=text(x.title,15,TEXT);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);r.addView(title);if(!x.choice.isEmpty()){TextView choice=text(x.choice,13,TEXT);choice.setPadding(0,dp(6),0,0);choice.setMaxLines(3);r.addView(choice);}if(!x.context.isEmpty())r.addView(meta(x.context));r.addView(meta(new java.text.SimpleDateFormat("MMM d, yyyy",java.util.Locale.getDefault()).format(new java.util.Date(x.createdAt))));content.addView(r);}}
    private int waitingFor(LifeDb.Conversation conversation,List<LifeDb.Loop> loops){int count=0;for(LifeDb.Loop loop:loops){LifeDb.Event e=db.eventById(loop.evidenceId);if(e!=null&&conversation.app.equals(e.app)&&(!conversation.threadKey.isEmpty()&&conversation.threadKey.equals(e.threadKey)||conversation.label.equalsIgnoreCase(LifeDb.personLabel(e))))count++;}return count;}
    private void syncDecision(String title,String context,String options,String choice,String consequences){new Thread(()->{try{LifeSignalsSync.recordDecision(this,title,"accepted","",context,options,choice,consequences);}catch(Exception ignored){}},"decision-memory-sync").start();}
    private void showFacts(String title,String sub,List<GraphitiGateway.Fact> xs){content.removeAllViews();section(title,sub);if(xs.isEmpty()){empty("No matching temporal facts returned yet.");return;}for(GraphitiGateway.Fact x:xs){LinearLayout r=row();TextView n=text((x.current()?"CURRENT · ":"SUPERSEDED · ")+(x.name==null||x.name.isEmpty()?"Fact":x.name),12,x.current()?GREEN:MUTED);n.setTypeface(Typeface.DEFAULT,Typeface.BOLD);r.addView(n);TextView f=text(x.fact,14,TEXT);f.setPadding(0,dp(6),0,0);r.addView(f);String when=x.validAt==null?x.createdAt:x.validAt;if(when!=null)r.addView(meta(when+(x.invalidAt==null?"":" · invalidated "+x.invalidAt)));content.addView(r);}}
    private void loading(String message){content.removeAllViews();section("Life Signals",message);} private void error(Exception e){connection.setText("Local intelligence active");connection.setTextColor(GREEN);loadSocial();}
    private void section(String t,String s){TextView h=text(t,20,TEXT);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);content.addView(h);TextView sub=text(s,12,MUTED);sub.setPadding(0,dp(2),0,dp(12));content.addView(sub);} private void empty(String x){LinearLayout r=row();r.addView(text(x,14,MUTED));content.addView(r);}
    private LinearLayout row(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(14),dp(13),dp(14),dp(13));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(8));c.setLayoutParams(p);c.setBackground(round(SURFACE,BORDER,8));return c;} private TextView meta(String x){TextView v=text(x,11,MUTED);v.setPadding(0,dp(8),0,0);return v;}private TextView badge(String x){TextView v=text(x,10,GREEN);v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);v.setPadding(dp(7),dp(3),dp(7),dp(3));v.setLayoutParams(new LinearLayout.LayoutParams(-2,-2));v.setBackground(round(Color.TRANSPARENT,GREEN,20));return v;}
    private Button tab(String x){Button b=new Button(this);b.setText(x);b.setTextColor(MUTED);b.setTextSize(12);b.setAllCaps(false);b.setBackgroundColor(Color.TRANSPARENT);return b;} private void select(Button active){for(Button b:new Button[]{social,decisions}){b.setTextColor(b==active?TEXT:MUTED);b.setTypeface(Typeface.DEFAULT,b==active?Typeface.BOLD:Typeface.NORMAL);}}
    private Button secondary(String x){Button b=new Button(this);b.setText(x);b.setTextColor(TEXT);b.setTextSize(12);b.setAllCaps(false);b.setGravity(Gravity.CENTER);b.setBackground(round(SURFACE,BORDER,7));return b;} private Button primary(String x){Button b=secondary(x);b.setBackground(round(BLUE,BLUE,7));b.setTextColor(Color.WHITE);return b;}
    private View divider(){View v=new View(this);v.setBackgroundColor(BORDER);v.setLayoutParams(new LinearLayout.LayoutParams(-1,dp(1)));return v;} private GradientDrawable round(int fill,int stroke,int radius){GradientDrawable g=new GradientDrawable();g.setColor(fill);g.setCornerRadius(dp(radius));g.setStroke(dp(1),stroke);return g;} private TextView text(String x,int size,int color){TextView v=new TextView(this);v.setText(x);v.setTextSize(size);v.setTextColor(color);v.setLineSpacing(0,1.08f);return v;} private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
}
