package com.kareem.lifeos;

import android.app.Notification;
import android.app.PendingIntent;
import android.content.ComponentName;
import android.os.Bundle;
import android.os.Parcelable;
import android.service.notification.NotificationListenerService;
import android.service.notification.StatusBarNotification;
import com.kareem.lifeos.context.NotificationCapture;
import com.kareem.lifeos.context.NotificationObservationAdapter;
import com.kareem.lifeos.context.RawObservation;
import com.kareem.lifeos.context.UniversalObservationStore;
import com.kareem.lifeos.engine.NotificationUnderstandingProbe;
import java.lang.ref.WeakReference;
import java.lang.reflect.Method;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;

/** Loss-minimizing notification ingress with durable source return addresses. */
public final class LifeNotificationListener extends NotificationListenerService {
    private static final NotificationObservationAdapter V2_ADAPTER=new NotificationObservationAdapter();private static volatile WeakReference<LifeNotificationListener> live=new WeakReference<>(null);
    @Override public void onNotificationPosted(StatusBarNotification sbn){processNotification(sbn);}
    @Override public void onListenerConnected(){super.onListenerConnected();live=new WeakReference<>(this);try{StatusBarNotification[] active=getActiveNotifications();if(active!=null)for(StatusBarNotification sbn:active)processNotification(sbn);}catch(Throwable ignored){}try{BackgroundBrain.poke(this);}catch(Throwable ignored){}}
    @Override public void onListenerDisconnected(){super.onListenerDisconnected();live=new WeakReference<>(null);try{requestRebind(new ComponentName(this,LifeNotificationListener.class));}catch(Throwable ignored){}}
    @Override public void onDestroy(){LifeNotificationListener x=live.get();if(x==this)live=new WeakReference<>(null);super.onDestroy();}
    static boolean openActiveNotification(String notificationKey){LifeNotificationListener s=live.get();if(s==null||notificationKey==null||notificationKey.isEmpty())return false;try{StatusBarNotification[] active=s.getActiveNotifications();if(active==null)return false;for(StatusBarNotification n:active){if(notificationKey.equals(n.getKey())&&n.getNotification()!=null&&n.getNotification().contentIntent!=null){n.getNotification().contentIntent.send();return true;}}}catch(PendingIntent.CanceledException ignored){}catch(Throwable ignored){}return false;}

    private void processNotification(StatusBarNotification sbn){if(sbn==null||sbn.getNotification()==null)return;String app=sbn.getPackageName()==null?"unknown":sbn.getPackageName();if(getPackageName().equals(app))return;Notification n=sbn.getNotification();Bundle e=n.extras==null?Bundle.EMPTY:n.extras;String title=text(e.getCharSequence(Notification.EXTRA_TITLE));String body=text(e.getCharSequence(Notification.EXTRA_BIG_TEXT));if(body.isEmpty())body=text(e.getCharSequence(Notification.EXTRA_TEXT));String conversation=text(e.getCharSequence(Notification.EXTRA_CONVERSATION_TITLE));boolean group=e.getBoolean(Notification.EXTRA_IS_GROUP_CONVERSATION,false);String category=n.category==null?"":n.category;String channel=n.getChannelId()==null?"":n.getChannelId();boolean ongoing=sbn.isOngoing();String base=sbn.getKey()==null?app+"|"+sbn.getId()+"|"+sbn.getPostTime():sbn.getKey();try(LifeDb db=new LifeDb(this)){List<MessagePart> messages=structuredMessages(e,sbn.getPostTime());Set<String> seen=new HashSet<>();boolean stored=false;for(MessagePart m:messages){String normalized=(m.sender+"\n"+m.text).toLowerCase(Locale.ROOT).replaceAll("\\s+"," ").trim();if(m.text.isEmpty()||!seen.add(normalized))continue;store(db,base+"|msg|"+m.at+"|"+sha(m.sender+"\n"+m.text),app,title,conversation,m.sender,m.text,category,channel,group,ongoing,m.at);stored=true;}if(!stored){CharSequence[] lines=e.getCharSequenceArray(Notification.EXTRA_TEXT_LINES);boolean had=false;if(lines!=null)for(int i=0;i<lines.length;i++){String line=text(lines[i]);String normalized=line.toLowerCase(Locale.ROOT).replaceAll("\\s+"," ").trim();if(line.isEmpty()||!seen.add(normalized))continue;had=true;store(db,base+"|line|"+i+"|"+sha(line),app,title,conversation,"",line,category,channel,group,ongoing,sbn.getPostTime());}if(!had)store(db,base+"|body|"+sha(body),app,title,conversation,"",body,category,channel,group,ongoing,sbn.getPostTime());}}catch(Throwable ignored){}
    }
    private boolean store(LifeDb db,String key,String app,String originalTitle,String conversation,String sender,String body,String category,String channel,boolean group,boolean ongoing,long at){String structural=!conversation.trim().isEmpty()?conversation.trim():!sender.trim().isEmpty()?sender.trim():originalTitle.trim();String thread=app+"|"+structural.toLowerCase(Locale.ROOT).trim();String participant=participant(originalTitle,conversation,sender,body);if(!participant.isEmpty()&&conversation.trim().isEmpty())thread=app+"|"+participant.toLowerCase(Locale.ROOT).trim();boolean sensitive=isSensitive(originalTitle+" "+body);String captured=sensitive?"[sensitive notification content redacted]":body;NotificationCapture capture=new NotificationCapture(key,app,originalTitle,conversation,sender,captured,category,channel,group,ongoing,at);RawObservation raw=V2_ADAPTER.adapt(capture);UniversalObservationStore.get(this).append(raw);if(sensitive||CapturePolicy.isNotificationSummary(body))return false;NotificationUnderstandingProbe.observe(this,thread,body,at,key);String eventTitle=structural.isEmpty()?LifeDb.friendlyApp(app):structural;long id=db.upsertEvent(key,app,eventTitle,body,thread,at);if(id>0){SourceLocatorStore.get(this).record(id,notificationBase(key),app,thread,at);LifeDb.Event event=db.eventById(id);FastAttentionGate.Result fast=FastAttentionGate.evaluate(event,raw,System.currentTimeMillis());AttentionStore attention=AttentionStore.get(this);attention.enqueue(raw.observationId,raw.streamId,id,raw.observedAt,fast.queuePriority);if(fast.provisional)attention.provisional(raw.observationId,raw.streamId,id,raw.observedAt,fast.type,fast.intent,fast.urgency,fast.action,UserFacingText.humanize(fast.summary),UserFacingText.humanize(fast.reason),fast.confidence,fast.attentionPriority);for(OpenLoopExtractor.Candidate x:OpenLoopExtractor.extract(eventTitle,body,System.currentTimeMillis()))db.upsertLoop(id,x);LocalGroundedMemory.materialize(this,event);BackgroundBrain.poke(this);return true;}return false;}
    private static String notificationBase(String key){int cut=key.length();for(String marker:new String[]{"|msg|","|line|","|body|"}){int i=key.lastIndexOf(marker);if(i>=0&&i<cut)cut=i;}return key.substring(0,cut);}
    private static List<MessagePart> structuredMessages(Bundle extras,long fallbackAt){ArrayList<MessagePart> out=new ArrayList<>();Parcelable[] parcels=extras.getParcelableArray(Notification.EXTRA_MESSAGES);if(parcels==null)return out;for(Parcelable parcel:parcels){if(!(parcel instanceof Bundle))continue;Bundle b=(Bundle)parcel;String message=text(b.getCharSequence("text"));long at=b.getLong("time",fallbackAt);String sender=text(b.getCharSequence("sender"));if(sender.isEmpty())sender=personName(b.getParcelable("sender_person"));if(!message.isEmpty())out.add(new MessagePart(sender,message,at>0?at:fallbackAt));}return out;}
    private static String personName(Object person){if(person==null)return "";try{Method m=person.getClass().getMethod("getName");Object v=m.invoke(person);return v==null?"":v.toString().trim();}catch(Exception ignored){return "";}}
    private static String participant(String title,String conversation,String sender,String body){if(conversation!=null&&!conversation.trim().isEmpty())return conversation.trim();if(sender!=null&&!sender.trim().isEmpty())return sender.trim();String t=title==null?"":title.trim(),low=t.toLowerCase(Locale.ROOT);if(!low.equals("whatsapp")&&!low.equals("messenger")&&!low.equals("telegram")&&!low.equals("signal")&&!low.contains("new message"))return "";int colon=body==null?-1:body.indexOf(':');return colon>1&&colon<80?body.substring(0,colon).trim():"";}
    private static boolean isSensitive(String s){String x=s==null?"":s.toLowerCase(Locale.ROOT);return x.contains("otp")||x.contains("one-time password")||x.contains("verification code")||x.contains("رمز التحقق")||x.contains("كود التحقق");}
    private static String text(CharSequence x){return x==null?"":x.toString().trim();}
    private static String sha(String value){try{byte[] b=MessageDigest.getInstance("SHA-256").digest((value==null?"":value).getBytes(StandardCharsets.UTF_8));StringBuilder x=new StringBuilder();for(byte q:b)x.append(String.format(Locale.US,"%02x",q));return x.toString();}catch(Exception e){return Integer.toHexString(value==null?0:value.hashCode());}}
    private static final class MessagePart{final String sender,text;final long at;MessagePart(String sender,String text,long at){this.sender=sender==null?"":sender;this.text=text==null?"":text;this.at=at;}}
}
