package com.kareem.lifeos;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.Intent;
import android.os.Bundle;
import android.provider.Settings;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import com.kareem.lifeos.context.UniversalObservationStore;
import com.kareem.lifeos.memory.PersistentLifeMemoryStore;

/** Human-readable system health. Donor/runtime plumbing stays out of normal LifeOS UX. */
public final class MainActivity extends Activity {
    private LifeDb db;private LinearLayout content;
    @Override public void onCreate(Bundle s){super.onCreate(s);db=new LifeDb(this);render();}
    @Override protected void onResume(){super.onResume();refresh();}
    @Override protected void onDestroy(){db.close();super.onDestroy();}
    private void render(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(LifeOsUi.BG);LinearLayout head=LifeOsUi.topBar(this,"LifeOS Health",false);Button back=LifeOsUi.button(this,"‹");back.setTextSize(20);back.setOnClickListener(v->finish());head.addView(back,0,new LinearLayout.LayoutParams(LifeOsUi.dp(this,46),LifeOsUi.dp(this,46)));root.addView(head);TextView sub=LifeOsUi.text(this,"Capture, intelligence, memory and processing status",12,LifeOsUi.MUTED);sub.setPadding(LifeOsUi.dp(this,16),0,LifeOsUi.dp(this,16),LifeOsUi.dp(this,10));root.addView(sub);ScrollView sc=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(LifeOsUi.dp(this,16),LifeOsUi.dp(this,4),LifeOsUi.dp(this,16),LifeOsUi.dp(this,24));sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
    private void refresh(){content.removeAllViews();String listeners=Settings.Secure.getString(getContentResolver(),"enabled_notification_listeners"),services=Settings.Secure.getString(getContentResolver(),Settings.Secure.ENABLED_ACCESSIBILITY_SERVICES);boolean notif=listeners!=null&&listeners.contains(getPackageName()),screen=services!=null&&services.contains(getPackageName());IntelligenceStatus.Snapshot s=IntelligenceStatus.snapshot(this);BackgroundModelManager.Status model=BackgroundModelManager.status(this);int raw=UniversalObservationStore.get(this).count(),mem=PersistentLifeMemoryStore.get(this).searchable().size();content.addView(LifeOsUi.section(this,"System health"));health("Capture",notif&&screen?"Active":notif||screen?"Partially active":"Needs access",notif&&screen);health("Background Brain",model.ready()?"Ready":model.state+(model.progress>0?" · "+model.progress+"%":""),model.ready());health("Memory",raw+" observations · "+mem+" durable memories",true);health("Processing",s.pending==0?"Everything ready":s.pending+" items processing",s.pending==0);health("Attention",AttentionStore.get(this).openItems(1000).size()+" open items",true);content.addView(LifeOsUi.section(this,"Access"));Button n=LifeOsUi.button(this,"Notification access");n.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_NOTIFICATION_LISTENER_SETTINGS)));content.addView(n,new LinearLayout.LayoutParams(-1,LifeOsUi.dp(this,50)));Button a=LifeOsUi.button(this,"Screen context");a.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS)));LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,LifeOsUi.dp(this,50));ap.setMargins(0,LifeOsUi.dp(this,8),0,0);content.addView(a,ap);content.addView(LifeOsUi.section(this,"Advanced"));Button audit=LifeOsUi.button(this,"Run experience audit");audit.setOnClickListener(v->startActivity(new Intent(this,ExperienceAuditActivity.class)));content.addView(audit,new LinearLayout.LayoutParams(-1,LifeOsUi.dp(this,50)));Button erase=LifeOsUi.button(this,"Erase local LifeOS data");erase.setTextColor(LifeOsUi.RED);erase.setOnClickListener(v->confirmErase());LinearLayout.LayoutParams ep=new LinearLayout.LayoutParams(-1,LifeOsUi.dp(this,50));ep.setMargins(0,LifeOsUi.dp(this,8),0,0);content.addView(erase,ep);}
    private void health(String title,String value,boolean ok){LinearLayout c=LifeOsUi.card(this);TextView t=LifeOsUi.text(this,title,14,LifeOsUi.TEXT);t.setTypeface(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);c.addView(t);TextView v=LifeOsUi.text(this,(ok?"● ":"○ ")+value,12,ok?LifeOsUi.GREEN:LifeOsUi.AMBER);v.setPadding(0,LifeOsUi.dp(this,5),0,0);c.addView(v);content.addView(c);}
    private void confirmErase(){new AlertDialog.Builder(this).setTitle("Erase local LifeOS data?").setMessage("This removes captured evidence, memory, attention and source locators stored by this install.").setNegativeButton("Cancel",null).setPositiveButton("Erase",(d,w)->{db.eraseAll();AttentionStore.get(this).eraseAll();NotificationMeaningStore.get(this).eraseAll();com.kareem.lifeos.engine.PersistentUnderstandingStore.get(this).eraseAllUnderstanding();UniversalObservationStore.get(this).eraseAll();PersistentLifeMemoryStore.get(this).eraseAll();SourceLocatorStore.get(this).eraseAll();refresh();}).show();}
}
