package com.kareem.lifeos;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.Intent;
import android.os.Bundle;
import android.provider.Settings;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import com.kareem.lifeos.context.UniversalObservationStore;
import com.kareem.lifeos.memory.PersistentLifeMemoryStore;

/** Human-facing LifeOS status reached from the status ring or avatar. */
public final class MainActivity extends Activity {
    private LifeDb db;private LinearLayout content;
    @Override public void onCreate(Bundle s){super.onCreate(s);db=new LifeDb(this);render();}
    @Override protected void onResume(){super.onResume();refresh();}
    @Override protected void onDestroy(){db.close();super.onDestroy();}
    private void render(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(LifeOsUi.BG);root.addView(LifeOsUi.detailTopBar(this,"LifeOS status"));ScrollView sc=new ScrollView(this);sc.setVerticalScrollBarEnabled(false);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(LifeOsUi.dp(this,16),LifeOsUi.dp(this,8),LifeOsUi.dp(this,16),LifeOsUi.dp(this,24));sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
    private void refresh(){content.removeAllViews();String listeners=Settings.Secure.getString(getContentResolver(),"enabled_notification_listeners"),services=Settings.Secure.getString(getContentResolver(),Settings.Secure.ENABLED_ACCESSIBILITY_SERVICES);boolean notif=listeners!=null&&listeners.contains(getPackageName()),screen=services!=null&&services.contains(getPackageName());IntelligenceStatus.Snapshot s=IntelligenceStatus.snapshot(this);BackgroundModelManager.Status model=BackgroundModelManager.status(this);int raw=UniversalObservationStore.get(this).count(),mem=PersistentLifeMemoryStore.get(this).searchable().size();
        LinearLayout hero=new LinearLayout(this);hero.setOrientation(LinearLayout.VERTICAL);hero.setGravity(Gravity.CENTER_HORIZONTAL);hero.addView(LifeOsUi.statusRing(this,s,64),new LinearLayout.LayoutParams(LifeOsUi.dp(this,76),LifeOsUi.dp(this,76)));TextView title=LifeOsUi.text(this,stateTitle(s,notif,screen),18f,LifeOsUi.TEXT);LifeOsUi.weight(title,700);title.setGravity(Gravity.CENTER);title.setPadding(0,LifeOsUi.dp(this,7),0,0);hero.addView(title);TextView sub=LifeOsUi.text(this,stateDescription(s,notif,screen),10.6f,LifeOsUi.MUTED);LifeOsUi.weight(sub,500);sub.setGravity(Gravity.CENTER);sub.setPadding(0,LifeOsUi.dp(this,3),0,LifeOsUi.dp(this,9));hero.addView(sub);content.addView(hero);
        content.addView(LifeOsUi.section(this,"System health"));health("Capture",notif&&screen?"Active":notif||screen?"Partially active":"Needs access",notif&&screen);health("Background intelligence",model.ready()?"Ready":human(model.state)+(model.progress>0?" · "+model.progress+"%":""),model.ready());health("Memory",raw+" observations · "+mem+" durable memories",true);health("Processing",s.pending==0?"Everything ready":s.pending+" items processing",s.pending==0);health("Attention",AttentionStore.get(this).openCount()+" open items",true);
        content.addView(LifeOsUi.section(this,"Access"));Button n=LifeOsUi.button(this,"Notification access");n.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_NOTIFICATION_LISTENER_SETTINGS)));content.addView(n,new LinearLayout.LayoutParams(-1,LifeOsUi.dp(this,46)));Button a=LifeOsUi.button(this,"Screen context");a.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS)));LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,LifeOsUi.dp(this,46));ap.setMargins(0,LifeOsUi.dp(this,7),0,0);content.addView(a,ap);
        content.addView(LifeOsUi.section(this,"Advanced"));Button audit=LifeOsUi.button(this,"Run experience audit");audit.setOnClickListener(v->startActivity(new Intent(this,ExperienceAuditActivity.class)));content.addView(audit,new LinearLayout.LayoutParams(-1,LifeOsUi.dp(this,46)));Button erase=LifeOsUi.button(this,"Erase local LifeOS data");erase.setTextColor(LifeOsUi.RED);erase.setOnClickListener(v->confirmErase());LinearLayout.LayoutParams ep=new LinearLayout.LayoutParams(-1,LifeOsUi.dp(this,46));ep.setMargins(0,LifeOsUi.dp(this,7),0,0);content.addView(erase,ep);}
    private void health(String title,String value,boolean ok){LinearLayout c=LifeOsUi.card(this);TextView t=LifeOsUi.text(this,title,12.5f,LifeOsUi.TEXT);LifeOsUi.weight(t,700);c.addView(t);TextView v=LifeOsUi.text(this,(ok?"● ":"○ ")+value,10.4f,ok?LifeOsUi.GREEN:LifeOsUi.AMBER);LifeOsUi.weight(v,500);v.setPadding(0,LifeOsUi.dp(this,4),0,0);c.addView(v);content.addView(c);}
    private static String stateTitle(IntelligenceStatus.Snapshot s,boolean notif,boolean screen){if(!notif||!screen)return "LifeOS needs access";if("download_failed".equals(s.modelState)||"download_paused".equals(s.modelState)||"unavailable".equals(s.modelState))return "LifeOS needs attention";if(s.pending>0||s.backgroundRunning||"downloading".equals(s.modelState)||"verifying".equals(s.modelState))return "LifeOS is analyzing";return "LifeOS is ready";}
    private static String stateDescription(IntelligenceStatus.Snapshot s,boolean notif,boolean screen){if(!notif||!screen)return "Enable the missing capture access so LifeOS can keep your context complete.";if("download_failed".equals(s.modelState)||"download_paused".equals(s.modelState)||"unavailable".equals(s.modelState))return "Background intelligence setup needs action; captured data remains safe.";if(s.pending>0||s.backgroundRunning)return "Grounded context is being processed in the background.";if("downloading".equals(s.modelState)||"verifying".equals(s.modelState))return "The background intelligence model is being prepared.";return "Nothing is waiting to be processed right now.";}
    private static String human(String x){String v=x==null?"unknown":x.replace('_',' ').trim();return v.isEmpty()?"Unknown":Character.toUpperCase(v.charAt(0))+v.substring(1);}
    private void confirmErase(){new AlertDialog.Builder(this).setTitle("Erase local LifeOS data?").setMessage("This removes captured evidence, memory, attention and source locators stored by this install.").setNegativeButton("Cancel",null).setPositiveButton("Erase",(d,w)->{db.eraseAll();AttentionStore.get(this).eraseAll();NotificationMeaningStore.get(this).eraseAll();com.kareem.lifeos.engine.PersistentUnderstandingStore.get(this).eraseAllUnderstanding();UniversalObservationStore.get(this).eraseAll();PersistentLifeMemoryStore.get(this).eraseAll();SourceLocatorStore.get(this).eraseAll();refresh();}).show();}
}
