package com.kareem.lifeos;

import android.app.Activity;
import android.content.Intent;
import android.content.SharedPreferences;
import android.graphics.Color;
import android.os.Bundle;
import android.speech.RecognizerIntent;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.Gravity;
import android.view.View;
import android.view.inputmethod.EditorInfo;
import android.widget.Button;
import android.widget.EditText;
import android.widget.HorizontalScrollView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/** Search is the visible capability hub: one simple entrance into the full connected LifeOS. */
public final class SearchActivity extends Activity {
    private static final int VOICE=41;private LinearLayout content;private EditText query;private String filter="All";private final Map<String,Button> chipViews=new LinkedHashMap<>();
    @Override public void onCreate(Bundle s){super.onCreate(s);render();String initial=getIntent().getStringExtra("initial_query");String initialFilter=getIntent().getStringExtra("initial_filter");if(initialFilter!=null&&!initialFilter.isEmpty()){filter=initialFilter;updateChips();}if(initial!=null&&!initial.trim().isEmpty()){query.setText(initial.trim());query.setSelection(query.length());}}

    private void render(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(LifeOsUi.BG);root.addView(LifeOsUi.topBar(this,"Search",false));
        LinearLayout search=new LinearLayout(this);search.setGravity(Gravity.CENTER_VERTICAL);search.setPadding(LifeOsUi.dp(this,13),0,LifeOsUi.dp(this,5),0);search.setBackground(LifeOsUi.round(this,LifeOsUi.SURFACE_2,LifeOsUi.BORDER,25));search.addView(LifeOsUi.icon(this,LifeOsIconView.SEARCH,LifeOsUi.MUTED,20),new LinearLayout.LayoutParams(LifeOsUi.dp(this,24),LifeOsUi.dp(this,24)));
        query=new EditText(this);query.setHint("Search your life…");query.setHintTextColor(LifeOsUi.MUTED);query.setTextColor(LifeOsUi.TEXT);query.setSingleLine(true);query.setTextSize(LifeOsUi.refSp(12.2f));LifeOsUi.weight(query,500);query.setImeOptions(EditorInfo.IME_ACTION_SEARCH);query.setPadding(LifeOsUi.dp(this,9),0,0,0);query.setBackgroundColor(Color.TRANSPARENT);search.addView(query,new LinearLayout.LayoutParams(0,-1,1));View mic=LifeOsUi.iconTouch(this,LifeOsIconView.MIC,LifeOsUi.MUTED,20,40);mic.setContentDescription("Voice search");mic.setOnClickListener(v->startVoice());search.addView(mic,new LinearLayout.LayoutParams(LifeOsUi.dp(this,40),LifeOsUi.dp(this,40)));LinearLayout.LayoutParams qp=new LinearLayout.LayoutParams(-1,LifeOsUi.dp(this,50));qp.setMargins(LifeOsUi.dp(this,16),0,LifeOsUi.dp(this,16),LifeOsUi.dp(this,9));root.addView(search,qp);
        HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);LinearLayout chips=new LinearLayout(this);chips.setPadding(LifeOsUi.dp(this,16),0,LifeOsUi.dp(this,8),LifeOsUi.dp(this,7));for(String x:new String[]{"All","People","Files","Places","Decisions"}){Button b=LifeOsUi.chip(this,x,x.equals(filter));b.setOnClickListener(v->{filter=x;updateChips();runSearch();});chipViews.put(x,b);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,LifeOsUi.dp(this,34));p.setMargins(0,0,LifeOsUi.dp(this,7),0);chips.addView(b,p);}hs.addView(chips);root.addView(hs);
        ScrollView sc=new ScrollView(this);sc.setVerticalScrollBarEnabled(false);sc.setFillViewport(true);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(LifeOsUi.dp(this,16),0,LifeOsUi.dp(this,16),LifeOsUi.dp(this,10));sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));root.addView(LifeOsUi.bottomNav(this,SearchActivity.class));setContentView(root);
        query.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){runSearch();}public void afterTextChanged(Editable e){}});query.setOnEditorActionListener((v,id,e)->{if(id==EditorInfo.IME_ACTION_SEARCH){saveHistory(query.getText().toString());runSearch();return true;}return false;});showLanding();
    }

    private void updateChips(){for(Map.Entry<String,Button> e:chipViews.entrySet()){boolean on=e.getKey().equals(filter);e.getValue().setBackground(LifeOsUi.round(this,on?LifeOsUi.BLUE:LifeOsUi.SURFACE_2,on?LifeOsUi.BLUE:LifeOsUi.BORDER,18));e.getValue().setTextColor(on?Color.WHITE:LifeOsUi.TEXT);}}

    private void showLanding(){content.removeAllViews();content.addView(LifeOsUi.section(this,"Browse LifeOS"));List<LifeOsCapabilityRegistry.Capability> caps=LifeOsCapabilityRegistry.all(this);LinearLayout grid=new LinearLayout(this);grid.setOrientation(LinearLayout.VERTICAL);for(int i=0;i<caps.size();i+=2){LinearLayout row=new LinearLayout(this);LifeOsCapabilityRegistry.Capability left=caps.get(i);row.addView(capabilityTile(left),new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,78),1));if(i+1<caps.size()){LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,78),1);rp.setMargins(LifeOsUi.dp(this,7),0,0,0);row.addView(capabilityTile(caps.get(i+1)),rp);}else row.addView(new View(this),new LinearLayout.LayoutParams(0,1,1));LinearLayout.LayoutParams rowp=new LinearLayout.LayoutParams(-1,-2);rowp.setMargins(0,0,0,LifeOsUi.dp(this,7));grid.addView(row,rowp);}content.addView(grid);
        List<String> history=history();if(!history.isEmpty()){LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);TextView h=LifeOsUi.section(this,"Recent searches");head.addView(h,new LinearLayout.LayoutParams(0,-2,1));TextView clear=LifeOsUi.text(this,"Clear",10.5f,LifeOsUi.BLUE);LifeOsUi.weight(clear,500);clear.setOnClickListener(v->{prefs().edit().remove("history").apply();showLanding();});head.addView(clear);content.addView(head);for(String s:history)recentRow(s,()->{query.setText(s);query.setSelection(query.length());});}
    }

    private View capabilityTile(LifeOsCapabilityRegistry.Capability c){LinearLayout tile=new LinearLayout(this);tile.setOrientation(LinearLayout.HORIZONTAL);tile.setGravity(Gravity.CENTER_VERTICAL);tile.setPadding(LifeOsUi.dp(this,10),LifeOsUi.dp(this,8),LifeOsUi.dp(this,9),LifeOsUi.dp(this,8));tile.setBackground(LifeOsUi.round(this,LifeOsUi.SURFACE,LifeOsUi.BORDER,13));tile.addView(LifeOsUi.iconTile(this,c.icon,c.color,34),new LinearLayout.LayoutParams(LifeOsUi.dp(this,34),LifeOsUi.dp(this,34)));LinearLayout copy=new LinearLayout(this);copy.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(0,-2,1);cp.setMargins(LifeOsUi.dp(this,9),0,0,0);tile.addView(copy,cp);TextView title=LifeOsUi.text(this,c.label,11.4f,LifeOsUi.TEXT);LifeOsUi.weight(title,700);copy.addView(title);TextView count=LifeOsUi.text(this,c.primaryLine(),9.6f,LifeOsUi.MUTED);LifeOsUi.weight(count,500);count.setPadding(0,LifeOsUi.dp(this,2),0,0);copy.addView(count);TextView secondary=LifeOsUi.text(this,c.secondary,8.8f,c.color);LifeOsUi.weight(secondary,500);secondary.setMaxLines(1);copy.addView(secondary);tile.setOnClickListener(v->startActivity(new Intent(this,CapabilityActivity.class).putExtra("capability",c.id)));return tile;}

    private void recentRow(String title,Runnable action){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(0,LifeOsUi.dp(this,2),0,LifeOsUi.dp(this,2));row.addView(LifeOsUi.icon(this,LifeOsIconView.HISTORY,LifeOsUi.MUTED,20),new LinearLayout.LayoutParams(LifeOsUi.dp(this,28),LifeOsUi.dp(this,38)));TextView t=LifeOsUi.text(this,title,11.8f,LifeOsUi.TEXT);LifeOsUi.weight(t,500);t.setPadding(LifeOsUi.dp(this,9),0,0,0);row.addView(t,new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,44),1));row.addView(LifeOsUi.icon(this,LifeOsIconView.CHEVRON,LifeOsUi.TERTIARY,12),new LinearLayout.LayoutParams(LifeOsUi.dp(this,12),LifeOsUi.dp(this,22)));row.setOnClickListener(v->action.run());content.addView(row);}

    private void runSearch(){String q=query.getText().toString().trim();if(q.isEmpty()){showLanding();return;}content.removeAllViews();List<LifeIntelligenceEngine.Result> xs=LifeIntelligenceEngine.search(this,q,80);int shown=0;for(LifeIntelligenceEngine.Result r:xs){if(!matchesFilter(r))continue;resultRow(r);shown++;if(shown>=40)break;}if(shown==0){TextView none=LifeOsUi.text(this,"No grounded result found for this search yet.",11.5f,LifeOsUi.MUTED);LifeOsUi.weight(none,500);none.setPadding(0,LifeOsUi.dp(this,14),0,0);content.addView(none);}}
    private void resultRow(LifeIntelligenceEngine.Result r){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(0,LifeOsUi.dp(this,7),0,LifeOsUi.dp(this,7));String icon=iconFor(r);int color=colorFor(r);row.addView(LifeOsUi.iconTile(this,icon,color,36),new LinearLayout.LayoutParams(LifeOsUi.dp(this,36),LifeOsUi.dp(this,36)));LinearLayout txt=new LinearLayout(this);txt.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,-2,1);tp.setMargins(LifeOsUi.dp(this,10),0,LifeOsUi.dp(this,8),0);row.addView(txt,tp);TextView t=LifeOsUi.text(this,UserFacingText.humanize(r.title),12.2f,LifeOsUi.TEXT);LifeOsUi.weight(t,600);t.setMaxLines(1);txt.addView(t);TextView s=LifeOsUi.text(this,clip(UserFacingText.humanize(r.summary),140),10.2f,LifeOsUi.MUTED);LifeOsUi.weight(s,500);s.setPadding(0,LifeOsUi.dp(this,2),0,0);s.setMaxLines(2);txt.addView(s);row.addView(LifeOsUi.icon(this,LifeOsIconView.CHEVRON,LifeOsUi.TERTIARY,12),new LinearLayout.LayoutParams(LifeOsUi.dp(this,12),LifeOsUi.dp(this,22)));row.setOnClickListener(v->openResult(r));content.addView(row);}
    private void openResult(LifeIntelligenceEngine.Result r){saveHistory(query.getText().toString());if("People".equalsIgnoreCase(r.kind)&&r.eventId>0){startActivity(new Intent(this,PersonDetailActivity.class).putExtra("event_id",r.eventId));return;}if("Conversation".equalsIgnoreCase(r.kind)&&r.eventId>0){startActivity(new Intent(this,ConversationDetailActivity.class).putExtra("event_id",r.eventId));return;}startActivity(EntityDetailActivity.intent(this,r.kind,r.title,r.summary,r.eventId));}

    private boolean matchesFilter(LifeIntelligenceEngine.Result r){if("All".equals(filter))return true;if("People".equals(filter))return "People".equalsIgnoreCase(r.kind)||"Conversation".equalsIgnoreCase(r.kind);if("Decisions".equals(filter))return "Decision".equalsIgnoreCase(r.kind);String x=(r.kind+" "+r.title+" "+r.summary).toLowerCase(Locale.ROOT);if("Files".equals(filter))return x.contains("file")||x.contains("document")||x.contains("attachment")||x.matches(".*\\.(pdf|docx?|xlsx?|pptx?|jpg|png|zip).*" );return "Places".equals(filter)&&(x.contains("location")||x.contains("place")||x.contains("arrived")||x.contains("office")||x.contains("cairo")||x.contains("zamalek"));}
    private String iconFor(LifeIntelligenceEngine.Result r){String k=r.kind.toLowerCase(Locale.ROOT);if(k.contains("people")||k.contains("conversation"))return LifeOsIconView.PEOPLE;if(k.contains("decision"))return LifeOsIconView.DECISION;if(k.contains("memory")||k.contains("commit")||k.contains("attention"))return LifeOsIconView.COMMITMENT;if(k.contains("event")||k.contains("reminder"))return LifeOsIconView.EVENT;if(k.contains("place"))return LifeOsIconView.PLACE;return LifeOsIconView.FILE;}
    private int colorFor(LifeIntelligenceEngine.Result r){String k=r.kind.toLowerCase(Locale.ROOT);if(k.contains("people")||k.contains("conversation"))return LifeOsUi.PURPLE;if(k.contains("decision"))return LifeOsUi.PINK;if(k.contains("memory")||k.contains("commit"))return LifeOsUi.GREEN;if(k.contains("attention"))return LifeOsUi.RED;if(k.contains("event")||k.contains("reminder"))return LifeOsUi.PURPLE;if(k.contains("file"))return LifeOsUi.AMBER;return LifeOsUi.BLUE;}
    private void saveHistory(String value){String s=value==null?"":value.trim();if(s.isEmpty())return;ArrayList<String> h=new ArrayList<>(history());h.remove(s);h.add(0,s);while(h.size()>5)h.remove(h.size()-1);prefs().edit().putString("history",android.text.TextUtils.join("\u001f",h)).apply();}
    private List<String> history(){String raw=prefs().getString("history","");if(raw==null||raw.isEmpty())return new ArrayList<>();return new ArrayList<>(Arrays.asList(raw.split("\u001f")));}
    private SharedPreferences prefs(){return getSharedPreferences("lifeos_search",MODE_PRIVATE);}
    private void startVoice(){try{Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);startActivityForResult(i,VOICE);}catch(Throwable ignored){}}
    @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){super.onActivityResult(requestCode,resultCode,data);if(requestCode==VOICE&&resultCode==RESULT_OK&&data!=null){ArrayList<String> xs=data.getStringArrayListExtra(RecognizerIntent.EXTRA_RESULTS);if(xs!=null&&!xs.isEmpty()){query.setText(xs.get(0));query.setSelection(query.length());}}}
    private static String clip(String x,int n){String v=x==null?"":x.trim();return v.length()>n?v.substring(0,n)+"…":v;}
}
