package com.kareem.lifeos;

import android.app.Activity;
import android.content.Intent;
import android.content.SharedPreferences;
import android.graphics.Color;
import android.os.Bundle;
import android.speech.RecognizerIntent;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.Gravity;
import android.view.View;
import android.view.inputmethod.EditorInfo;
import android.widget.Button;
import android.widget.EditText;
import android.widget.HorizontalScrollView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/** Golden-reference Search: compact global retrieval, real history, flat semantic rows. */
public final class SearchActivity extends Activity {
    private static final int VOICE=41;private LinearLayout content;private EditText query;private String filter="All";private final Map<String,Button> chipViews=new LinkedHashMap<>();
    @Override public void onCreate(Bundle s){super.onCreate(s);render();}
    private void render(){
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(LifeOsUi.BG);root.addView(LifeOsUi.topBar(this,"Search",false));
        LinearLayout search=new LinearLayout(this);search.setGravity(Gravity.CENTER_VERTICAL);search.setPadding(LifeOsUi.dp(this,13),0,LifeOsUi.dp(this,5),0);search.setBackground(LifeOsUi.round(this,LifeOsUi.SURFACE_2,LifeOsUi.BORDER,26));search.addView(LifeOsUi.icon(this,LifeOsIconView.SEARCH,LifeOsUi.MUTED,20),new LinearLayout.LayoutParams(LifeOsUi.dp(this,24),LifeOsUi.dp(this,24)));
        query=new EditText(this);query.setHint("Search your life…");query.setHintTextColor(LifeOsUi.MUTED);query.setTextColor(LifeOsUi.TEXT);query.setSingleLine(true);query.setTextSize(LifeOsUi.refSp(12.2f));query.setImeOptions(EditorInfo.IME_ACTION_SEARCH);query.setPadding(LifeOsUi.dp(this,9),0,0,0);query.setBackgroundColor(Color.TRANSPARENT);search.addView(query,new LinearLayout.LayoutParams(0,-1,1));View mic=LifeOsUi.iconTouch(this,LifeOsIconView.MIC,LifeOsUi.MUTED,20,40);mic.setContentDescription("Voice search");mic.setOnClickListener(v->startVoice());search.addView(mic,new LinearLayout.LayoutParams(LifeOsUi.dp(this,40),LifeOsUi.dp(this,40)));LinearLayout.LayoutParams qp=new LinearLayout.LayoutParams(-1,LifeOsUi.dp(this,52));qp.setMargins(LifeOsUi.dp(this,16),0,LifeOsUi.dp(this,16),LifeOsUi.dp(this,9));root.addView(search,qp);
        HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);LinearLayout chips=new LinearLayout(this);chips.setPadding(LifeOsUi.dp(this,16),0,LifeOsUi.dp(this,8),LifeOsUi.dp(this,8));for(String x:new String[]{"All","People","Files","Places","Decisions"}){Button b=LifeOsUi.chip(this,x,x.equals(filter));b.setOnClickListener(v->{filter=x;updateChips();runSearch();});chipViews.put(x,b);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,LifeOsUi.dp(this,36));p.setMargins(0,0,LifeOsUi.dp(this,7),0);chips.addView(b,p);}hs.addView(chips);root.addView(hs);
        ScrollView sc=new ScrollView(this);sc.setVerticalScrollBarEnabled(false);sc.setFillViewport(true);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(LifeOsUi.dp(this,16),0,LifeOsUi.dp(this,16),LifeOsUi.dp(this,10));sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));root.addView(LifeOsUi.bottomNav(this,SearchActivity.class));setContentView(root);
        query.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){runSearch();}public void afterTextChanged(Editable e){}});query.setOnEditorActionListener((v,id,e)->{if(id==EditorInfo.IME_ACTION_SEARCH){saveHistory(query.getText().toString());runSearch();return true;}return false;});showLanding();
    }
    private void updateChips(){for(Map.Entry<String,Button> e:chipViews.entrySet()){boolean on=e.getKey().equals(filter);e.getValue().setBackground(LifeOsUi.round(this,on?LifeOsUi.BLUE:LifeOsUi.SURFACE_2,on?LifeOsUi.BLUE:LifeOsUi.BORDER,18));e.getValue().setTextColor(on?Color.WHITE:LifeOsUi.TEXT);}}
    private void showLanding(){content.removeAllViews();List<String> history=history();if(!history.isEmpty()){LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);TextView h=LifeOsUi.section(this,"Recent searches");head.addView(h,new LinearLayout.LayoutParams(0,-2,1));TextView clear=LifeOsUi.text(this,"Clear",10.5f,LifeOsUi.BLUE);LifeOsUi.weight(clear,500);clear.setOnClickListener(v->{prefs().edit().remove("history").apply();showLanding();});head.addView(clear);content.addView(head);for(String s:history)recentRow(s,()->{query.setText(s);query.setSelection(query.length());});}content.addView(LifeOsUi.section(this,"Suggested"));suggestedRow(LifeOsIconView.COMMITMENT,"Open commitments","Show what's waiting on you",LifeOsUi.GREEN,()->setQuery("Open commitments"));suggestedRow(LifeOsIconView.DECISION,"Decisions","Find past decisions",LifeOsUi.PINK,()->setQuery("What did I decide"));suggestedRow(LifeOsIconView.PEOPLE,"People","Search conversations and activities",LifeOsUi.PURPLE,()->setQuery("People"));suggestedRow(LifeOsIconView.FILE,"Files","Documents, photos, attachments",LifeOsUi.AMBER,()->setQuery("file document attachment"));suggestedRow(LifeOsIconView.PLACE,"Places","Locations you've been to",LifeOsUi.BLUE,()->setQuery("location place arrived"));suggestedRow(LifeOsIconView.EVENT,"Events","Meetings, appointments, reminders",LifeOsUi.PURPLE,()->setQuery("meeting appointment reminder"));}
    private void recentRow(String title,Runnable action){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(0,LifeOsUi.dp(this,2),0,LifeOsUi.dp(this,2));row.addView(LifeOsUi.icon(this,LifeOsIconView.HISTORY,LifeOsUi.MUTED,20),new LinearLayout.LayoutParams(LifeOsUi.dp(this,28),LifeOsUi.dp(this,38)));TextView t=LifeOsUi.text(this,title,11.8f,LifeOsUi.TEXT);t.setPadding(LifeOsUi.dp(this,9),0,0,0);row.addView(t,new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,44),1));row.addView(LifeOsUi.icon(this,LifeOsIconView.CHEVRON,LifeOsUi.MUTED,12),new LinearLayout.LayoutParams(LifeOsUi.dp(this,12),LifeOsUi.dp(this,22)));row.setOnClickListener(v->action.run());content.addView(row);}
    private void suggestedRow(String icon,String title,String sub,int color,Runnable action){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(0,LifeOsUi.dp(this,4),0,LifeOsUi.dp(this,4));row.addView(LifeOsUi.iconTile(this,icon,color,36),new LinearLayout.LayoutParams(LifeOsUi.dp(this,36),LifeOsUi.dp(this,36)));LinearLayout txt=new LinearLayout(this);txt.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,-2,1);tp.setMargins(LifeOsUi.dp(this,10),0,0,0);row.addView(txt,tp);TextView t=LifeOsUi.text(this,title,12.2f,LifeOsUi.TEXT);LifeOsUi.weight(t,600);txt.addView(t);TextView st=LifeOsUi.text(this,sub,10.2f,LifeOsUi.MUTED);st.setPadding(0,LifeOsUi.dp(this,2),0,0);txt.addView(st);row.addView(LifeOsUi.icon(this,LifeOsIconView.CHEVRON,LifeOsUi.MUTED,12),new LinearLayout.LayoutParams(LifeOsUi.dp(this,12),LifeOsUi.dp(this,22)));row.setOnClickListener(v->action.run());content.addView(row);}
    private void runSearch(){String q=query.getText().toString().trim();if(q.isEmpty()){showLanding();return;}content.removeAllViews();List<LifeIntelligenceEngine.Result> xs=LifeIntelligenceEngine.search(this,q,60);int shown=0;for(LifeIntelligenceEngine.Result r:xs){if(!matchesFilter(r))continue;resultRow(r);shown++;if(shown>=30)break;}if(shown==0){TextView none=LifeOsUi.text(this,"No grounded result found for this search yet.",11.5f,LifeOsUi.MUTED);none.setPadding(0,LifeOsUi.dp(this,14),0,0);content.addView(none);}}
    private void resultRow(LifeIntelligenceEngine.Result r){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(0,LifeOsUi.dp(this,7),0,LifeOsUi.dp(this,7));String icon=iconFor(r);int color="People".equalsIgnoreCase(r.kind)?LifeOsUi.PURPLE:"Decision".equalsIgnoreCase(r.kind)?LifeOsUi.PINK:"Memory".equalsIgnoreCase(r.kind)?LifeOsUi.GREEN:"Attention".equalsIgnoreCase(r.kind)?LifeOsUi.RED:LifeOsUi.BLUE;row.addView(LifeOsUi.iconTile(this,icon,color,36),new LinearLayout.LayoutParams(LifeOsUi.dp(this,36),LifeOsUi.dp(this,36)));LinearLayout txt=new LinearLayout(this);txt.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,-2,1);tp.setMargins(LifeOsUi.dp(this,10),0,LifeOsUi.dp(this,8),0);row.addView(txt,tp);TextView t=LifeOsUi.text(this,UserFacingText.humanize(r.title),12.2f,LifeOsUi.TEXT);LifeOsUi.weight(t,600);t.setMaxLines(1);txt.addView(t);TextView s=LifeOsUi.text(this,clip(UserFacingText.humanize(r.summary),120),10.2f,LifeOsUi.MUTED);s.setPadding(0,LifeOsUi.dp(this,2),0,0);s.setMaxLines(2);txt.addView(s);row.addView(LifeOsUi.icon(this,LifeOsIconView.CHEVRON,LifeOsUi.MUTED,12),new LinearLayout.LayoutParams(LifeOsUi.dp(this,12),LifeOsUi.dp(this,22)));if(r.eventId>0)row.setOnClickListener(v->startActivity(new Intent(this,EvidenceDetailActivity.class).putExtra("event_id",r.eventId)));content.addView(row);}
    private boolean matchesFilter(LifeIntelligenceEngine.Result r){if("All".equals(filter))return true;if("People".equals(filter))return "People".equalsIgnoreCase(r.kind);if("Decisions".equals(filter))return "Decision".equalsIgnoreCase(r.kind);String x=(r.kind+" "+r.title+" "+r.summary).toLowerCase(Locale.ROOT);if("Files".equals(filter))return x.contains("file")||x.contains("document")||x.contains("attachment")||x.matches(".*\\.(pdf|docx?|xlsx?|jpg|png|zip).*" );return "Places".equals(filter)&&(x.contains("location")||x.contains("place")||x.contains("arrived")||x.contains("office")||x.contains("cairo")||x.contains("zamalek"));}
    private String iconFor(LifeIntelligenceEngine.Result r){if("People".equalsIgnoreCase(r.kind))return LifeOsIconView.PEOPLE;if("Decision".equalsIgnoreCase(r.kind))return LifeOsIconView.DECISION;if("Memory".equalsIgnoreCase(r.kind))return LifeOsIconView.COMMITMENT;if("Attention".equalsIgnoreCase(r.kind))return LifeOsIconView.ALERT;return LifeOsIconView.FILE;}
    private void setQuery(String s){saveHistory(s);query.setText(s);query.setSelection(query.length());}
    private void saveHistory(String value){String s=value==null?"":value.trim();if(s.isEmpty())return;ArrayList<String> h=new ArrayList<>(history());h.remove(s);h.add(0,s);while(h.size()>5)h.remove(h.size()-1);prefs().edit().putString("history",android.text.TextUtils.join("\u001f",h)).apply();}
    private List<String> history(){String raw=prefs().getString("history","");if(raw==null||raw.isEmpty())return new ArrayList<>();return new ArrayList<>(Arrays.asList(raw.split("\u001f")));}
    private SharedPreferences prefs(){return getSharedPreferences("lifeos_search",MODE_PRIVATE);}
    private void startVoice(){try{Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);startActivityForResult(i,VOICE);}catch(Throwable ignored){}}
    @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){super.onActivityResult(requestCode,resultCode,data);if(requestCode==VOICE&&resultCode==RESULT_OK&&data!=null){ArrayList<String> xs=data.getStringArrayListExtra(RecognizerIntent.EXTRA_RESULTS);if(xs!=null&&!xs.isEmpty())setQuery(xs.get(0));}}
    private static String clip(String x,int n){String v=x==null?"":x.trim();return v.length()>n?v.substring(0,n)+"…":v;}
}
