package com.kareem.lifeos;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import com.kareem.lifeos.actions.PersistentActionQueue;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.List;

/** Situation detail follows the common LifeOS connected-detail architecture. */
public final class SituationDetailActivity extends Activity {
    private LifeDb db;private String situationId;private SituationEngine.Situation situation;private List<PersistentActionQueue.Item> actions;
    @Override public void onCreate(Bundle s){super.onCreate(s);db=new LifeDb(this);situationId=getIntent().getStringExtra("situation_id");}
    @Override protected void onResume(){super.onResume();load();render();}
    @Override protected void onDestroy(){db.close();super.onDestroy();}
    private void load(){actions=new PersistentActionQueue(this).pending();situation=SituationEngine.find(db,db.openLoops(120),actions,situationId==null?"":situationId,System.currentTimeMillis());}

    private void render(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(LifeOsUi.BG);root.addView(LifeOsUi.detailTopBar(this,situation==null?"Situation":situation.title));ScrollView sc=new ScrollView(this);sc.setVerticalScrollBarEnabled(false);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(LifeOsUi.dp(this,16),LifeOsUi.dp(this,7),LifeOsUi.dp(this,16),LifeOsUi.dp(this,24));sc.addView(body);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));if(situation==null){TextView none=LifeOsUi.text(this,"This situation is no longer active.",11.5f,LifeOsUi.MUTED);LifeOsUi.weight(none,500);body.addView(none);setContentView(root);return;}
        TextView eyebrow=LifeOsUi.text(this,"ACTIVE SITUATION",9.5f,situation.attentionCount>0?LifeOsUi.RED:LifeOsUi.GREEN);LifeOsUi.weight(eyebrow,700);body.addView(eyebrow);TextView h=LifeOsUi.text(this,UserFacingText.humanize(situation.title),20f,LifeOsUi.TEXT);LifeOsUi.weight(h,700);h.setPadding(0,LifeOsUi.dp(this,4),0,0);body.addView(h);TextView meta=LifeOsUi.text(this,"Updated "+DateFormat.getDateTimeInstance(DateFormat.SHORT,DateFormat.SHORT).format(new java.util.Date(situation.latestAt)),10.2f,LifeOsUi.MUTED);LifeOsUi.weight(meta,500);meta.setPadding(0,LifeOsUi.dp(this,3),0,0);body.addView(meta);
        body.addView(LifeOsUi.section(this,"Summary"));LinearLayout summary=LifeOsUi.card(this);TextView sv=LifeOsUi.text(this,safeSummary(),11.6f,LifeOsUi.TEXT);LifeOsUi.weight(sv,500);summary.addView(sv);if(!situation.why.isEmpty()){TextView why=LifeOsUi.text(this,UserFacingText.humanize(situation.why),10f,LifeOsUi.BLUE);LifeOsUi.weight(why,600);why.setPadding(0,LifeOsUi.dp(this,6),0,0);summary.addView(why);}body.addView(summary);
        body.addView(LifeOsUi.section(this,"What matters"));LinearLayout counts=new LinearLayout(this);stat(counts,String.valueOf(situation.attentionCount),"Open items",LifeOsIconView.ALERT,situation.attentionCount>0?LifeOsUi.RED:LifeOsUi.TERTIARY);stat(counts,String.valueOf(situation.actionCount),"Actions",LifeOsIconView.ACTION,situation.actionCount>0?LifeOsUi.GREEN:LifeOsUi.TERTIARY);stat(counts,String.valueOf(situation.eventCount),"Evidence",LifeOsIconView.FILE,LifeOsUi.BLUE);body.addView(counts);
        if(!situation.signals.isEmpty()){TextView signals=LifeOsUi.text(this,"Signals · "+join(situation.signals),9.8f,LifeOsUi.MUTED);LifeOsUi.weight(signals,500);signals.setPadding(0,LifeOsUi.dp(this,6),0,0);body.addView(signals);}
        body.addView(LifeOsUi.section(this,"Related"));for(Long lid:situation.loopIds){LifeDb.Loop l=findLoop(lid);if(l!=null)body.addView(loopRow(l));}for(String pid:situation.proposalIds){PersistentActionQueue.Item a=findAction(pid);if(a!=null)body.addView(actionRow(a));}
        body.addView(LifeOsUi.section(this,"Evidence"));List<LifeDb.Event> evidence=new ArrayList<>(SituationEngine.evidence(db,situation,40));int shown=Math.min(10,evidence.size());for(int i=0;i<shown;i++)body.addView(evidenceRow(evidence.get(i)));if(evidence.size()>shown){TextView more=LifeOsUi.text(this,(evidence.size()-shown)+" older evidence items remain available.",9.7f,LifeOsUi.MUTED);LifeOsUi.weight(more,500);body.addView(more);}
        body.addView(LifeOsUi.section(this,"Actions"));Button ask=LifeOsUi.primary(this,"Ask about this situation");ask.setOnClickListener(v->startActivity(new Intent(this,AskLifeOsActivity.class).putExtra("initial_question","What matters about "+situation.title+", what is still unresolved, and what should I do next?")));body.addView(ask,new LinearLayout.LayoutParams(-1,LifeOsUi.dp(this,44)));setContentView(root);
    }

    private void stat(LinearLayout row,String value,String label,String icon,int color){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(LifeOsUi.dp(this,8),LifeOsUi.dp(this,7),LifeOsUi.dp(this,6),LifeOsUi.dp(this,6));c.setBackground(LifeOsUi.round(this,LifeOsUi.SURFACE,LifeOsUi.BORDER,12));LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.addView(LifeOsUi.icon(this,icon,color,12),new LinearLayout.LayoutParams(LifeOsUi.dp(this,12),LifeOsUi.dp(this,12)));TextView n=LifeOsUi.text(this,value,14f,color);LifeOsUi.weight(n,700);LinearLayout.LayoutParams np=new LinearLayout.LayoutParams(-2,-2);np.leftMargin=LifeOsUi.dp(this,5);top.addView(n,np);c.addView(top);TextView l=LifeOsUi.text(this,label,8.8f,LifeOsUi.MUTED);LifeOsUi.weight(l,500);l.setPadding(0,LifeOsUi.dp(this,3),0,0);c.addView(l);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,52),1);p.setMargins(0,0,LifeOsUi.dp(this,6),0);row.addView(c,p);}
    private View loopRow(LifeDb.Loop l){LifeDb.Event e=db.eventById(l.evidenceId);String title=e==null?UserFacingText.humanize(l.title):PresentationSemantics.title(this,e);String summary=e==null?UserFacingText.humanize(l.title):PresentationSemantics.summary(this,e);LinearLayout row=relatedRow(LifeOsIconView.COMMITMENT,LifeOsUi.RED,title,summary);row.setOnClickListener(v->startActivity(EntityDetailActivity.intent(this,"Commitment",title,summary,l.evidenceId)));return row;}
    private View actionRow(PersistentActionQueue.Item a){String title=UserFacingText.humanize(a.proposal.payloadSummary.isEmpty()?a.proposal.actionType:a.proposal.payloadSummary);LinearLayout row=relatedRow(LifeOsIconView.ACTION,LifeOsUi.GREEN,title,a.proposal.target);row.setOnClickListener(v->startActivity(new Intent(this,SuggestedActionDetailActivity.class).putExtra("proposal_id",a.proposal.proposalId)));return row;}
    private LinearLayout relatedRow(String icon,int color,String title,String summary){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(0,LifeOsUi.dp(this,6),0,LifeOsUi.dp(this,6));row.addView(LifeOsUi.iconTile(this,icon,color,34),new LinearLayout.LayoutParams(LifeOsUi.dp(this,34),LifeOsUi.dp(this,34)));LinearLayout copy=new LinearLayout(this);copy.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);p.setMargins(LifeOsUi.dp(this,9),0,LifeOsUi.dp(this,7),0);row.addView(copy,p);TextView t=LifeOsUi.text(this,title,11.5f,LifeOsUi.TEXT);LifeOsUi.weight(t,600);t.setMaxLines(1);copy.addView(t);TextView s=LifeOsUi.text(this,summary,9.7f,LifeOsUi.MUTED);LifeOsUi.weight(s,500);s.setMaxLines(1);copy.addView(s);row.addView(LifeOsUi.icon(this,LifeOsIconView.CHEVRON,LifeOsUi.TERTIARY,11),new LinearLayout.LayoutParams(LifeOsUi.dp(this,11),LifeOsUi.dp(this,18)));return row;}
    private View evidenceRow(LifeDb.Event e){String title=PresentationSemantics.title(this,e),summary=PresentationSemantics.summary(this,e);LinearLayout row=relatedRow(LifeOsIconView.FILE,LifeOsUi.BLUE,title,summary);row.setOnClickListener(v->startActivity(new Intent(this,EvidenceDetailActivity.class).putExtra("event_id",e.id).putExtra("mode","situation")));return row;}
    private String safeSummary(){String raw=UserFacingText.humanize(situation.summary);if(raw.matches(".*\\d{8,}.*")||raw.startsWith("Request ·")||raw.length()>180){String counts=(situation.attentionCount>0?situation.attentionCount+" open item"+(situation.attentionCount==1?"":"s"):"")+(situation.actionCount>0?(situation.attentionCount>0?" · ":"")+situation.actionCount+" action"+(situation.actionCount==1?"":"s")+" ready":"");return (UserFacingText.humanize(situation.why)+(counts.isEmpty()?"":" · "+counts)).trim();}return raw;}
    private LifeDb.Loop findLoop(long id){for(LifeDb.Loop x:db.openLoops(250))if(x.id==id)return x;return null;}
    private PersistentActionQueue.Item findAction(String id){for(PersistentActionQueue.Item x:actions)if(x.proposal.proposalId.equals(id))return x;return null;}
    private static String join(List<String> xs){StringBuilder b=new StringBuilder();for(String x:xs){if(b.length()>0)b.append(" · ");b.append(x.replace('_',' '));}return b.toString();}
}
