package com.kareem.lifeos;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import com.kareem.lifeos.actions.PersistentActionQueue;
import com.kareem.lifeos.actions.TeyaApprovalReceiver;

/** Suggested action is a connected entity with rationale, evidence and explicit approval. */
public final class SuggestedActionDetailActivity extends Activity {
    private PersistentActionQueue queue;private PersistentActionQueue.Item item;private LifeDb db;private String id;
    @Override public void onCreate(Bundle s){super.onCreate(s);queue=new PersistentActionQueue(this);db=new LifeDb(this);id=getIntent().getStringExtra("proposal_id");for(PersistentActionQueue.Item x:queue.history())if(x.proposal.proposalId.equals(id)){item=x;break;}render();}
    @Override protected void onDestroy(){db.close();super.onDestroy();}

    private void render(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(LifeOsUi.BG);root.addView(LifeOsUi.detailTopBar(this,"Suggested action"));ScrollView sc=new ScrollView(this);sc.setVerticalScrollBarEnabled(false);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(LifeOsUi.dp(this,16),LifeOsUi.dp(this,7),LifeOsUi.dp(this,16),LifeOsUi.dp(this,24));sc.addView(body);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));if(item==null){TextView none=LifeOsUi.text(this,"This suggestion is no longer available.",11.5f,LifeOsUi.MUTED);LifeOsUi.weight(none,500);body.addView(none);setContentView(root);return;}
        TextView eyebrow=LifeOsUi.text(this,human(item.proposal.actionType).toUpperCase(),9.5f,LifeOsUi.GREEN);LifeOsUi.weight(eyebrow,700);body.addView(eyebrow);String headline=item.proposal.payloadSummary.isEmpty()?human(item.proposal.actionType):UserFacingText.humanize(item.proposal.payloadSummary);TextView h=LifeOsUi.text(this,headline,20f,LifeOsUi.TEXT);LifeOsUi.weight(h,700);h.setPadding(0,LifeOsUi.dp(this,4),0,0);body.addView(h);if(!item.proposal.target.isEmpty()){TextView target=LifeOsUi.text(this,UserFacingText.humanize(item.proposal.target),10.2f,LifeOsUi.MUTED);LifeOsUi.weight(target,500);target.setPadding(0,LifeOsUi.dp(this,3),0,0);body.addView(target);}
        body.addView(LifeOsUi.section(this,"Summary"));LinearLayout summary=LifeOsUi.card(this);TextView sv=LifeOsUi.text(this,"LifeOS prepared this action for review. Nothing is executed until you explicitly approve it.",11.2f,LifeOsUi.TEXT);LifeOsUi.weight(sv,500);summary.addView(sv);body.addView(summary);
        body.addView(LifeOsUi.section(this,"What matters"));LinearLayout facts=new LinearLayout(this);stat(facts,String.valueOf(item.proposal.evidenceIds.size()),"Evidence",LifeOsIconView.FILE,LifeOsUi.BLUE);stat(facts,risk(item.proposal.risk.name()),"Safety",LifeOsIconView.CHECK,LifeOsUi.GREEN);body.addView(facts);
        if(!item.proposal.situationId.isEmpty()){body.addView(LifeOsUi.section(this,"Related"));LinearLayout rel=LifeOsUi.card(this);TextView rt=LifeOsUi.text(this,"Connected to an active LifeOS situation",11f,LifeOsUi.TEXT);LifeOsUi.weight(rt,600);rel.addView(rt);TextView rs=LifeOsUi.text(this,"Open the related context before approving if you want to verify why this action was suggested.",9.8f,LifeOsUi.MUTED);LifeOsUi.weight(rs,500);rs.setPadding(0,LifeOsUi.dp(this,3),0,0);rel.addView(rs);rel.setOnClickListener(v->startActivity(new Intent(this,SituationDetailActivity.class).putExtra("situation_id",item.proposal.situationId)));body.addView(rel);}
        body.addView(LifeOsUi.section(this,"Evidence"));int shown=0;for(String evidence:item.proposal.evidenceIds){long eventId=parseEventId(evidence);if(eventId<=0)continue;LifeDb.Event e=db.eventById(eventId);if(e==null)continue;body.addView(evidenceRow(e));shown++;}if(shown==0){TextView no=LifeOsUi.text(this,"No directly readable evidence item is available for this action.",10.4f,LifeOsUi.MUTED);LifeOsUi.weight(no,500);body.addView(no);}
        body.addView(LifeOsUi.section(this,"Actions"));LinearLayout buttons=new LinearLayout(this);Button dismiss=LifeOsUi.button(this,"Dismiss");dismiss.setTextColor(LifeOsUi.RED);dismiss.setOnClickListener(v->{queue.decide(id,false);finish();});buttons.addView(dismiss,new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,44),1));Button approve=LifeOsUi.primary(this,"Approve");approve.setOnClickListener(v->{queue.decide(id,true);TeyaApprovalReceiver.executeApproved(this,item);finish();});LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,44),1);ap.setMargins(LifeOsUi.dp(this,8),0,0,0);buttons.addView(approve,ap);body.addView(buttons);setContentView(root);
    }

    private void stat(LinearLayout row,String value,String label,String icon,int color){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(LifeOsUi.dp(this,9),LifeOsUi.dp(this,8),LifeOsUi.dp(this,7),LifeOsUi.dp(this,7));c.setBackground(LifeOsUi.round(this,LifeOsUi.SURFACE,LifeOsUi.BORDER,12));LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.addView(LifeOsUi.icon(this,icon,color,12),new LinearLayout.LayoutParams(LifeOsUi.dp(this,12),LifeOsUi.dp(this,12)));TextView n=LifeOsUi.text(this,value,11.4f,color);LifeOsUi.weight(n,700);LinearLayout.LayoutParams np=new LinearLayout.LayoutParams(-2,-2);np.leftMargin=LifeOsUi.dp(this,5);top.addView(n,np);c.addView(top);TextView l=LifeOsUi.text(this,label,8.9f,LifeOsUi.MUTED);LifeOsUi.weight(l,500);l.setPadding(0,LifeOsUi.dp(this,3),0,0);c.addView(l);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,54),1);p.setMargins(0,0,LifeOsUi.dp(this,7),0);row.addView(c,p);}
    private View evidenceRow(LifeDb.Event e){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(0,LifeOsUi.dp(this,6),0,LifeOsUi.dp(this,6));row.addView(LifeOsUi.appIcon(this,e.app,34),new LinearLayout.LayoutParams(LifeOsUi.dp(this,34),LifeOsUi.dp(this,34)));LinearLayout copy=new LinearLayout(this);copy.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);p.setMargins(LifeOsUi.dp(this,9),0,LifeOsUi.dp(this,7),0);row.addView(copy,p);TextView t=LifeOsUi.text(this,PresentationSemantics.title(this,e),11.5f,LifeOsUi.TEXT);LifeOsUi.weight(t,600);t.setMaxLines(1);copy.addView(t);TextView s=LifeOsUi.text(this,PresentationSemantics.summary(this,e),9.8f,LifeOsUi.MUTED);LifeOsUi.weight(s,500);s.setMaxLines(2);copy.addView(s);row.addView(LifeOsUi.icon(this,LifeOsIconView.CHEVRON,LifeOsUi.TERTIARY,11),new LinearLayout.LayoutParams(LifeOsUi.dp(this,11),LifeOsUi.dp(this,18)));row.setOnClickListener(v->startActivity(new Intent(this,EvidenceDetailActivity.class).putExtra("event_id",e.id).putExtra("mode","action")));return row;}
    private static long parseEventId(String s){if(s==null)return 0;String d=s.replaceAll("[^0-9]","");try{return d.isEmpty()?0:Long.parseLong(d);}catch(Exception e){return 0;}}
    private static String human(String value){String x=value==null?"":value.replace('_',' ').trim().toLowerCase();return x.isEmpty()?"Action":Character.toUpperCase(x.charAt(0))+x.substring(1);}
    private static String risk(String value){if("READ_ONLY".equals(value))return "Review only";if("REVERSIBLE_WRITE".equals(value))return "Reversible";if("IRREVERSIBLE_WRITE".equals(value))return "Explicit approval";return "Sensitive";}
}
