package com.kareem.lifeos;

import android.app.Activity;
import android.content.Intent;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import com.kareem.lifeos.actions.PersistentActionQueue;

public final class SuggestedActionDetailActivity extends Activity {
    private static final int BG=Color.rgb(13,17,23),SURFACE=Color.rgb(22,27,34),BORDER=Color.rgb(48,54,61),TEXT=Color.rgb(230,237,243),MUTED=Color.rgb(139,148,158),GREEN=Color.rgb(63,185,80),BLUE=Color.rgb(47,129,247),RED=Color.rgb(248,81,73);
    private PersistentActionQueue queue;private PersistentActionQueue.Item item;private LifeDb db;private String id;
    @Override public void onCreate(Bundle s){super.onCreate(s);queue=new PersistentActionQueue(this);db=new LifeDb(this);id=getIntent().getStringExtra("proposal_id");for(PersistentActionQueue.Item x:queue.history())if(x.proposal.proposalId.equals(id)){item=x;break;}render();}
    @Override protected void onDestroy(){db.close();super.onDestroy();}
    private void render(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.setPadding(dp(12),dp(10),dp(16),dp(8));top.setBackgroundColor(SURFACE);Button back=plain("‹");back.setContentDescription("Back");back.setOnClickListener(v->finish());top.addView(back,new LinearLayout.LayoutParams(dp(48),dp(48)));TextView title=text("Suggested action",22,TEXT);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);top.addView(title);root.addView(top);root.addView(divider());ScrollView sc=new ScrollView(this);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(16),dp(18),dp(16),dp(28));sc.addView(body);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));if(item==null){body.addView(text("This suggestion is no longer available.",14,MUTED));setContentView(root);return;}TextView badge=text(human(item.proposal.actionType).toUpperCase(),11,GREEN);badge.setTypeface(Typeface.DEFAULT,Typeface.BOLD);body.addView(badge);TextView h=text(item.proposal.payloadSummary.isEmpty()?human(item.proposal.actionType):item.proposal.payloadSummary,21,TEXT);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);h.setPadding(0,dp(9),0,dp(4));body.addView(h);body.addView(text(item.proposal.target,13,MUTED));LinearLayout why=row();TextView wh=text("Why LifeOS suggested this",13,GREEN);wh.setTypeface(Typeface.DEFAULT,Typeface.BOLD);why.addView(wh);why.addView(text((item.proposal.situationId.isEmpty()?"No related situation":"Related to a LifeOS situation")+"\nApproval: "+risk(item.proposal.risk.name())+"\nEvidence: "+item.proposal.evidenceIds.size()+" linked item(s)",14,TEXT));body.addView(why);if(!item.proposal.evidenceIds.isEmpty()){TextView eh=text("Evidence",18,TEXT);eh.setTypeface(Typeface.DEFAULT,Typeface.BOLD);eh.setPadding(0,dp(20),0,dp(8));body.addView(eh);for(String e:item.proposal.evidenceIds){long eventId=parseEventId(e);if(eventId<=0)continue;LifeDb.Event ev=db.eventById(eventId);if(ev==null)continue;LinearLayout c=row();TextView t=text(ev.title,14,TEXT);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);c.addView(t);c.addView(text(trim(ev.body,220),13,TEXT));c.setOnClickListener(v->startActivity(new Intent(this,EvidenceDetailActivity.class).putExtra("event_id",eventId).putExtra("mode","action")));body.addView(c);}}
        LinearLayout buttons=new LinearLayout(this);buttons.setOrientation(LinearLayout.HORIZONTAL);Button approve=primary("Approve");approve.setOnClickListener(v->{queue.decide(id,true);finish();});buttons.addView(approve,new LinearLayout.LayoutParams(0,dp(48),1));Button deny=secondary("Dismiss");deny.setTextColor(RED);deny.setOnClickListener(v->{queue.decide(id,false);finish();});LinearLayout.LayoutParams dpv=new LinearLayout.LayoutParams(0,dp(48),1);dpv.setMargins(dp(8),0,0,0);buttons.addView(deny,dpv);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,-2);bp.setMargins(0,dp(18),0,0);body.addView(buttons,bp);setContentView(root);}
    private static long parseEventId(String s){if(s==null)return 0;String d=s.replaceAll("[^0-9]","");try{return d.isEmpty()?0:Long.parseLong(d);}catch(Exception e){return 0;}}
    private static String trim(String s,int n){if(s==null)return "";s=s.trim();return s.length()>n?s.substring(0,n)+"…":s;}
    private LinearLayout row(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(14),dp(13),dp(14),dp(13));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(12),0,0);c.setLayoutParams(p);c.setBackground(round(SURFACE,BORDER,9));return c;}private Button plain(String s){Button b=new Button(this);b.setText(s);b.setTextColor(TEXT);b.setTextSize(18);b.setAllCaps(false);b.setBackgroundColor(Color.TRANSPARENT);return b;}private Button secondary(String s){Button b=plain(s);b.setTextSize(13);b.setBackground(round(SURFACE,BORDER,8));return b;}private Button primary(String s){Button b=secondary(s);b.setTextColor(Color.WHITE);b.setBackground(round(BLUE,BLUE,8));return b;}private View divider(){View v=new View(this);v.setBackgroundColor(BORDER);v.setLayoutParams(new LinearLayout.LayoutParams(-1,dp(1)));return v;}private GradientDrawable round(int fill,int stroke,int radius){GradientDrawable g=new GradientDrawable();g.setColor(fill);g.setCornerRadius(dp(radius));g.setStroke(dp(1),stroke);return g;}private TextView text(String s,int size,int color){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(color);v.setLineSpacing(0,1.08f);return v;}private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}private static String human(String value){String x=value==null?"":value.replace('_',' ').trim().toLowerCase();return x.isEmpty()?"Action":Character.toUpperCase(x.charAt(0))+x.substring(1);}private static String risk(String value){if("READ_ONLY".equals(value))return "Review only";if("REVERSIBLE_WRITE".equals(value))return "Can be undone";if("IRREVERSIBLE_WRITE".equals(value))return "Cannot be undone";return "Sensitive action";}
}
