package com.kareem.lifeos;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;

/** Human-facing status for the LifeOS ring: idle, analyzing, or setup attention. */
public final class SystemStatusActivity extends Activity {
    @Override public void onCreate(Bundle state){super.onCreate(state);render();}
    @Override protected void onResume(){super.onResume();render();}
    private void render(){IntelligenceStatus.Snapshot s=IntelligenceStatus.snapshot(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(LifeOsUi.BG);root.addView(LifeOsUi.detailTopBar(this,"LifeOS status"));ScrollView sc=new ScrollView(this);sc.setVerticalScrollBarEnabled(false);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setGravity(Gravity.CENTER_HORIZONTAL);body.setPadding(LifeOsUi.dp(this,16),LifeOsUi.dp(this,18),LifeOsUi.dp(this,16),LifeOsUi.dp(this,24));sc.addView(body);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));View ring=LifeOsUi.statusRing(this,s,74);body.addView(ring,new LinearLayout.LayoutParams(LifeOsUi.dp(this,88),LifeOsUi.dp(this,88)));TextView h=LifeOsUi.text(this,stateTitle(s),19f,LifeOsUi.TEXT);LifeOsUi.weight(h,700);h.setGravity(Gravity.CENTER);h.setPadding(0,LifeOsUi.dp(this,8),0,0);body.addView(h);TextView sub=LifeOsUi.text(this,stateDescription(s),10.8f,LifeOsUi.MUTED);LifeOsUi.weight(sub,500);sub.setGravity(Gravity.CENTER);sub.setPadding(0,LifeOsUi.dp(this,4),0,LifeOsUi.dp(this,14));body.addView(sub);
        LinearLayout stats=new LinearLayout(this);stat(stats,String.valueOf(s.ready),"Analyzed",LifeOsIconView.CHECK,LifeOsUi.BLUE);stat(stats,String.valueOf(s.pending),"Pending",LifeOsIconView.UPCOMING,s.pending>0?LifeOsUi.PURPLE:LifeOsUi.TERTIARY);stat(stats,String.valueOf(s.open),"Attention",LifeOsIconView.ALERT,s.open>0?LifeOsUi.RED:LifeOsUi.TERTIARY);body.addView(stats,new LinearLayout.LayoutParams(-1,-2));
        body.addView(LifeOsUi.section(this,"Background intelligence"));LinearLayout model=LifeOsUi.card(this);TextView mt=LifeOsUi.text(this,human(s.modelState),11.8f,LifeOsUi.TEXT);LifeOsUi.weight(mt,600);model.addView(mt);String progress=s.modelProgress>0?" · "+s.modelProgress+"%":"";TextView ms=LifeOsUi.text(this,(s.backgroundRunning?"Processing now":"Background worker idle")+progress,10f,LifeOsUi.MUTED);LifeOsUi.weight(ms,500);ms.setPadding(0,LifeOsUi.dp(this,3),0,0);model.addView(ms);body.addView(model);
        android.widget.Button settings=LifeOsUi.button(this,"Settings & permissions");settings.setOnClickListener(v->startActivity(new Intent(this,MainActivity.class)));body.addView(settings,new LinearLayout.LayoutParams(-1,LifeOsUi.dp(this,44)));setContentView(root);}
    private void stat(LinearLayout row,String value,String label,String icon,int color){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(LifeOsUi.dp(this,8),LifeOsUi.dp(this,7),LifeOsUi.dp(this,6),LifeOsUi.dp(this,6));c.setBackground(LifeOsUi.round(this,LifeOsUi.SURFACE,LifeOsUi.BORDER,12));LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.addView(LifeOsUi.icon(this,icon,color,12),new LinearLayout.LayoutParams(LifeOsUi.dp(this,12),LifeOsUi.dp(this,12)));TextView n=LifeOsUi.text(this,value,14f,color);LifeOsUi.weight(n,700);LinearLayout.LayoutParams np=new LinearLayout.LayoutParams(-2,-2);np.leftMargin=LifeOsUi.dp(this,5);top.addView(n,np);c.addView(top);TextView l=LifeOsUi.text(this,label,8.9f,LifeOsUi.MUTED);LifeOsUi.weight(l,500);l.setPadding(0,LifeOsUi.dp(this,3),0,0);c.addView(l);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,52),1);p.setMargins(0,0,LifeOsUi.dp(this,6),0);row.addView(c,p);}
    private static String stateTitle(IntelligenceStatus.Snapshot s){if("download_failed".equals(s.modelState)||"download_paused".equals(s.modelState)||"unavailable".equals(s.modelState))return "LifeOS needs attention";if(s.pending>0||s.backgroundRunning||"downloading".equals(s.modelState)||"verifying".equals(s.modelState))return "LifeOS is analyzing";return "LifeOS is ready";}
    private static String stateDescription(IntelligenceStatus.Snapshot s){if("download_failed".equals(s.modelState)||"download_paused".equals(s.modelState)||"unavailable".equals(s.modelState))return "Background intelligence setup needs action. Your captured data remains stored locally.";if(s.pending>0||s.backgroundRunning)return "LifeOS is processing grounded context in the background.";if("downloading".equals(s.modelState)||"verifying".equals(s.modelState))return "The background intelligence model is being prepared.";return "Nothing is waiting to be processed right now.";}
    private static String human(String x){String v=x==null?"unknown":x.replace('_',' ').trim();return v.isEmpty()?"Unknown":Character.toUpperCase(v.charAt(0))+v.substring(1);}
}
