package com.kareem.lifeos;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.FrameLayout;
import android.widget.HorizontalScrollView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/** Timeline = canonical meaningful history, not a raw notification log. */
public final class TimelineActivity extends Activity {
    private LinearLayout content;private String filter="All";private HorizontalScrollView filterStrip;private final Map<String,Button> chipViews=new LinkedHashMap<>();
    @Override public void onCreate(Bundle s){super.onCreate(s);String f=getIntent().getStringExtra("filter");if(f!=null&&!f.trim().isEmpty())filter=f;render();}
    @Override protected void onResume(){super.onResume();show();}

    private void render(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(LifeOsUi.BG);LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);head.setPadding(LifeOsUi.dp(this,16),LifeOsUi.dp(this,8),LifeOsUi.dp(this,9),LifeOsUi.dp(this,5));TextView title=LifeOsUi.text(this,"Timeline",21.2f,LifeOsUi.TEXT);LifeOsUi.weight(title,700);head.addView(title,new LinearLayout.LayoutParams(0,-2,1));View search=LifeOsUi.iconTouch(this,LifeOsIconView.SEARCH,LifeOsUi.TEXT,22,42);search.setContentDescription("Search timeline");search.setOnClickListener(v->LifeOsUi.go(this,SearchActivity.class));head.addView(search,new LinearLayout.LayoutParams(LifeOsUi.dp(this,42),LifeOsUi.dp(this,42)));View filters=LifeOsUi.iconTouch(this,LifeOsIconView.FILTER,LifeOsUi.TEXT,22,42);filters.setContentDescription("Show or hide timeline filters");filters.setOnClickListener(v->filterStrip.setVisibility(filterStrip.getVisibility()==View.VISIBLE?View.GONE:View.VISIBLE));head.addView(filters,new LinearLayout.LayoutParams(LifeOsUi.dp(this,42),LifeOsUi.dp(this,42)));root.addView(head);
        filterStrip=new HorizontalScrollView(this);filterStrip.setHorizontalScrollBarEnabled(false);LinearLayout chips=new LinearLayout(this);chips.setPadding(LifeOsUi.dp(this,16),0,LifeOsUi.dp(this,8),LifeOsUi.dp(this,7));for(String x:new String[]{"All","Messages","Emails","Calls","Events"}){Button b=LifeOsUi.chip(this,x,x.equals(filter));b.setOnClickListener(v->{filter=x;updateChips();show();});chipViews.put(x,b);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,LifeOsUi.dp(this,34));p.setMargins(0,0,LifeOsUi.dp(this,7),0);chips.addView(b,p);}filterStrip.addView(chips);root.addView(filterStrip);
        ScrollView sc=new ScrollView(this);sc.setVerticalScrollBarEnabled(false);sc.setFillViewport(true);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(LifeOsUi.dp(this,16),0,LifeOsUi.dp(this,16),LifeOsUi.dp(this,10));sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));root.addView(LifeOsUi.bottomNav(this,TimelineActivity.class));setContentView(root);}
    private void updateChips(){for(Map.Entry<String,Button> e:chipViews.entrySet()){boolean on=e.getKey().equals(filter);e.getValue().setBackground(LifeOsUi.round(this,on?LifeOsUi.BLUE:LifeOsUi.SURFACE_2,on?LifeOsUi.BLUE:LifeOsUi.BORDER,18));e.getValue().setTextColor(on?android.graphics.Color.WHITE:LifeOsUi.TEXT);}}
    private void show(){if(content==null)return;content.removeAllViews();List<CanonicalTimelineRepository.TimelineObject> xs=CanonicalTimelineRepository.recent(this,180);String lastDay="";int shown=0;for(CanonicalTimelineRepository.TimelineObject e:xs){if(!matches(e))continue;String day=dayKey(e.at);if(!day.equals(lastDay)){TextView h=LifeOsUi.text(this,dayLabel(e.at),11.8f,LifeOsUi.MUTED);LifeOsUi.weight(h,600);h.setPadding(0,LifeOsUi.dp(this,13),0,LifeOsUi.dp(this,5));content.addView(h);lastDay=day;}timelineRow(e);shown++;if(shown>=140)break;}if(shown==0){TextView none=LifeOsUi.text(this,"No canonical meaningful activity in this filter yet.",11.5f,LifeOsUi.MUTED);LifeOsUi.weight(none,500);none.setPadding(0,LifeOsUi.dp(this,15),0,0);content.addView(none);}}
    private void timelineRow(CanonicalTimelineRepository.TimelineObject e){final int rowH=64;LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);TextView time=LifeOsUi.text(this,new SimpleDateFormat("HH:mm",Locale.getDefault()).format(new Date(e.at)),10.1f,LifeOsUi.MUTED);LifeOsUi.weight(time,500);time.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);row.addView(time,new LinearLayout.LayoutParams(LifeOsUi.dp(this,49),LifeOsUi.dp(this,rowH)));FrameLayout marker=new FrameLayout(this);View line=new View(this);line.setBackgroundColor(LifeOsUi.BORDER);marker.addView(line,new FrameLayout.LayoutParams(LifeOsUi.dp(this,1),-1,Gravity.CENTER_HORIZONTAL));View dot=new View(this);dot.setBackground(LifeOsUi.round(this,accent(e.kind),android.graphics.Color.TRANSPARENT,20));marker.addView(dot,new FrameLayout.LayoutParams(LifeOsUi.dp(this,7),LifeOsUi.dp(this,7),Gravity.CENTER));row.addView(marker,new LinearLayout.LayoutParams(LifeOsUi.dp(this,27),LifeOsUi.dp(this,rowH)));View icon=e.calendar?LifeOsUi.iconTile(this,LifeOsIconView.EVENT,LifeOsUi.PURPLE,36):LifeOsUi.appIcon(this,e.sourcePackage,36);LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(LifeOsUi.dp(this,36),LifeOsUi.dp(this,36));ip.setMargins(0,0,LifeOsUi.dp(this,10),0);row.addView(icon,ip);LinearLayout txt=new LinearLayout(this);txt.setOrientation(LinearLayout.VERTICAL);txt.setGravity(Gravity.CENTER_VERTICAL);TextView title=LifeOsUi.text(this,e.title,12.6f,LifeOsUi.TEXT);LifeOsUi.weight(title,700);title.setMaxLines(1);txt.addView(title);if(!e.summary.isEmpty()){TextView body=LifeOsUi.text(this,e.summary,10.7f,LifeOsUi.MUTED);LifeOsUi.weight(body,500);body.setPadding(0,LifeOsUi.dp(this,2),0,0);body.setMaxLines(1);txt.addView(body);}row.addView(txt,new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,rowH),1));row.addView(LifeOsUi.icon(this,LifeOsIconView.CHEVRON,LifeOsUi.TERTIARY,12),new LinearLayout.LayoutParams(LifeOsUi.dp(this,12),LifeOsUi.dp(this,20)));row.setOnClickListener(v->openEvent(e));content.addView(row);}
    private void openEvent(CanonicalTimelineRepository.TimelineObject e){if(e.calendar){String objectId=e.id.startsWith("timeline:")?e.id.substring("timeline:".length()):e.id;startActivity(new Intent(this,FunctionalObjectDetailActivity.class).putExtra("capability_id","events").putExtra("object_id",objectId));return;}try(LifeDb db=new LifeDb(this)){LifeDb.Event raw=db.eventById(e.eventId);if(raw!=null&&LifeDb.isConversationLike(raw)){String id=ConversationRepository.idFor(raw.app,raw.threadKey,LifeDb.personLabel(raw));startActivity(new Intent(this,ConversationDetailActivity.class).putExtra("conversation_id",id));return;}}startActivity(new Intent(this,EvidenceDetailActivity.class).putExtra("event_id",e.eventId).putExtra("mode","timeline"));}
    private boolean matches(CanonicalTimelineRepository.TimelineObject e){if("All".equals(filter))return true;if("Messages".equals(filter))return "Message".equals(e.kind);if("Emails".equals(filter))return "Email".equals(e.kind);if("Calls".equals(filter))return "Call".equals(e.kind);return "Events".equals(filter)&&"Event".equals(e.kind);}
    private int accent(String kind){if("Security".equals(kind)||"Finance".equals(kind))return LifeOsUi.RED;if("Event".equals(kind))return LifeOsUi.PURPLE;if("Delivery".equals(kind))return LifeOsUi.AMBER;return LifeOsUi.BLUE;}
    private String dayKey(long at){return new SimpleDateFormat("yyyyMMdd",Locale.US).format(new Date(at));}
    private String dayLabel(long at){long now=System.currentTimeMillis(),day=86400000L;String d=new SimpleDateFormat("EEE, d MMM yyyy",Locale.getDefault()).format(new Date(at));String a=dayKey(at),today=dayKey(now),yesterday=dayKey(now-day);if(a.equals(today))return "Today  ·  "+d;if(a.equals(yesterday))return "Yesterday  ·  "+d;return d;}
}
