package com.kareem.lifeos;

import android.Manifest;
import android.app.Activity;
import android.content.pm.PackageManager;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.TextView;
import android.widget.Toast;
import java.io.File;
import java.util.Locale;

/** First-party Voice Memory capture. Recording is saved before transcription is attempted. */
public final class VoiceRecorderActivity extends Activity {
    private static final int MIC_PERMISSION=621;private final Handler ui=new Handler(Looper.getMainLooper());private final VoiceCapture capture=new VoiceCapture();private TextView timer,status;private Button record,stop;private File file;private boolean stopping;
    private final Runnable tick=new Runnable(){public void run(){if(capture.isRunning()){timer.setText(time(capture.elapsedMs()));ui.postDelayed(this,250);}}};
    @Override public void onCreate(Bundle s){super.onCreate(s);render();}
    @Override protected void onDestroy(){if(capture.isRunning())try{capture.stop();}catch(Exception ignored){}ui.removeCallbacks(tick);super.onDestroy();}

    private void render(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(LifeOsUi.BG);root.addView(LifeOsUi.detailTopBar(this,"Voice memory"));LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setGravity(Gravity.CENTER_HORIZONTAL);body.setPadding(LifeOsUi.dp(this,24),LifeOsUi.dp(this,32),LifeOsUi.dp(this,24),LifeOsUi.dp(this,24));root.addView(body,new LinearLayout.LayoutParams(-1,0,1));body.addView(LifeOsUi.iconTile(this,LifeOsIconView.MIC,LifeOsUi.BLUE,72),new LinearLayout.LayoutParams(LifeOsUi.dp(this,72),LifeOsUi.dp(this,72)));TextView title=LifeOsUi.text(this,"Capture a voice memory",20f,LifeOsUi.TEXT);LifeOsUi.weight(title,700);title.setGravity(Gravity.CENTER);title.setPadding(0,LifeOsUi.dp(this,16),0,0);body.addView(title);TextView sub=LifeOsUi.text(this,"The WAV is saved first. Transcription can fail or be retried without losing the recording.",10.8f,LifeOsUi.MUTED);LifeOsUi.weight(sub,500);sub.setGravity(Gravity.CENTER);sub.setPadding(LifeOsUi.dp(this,12),LifeOsUi.dp(this,6),LifeOsUi.dp(this,12),LifeOsUi.dp(this,24));body.addView(sub);timer=LifeOsUi.text(this,"00:00",31f,LifeOsUi.TEXT);LifeOsUi.weight(timer,700);timer.setGravity(Gravity.CENTER);body.addView(timer);status=LifeOsUi.text(this,"Ready to record",10.5f,LifeOsUi.MUTED);LifeOsUi.weight(status,500);status.setGravity(Gravity.CENTER);status.setPadding(0,LifeOsUi.dp(this,7),0,LifeOsUi.dp(this,26));body.addView(status);LinearLayout actions=new LinearLayout(this);record=LifeOsUi.primary(this,"Start recording");record.setOnClickListener(v->start());actions.addView(record,new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,50),1));stop=LifeOsUi.button(this,"Stop & save");stop.setEnabled(false);stop.setOnClickListener(v->stopAndSave());LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,50),1);sp.setMargins(LifeOsUi.dp(this,8),0,0,0);actions.addView(stop,sp);body.addView(actions,new LinearLayout.LayoutParams(-1,-2));TextView note=LifeOsUi.text(this,"Mixed Arabic + English transcription uses the existing server-side voice service; no ASR provider credential is stored in the APK.",9.4f,LifeOsUi.TERTIARY);LifeOsUi.weight(note,500);note.setGravity(Gravity.CENTER);note.setPadding(LifeOsUi.dp(this,6),LifeOsUi.dp(this,18),LifeOsUi.dp(this,6),0);body.addView(note);setContentView(root);}
    private void start(){if(stopping||capture.isRunning())return;if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},MIC_PERMISSION);return;}try{file=capture.start(this);timer.setText("00:00");status.setText("Recording · WAV 16 kHz mono");status.setTextColor(LifeOsUi.RED);record.setEnabled(false);stop.setEnabled(true);ui.post(tick);}catch(Exception e){Toast.makeText(this,"Recorder could not start: "+safe(e),Toast.LENGTH_LONG).show();}}
    private void stopAndSave(){if(stopping||!capture.isRunning())return;stopping=true;ui.removeCallbacks(tick);try{File saved=capture.stop();long duration=capture.audioDurationMs();if(saved==null||!saved.exists()||saved.length()<=44)throw new IllegalStateException("Recording is empty");VoiceMemoryRepository.VoiceObject voice=VoiceMemoryRepository.register(this,saved,duration);if(voice==null)throw new IllegalStateException("Recording could not be registered");timer.setText(time(duration));status.setText("Saved locally · transcription starting…");status.setTextColor(LifeOsUi.GREEN);record.setEnabled(false);stop.setEnabled(false);VoiceMemoryRepository.transcribe(this,voice.id,new VoiceMemoryRepository.Callback(){public void ok(VoiceMemoryRepository.VoiceObject v){stopping=false;status.setText("Saved & transcribed");status.setTextColor(LifeOsUi.GREEN);startActivity(new android.content.Intent(VoiceRecorderActivity.this,VoiceMemoryDetailActivity.class).putExtra("voice_id",v.id));finish();}public void fail(VoiceMemoryRepository.VoiceObject v,Exception error){stopping=false;status.setText("Recording saved · transcription can be retried");status.setTextColor(LifeOsUi.AMBER);Toast.makeText(VoiceRecorderActivity.this,"Audio is safe. Transcription failed: "+safe(error),Toast.LENGTH_LONG).show();if(v!=null){startActivity(new android.content.Intent(VoiceRecorderActivity.this,VoiceMemoryDetailActivity.class).putExtra("voice_id",v.id));finish();}}});}catch(Exception e){stopping=false;status.setText("Could not save recording");status.setTextColor(LifeOsUi.RED);record.setEnabled(true);stop.setEnabled(false);Toast.makeText(this,"Save failed: "+safe(e),Toast.LENGTH_LONG).show();}}
    @Override public void onRequestPermissionsResult(int requestCode,String[] permissions,int[] results){super.onRequestPermissionsResult(requestCode,permissions,results);if(requestCode==MIC_PERMISSION&&results.length>0&&results[0]==PackageManager.PERMISSION_GRANTED)start();else if(requestCode==MIC_PERMISSION)Toast.makeText(this,"Microphone permission is required for Voice Memory.",Toast.LENGTH_LONG).show();}
    @Override public void onBackPressed(){if(capture.isRunning()){stopAndSave();return;}super.onBackPressed();}
    private static String time(long ms){long sec=Math.max(0,ms/1000);return String.format(Locale.US,"%02d:%02d",sec/60,sec%60);}private static String safe(Throwable e){String s=e==null?"Unknown error":e.getMessage();return s==null||s.trim().isEmpty()?e.getClass().getSimpleName():s;}
}
