package com.kareem.lifeos;

import android.app.Activity;
import android.content.Intent;
import android.media.MediaPlayer;
import android.os.Bundle;
import android.view.Gravity;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;

/** Voice memory detail: source audio -> transcript -> timed segments -> grounded actions. */
public final class VoiceMemoryDetailActivity extends Activity {
    private String voiceId;private LinearLayout body;private MediaPlayer player;
    @Override public void onCreate(Bundle s){super.onCreate(s);voiceId=getIntent().getStringExtra("voice_id");render();}
    @Override protected void onResume(){super.onResume();refresh();}
    @Override protected void onDestroy(){release();super.onDestroy();}
    private void render(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(LifeOsUi.BG);root.addView(LifeOsUi.detailTopBar(this,"Voice memory"));ScrollView sc=new ScrollView(this);sc.setVerticalScrollBarEnabled(false);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(LifeOsUi.dp(this,16),LifeOsUi.dp(this,7),LifeOsUi.dp(this,16),LifeOsUi.dp(this,24));sc.addView(body);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
    private void refresh(){if(body==null)return;body.removeAllViews();VoiceMemoryRepository.VoiceObject v=VoiceMemoryRepository.load(this,voiceId);if(v==null){TextView none=LifeOsUi.text(this,"Voice memory is no longer available.",11.5f,LifeOsUi.MUTED);body.addView(none);return;}TextView eyebrow=LifeOsUi.text(this,"VOICE MEMORY",9.5f,LifeOsUi.BLUE);LifeOsUi.weight(eyebrow,700);body.addView(eyebrow);TextView title=LifeOsUi.text(this,v.hasTranscript()?clip(v.transcript,70):"Recorded voice memory",18f,LifeOsUi.TEXT);LifeOsUi.weight(title,700);title.setPadding(0,LifeOsUi.dp(this,4),0,0);body.addView(title);TextView meta=LifeOsUi.text(this,new SimpleDateFormat("EEE, d MMM yyyy · HH:mm",Locale.getDefault()).format(new Date(v.createdAt))+" · "+time(v.durationMs)+" · "+humanBytes(v.sizeBytes),9.8f,LifeOsUi.MUTED);LifeOsUi.weight(meta,500);meta.setPadding(0,LifeOsUi.dp(this,3),0,0);body.addView(meta);
        body.addView(LifeOsUi.section(this,"Recording"));LinearLayout source=LifeOsUi.card(this);TextView saved=LifeOsUi.text(this,new File(v.filePath).exists()?"Original WAV saved locally":"Original audio file is missing",11f,new File(v.filePath).exists()?LifeOsUi.GREEN:LifeOsUi.RED);LifeOsUi.weight(saved,600);source.addView(saved);TextView path=LifeOsUi.text(this,"16 kHz mono PCM WAV · source retained independently from transcript",9.6f,LifeOsUi.MUTED);LifeOsUi.weight(path,500);path.setPadding(0,LifeOsUi.dp(this,3),0,0);source.addView(path);body.addView(source);
        body.addView(LifeOsUi.section(this,"Transcription"));LinearLayout tc=LifeOsUi.card(this);TextView state=LifeOsUi.text(this,human(v.status),10f,"transcribed".equals(v.status)?LifeOsUi.GREEN:"transcription_failed".equals(v.status)?LifeOsUi.AMBER:LifeOsUi.BLUE);LifeOsUi.weight(state,700);tc.addView(state);if(v.hasTranscript()){TextView transcript=LifeOsUi.text(this,v.transcript,11.4f,LifeOsUi.TEXT);LifeOsUi.weight(transcript,500);transcript.setTextIsSelectable(true);transcript.setPadding(0,LifeOsUi.dp(this,7),0,0);tc.addView(transcript);TextView engine=LifeOsUi.text(this,(v.language.isEmpty()?"":v.language+" · ")+(v.engine.isEmpty()?"":v.engine)+(v.engineVersion.isEmpty()?"":" · "+v.engineVersion),9.5f,LifeOsUi.MUTED);LifeOsUi.weight(engine,500);engine.setPadding(0,LifeOsUi.dp(this,5),0,0);tc.addView(engine);}else if(!v.error.isEmpty()){TextView error=LifeOsUi.text(this,v.error,9.8f,LifeOsUi.MUTED);LifeOsUi.weight(error,500);error.setPadding(0,LifeOsUi.dp(this,5),0,0);tc.addView(error);}body.addView(tc);
        List<VoiceTranscript.Segment> segments=v.segments(this);if(!segments.isEmpty()){body.addView(LifeOsUi.section(this,"Transcript segments"));LinearLayout seg=LifeOsUi.card(this);for(VoiceTranscript.Segment x:segments){TextView line=LifeOsUi.text(this,time(x.startMs)+"  "+x.text,10.4f,LifeOsUi.TEXT);LifeOsUi.weight(line,500);line.setPadding(0,LifeOsUi.dp(this,3),0,LifeOsUi.dp(this,3));seg.addView(line);}body.addView(seg);}
        body.addView(LifeOsUi.section(this,"Actions"));LinearLayout row=new LinearLayout(this);Button play=LifeOsUi.button(this,"Play recording");play.setOnClickListener(x->togglePlay(v,play));row.addView(play,new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,44),1));Button retry=LifeOsUi.button(this,v.hasTranscript()?"Re-transcribe":"Retry transcript");retry.setOnClickListener(x->retry(v));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(0,LifeOsUi.dp(this,44),1);rp.setMargins(LifeOsUi.dp(this,8),0,0,0);row.addView(retry,rp);body.addView(row);if(v.hasTranscript()){Button ask=LifeOsUi.primary(this,"Ask about this voice memory");ask.setOnClickListener(x->startActivity(new Intent(this,AskLifeOsActivity.class).putExtra("initial_question","Use my voice memory from "+new SimpleDateFormat("d MMM yyyy HH:mm",Locale.getDefault()).format(new Date(v.createdAt))+" and tell me what matters.")));LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,LifeOsUi.dp(this,44));ap.topMargin=LifeOsUi.dp(this,8);body.addView(ask,ap);}}
    private void togglePlay(VoiceMemoryRepository.VoiceObject v,Button button){try{if(player!=null&&player.isPlaying()){player.pause();button.setText("Resume recording");return;}if(player==null){File f=new File(v.filePath);if(!f.exists())throw new IllegalStateException("Audio file is missing");player=new MediaPlayer();player.setDataSource(f.getAbsolutePath());player.prepare();player.setOnCompletionListener(mp->{button.setText("Play recording");release();});}player.start();button.setText("Pause recording");}catch(Exception e){release();Toast.makeText(this,"Playback failed: "+safe(e),Toast.LENGTH_LONG).show();}}
    private void retry(VoiceMemoryRepository.VoiceObject v){VoiceMemoryStore.get(this).setStatus(v.id,"transcribing","");refresh();VoiceMemoryRepository.transcribe(this,v.id,new VoiceMemoryRepository.Callback(){public void ok(VoiceMemoryRepository.VoiceObject voice){refresh();Toast.makeText(VoiceMemoryDetailActivity.this,"Transcription complete",Toast.LENGTH_SHORT).show();}public void fail(VoiceMemoryRepository.VoiceObject voice,Exception error){refresh();Toast.makeText(VoiceMemoryDetailActivity.this,"Audio is safe; transcription failed: "+safe(error),Toast.LENGTH_LONG).show();}});}
    private void release(){if(player!=null){try{player.release();}catch(Exception ignored){}player=null;}}
    private static String clip(String x,int n){String s=x==null?"":x.replace('\n',' ').trim();return s.length()<=n?s:s.substring(0,n)+"…";}private static String time(long ms){long sec=Math.max(0,ms/1000);return String.format(Locale.US,"%02d:%02d",sec/60,sec%60);}private static String human(String x){String s=x==null?"unknown":x.replace('_',' ');return s.isEmpty()?"Unknown":Character.toUpperCase(s.charAt(0))+s.substring(1);}private static String humanBytes(long n){if(n<1024)return n+" B";if(n<1024L*1024)return String.format(Locale.US,"%.1f KB",n/1024.0);return String.format(Locale.US,"%.1f MB",n/(1024.0*1024));}private static String safe(Throwable e){String s=e==null?"Unknown":e.getMessage();return s==null||s.trim().isEmpty()?e.getClass().getSimpleName():s;}
}
